// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter, type Overrides } from 'ethers';
import { DiesisSettlementRouterAbi } from '../../generated/viem/DiesisSettlementRouter.abi.js';

export interface DiesisSettlementRouterContract {
  deposit(token: AddressLike, amount: BigNumberish, beneficiary: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  owner(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  renounceOwnership(overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setTokenAllowed(token: AddressLike, allowed: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  settlement(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  tokenAllowed(arg0: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  totalCustodied(arg0: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  transferOwnership(newOwner: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  withdraw(token: AddressLike, amount: BigNumberish, recipient: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    OwnershipTransferred(previousOwner?: AddressLike | null, newOwner?: AddressLike | null): EventFilter;
    RouterDeposit(payer?: AddressLike | null, beneficiary?: AddressLike | null, token?: AddressLike | null): EventFilter;
    RouterWithdrawal(principal?: AddressLike | null, recipient?: AddressLike | null, token?: AddressLike | null): EventFilter;
    TokenAllowlistUpdated(token?: AddressLike | null): EventFilter;
  };
}

export function connectDiesisSettlementRouter(address: string, runner: ContractRunner): DiesisSettlementRouterContract {
  const contract = new Contract(address, DiesisSettlementRouterAbi, runner);
  return contract as unknown as DiesisSettlementRouterContract;
}
