// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter, type Overrides } from 'ethers';
import { DiesisPublicResolverAbi } from '../../generated/viem/DiesisPublicResolver.abi.js';

export interface DiesisPublicResolverContract {
  DIESIS_EVM_COIN_TYPE(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  MAX_AGENT_RECORD_BYTES(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  MAX_CONTENTHASH_BYTES(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  MAX_MULTICOIN_ADDR_BYTES(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  MAX_RESOLVER_CALLS(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  MAX_ROUTE_TARGET_BYTES(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  MAX_TEXT_KEY_BYTES(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  MAX_TEXT_VALUE_BYTES(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  ROUTE_KIND_PAYMENT(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  addrBytes32(node: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  addrBytes32Uint256(node: BytesLike, coinType: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  agentRecord(node: BytesLike, agentId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[string, string, string, string, string, bigint, bigint, boolean] & { agentId: string; endpoint: string; publicKey: string; capabilitiesHash: string; policyHash: string; validFrom: bigint; validUntil: bigint; enabled: boolean }>;
  contenthash(node: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  contractRecord(node: BytesLike, role: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  owner(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  paymentRoute(node: BytesLike, routeId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, string, string, bigint, bigint, string, boolean] & { chainId: bigint; token: string; recipient: string; priority: bigint; feeBpsLimit: bigint; memoPolicy: string; enabled: boolean }>;
  registry(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  renounceOwnership(overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  routeRecord(node: BytesLike, routeId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[string, bigint, string, string, string, boolean, boolean] & { routeId: string; routeKind: bigint; target: string; contractTarget: string; policyHash: string; wildcard: boolean; enabled: boolean }>;
  setAddrBytes32Uint256Bytes(node: BytesLike, coinType: BigNumberish, value: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setAddrBytes32Address(node: BytesLike, value: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setAgentRecord(node: BytesLike, agentId: BytesLike, record: { agentId: BytesLike; endpoint: string; publicKey: BytesLike; capabilitiesHash: BytesLike; policyHash: BytesLike; validFrom: BigNumberish; validUntil: BigNumberish; enabled: boolean }, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setContenthash(node: BytesLike, value: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setContractRecord(node: BytesLike, role: BytesLike, target: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setPaymentRoute(node: BytesLike, routeId: BytesLike, route: { chainId: BigNumberish; token: AddressLike; recipient: AddressLike; priority: BigNumberish; feeBpsLimit: BigNumberish; memoPolicy: BytesLike; enabled: boolean }, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setRecords(node: BytesLike, calls: BytesLike[], overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setRouteRecord(node: BytesLike, record: { routeId: BytesLike; routeKind: BigNumberish; target: BytesLike; contractTarget: AddressLike; policyHash: BytesLike; wildcard: boolean; enabled: boolean }, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setText(node: BytesLike, key: string, value: string, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setTrustedWriter(writer: AddressLike, approved: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setWildcardPaymentRoutingAllowed(node: BytesLike, approved: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  text(node: BytesLike, key: string, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  transferOwnership(newOwner: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  trustedWriters(writer: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  wildcardPaymentRoutingAllowed(node: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  filters: {
    AddrChanged(node?: BytesLike | null, addrValue?: AddressLike | null): EventFilter;
    AddressChanged(node?: BytesLike | null, coinType?: BigNumberish | null): EventFilter;
    AgentRecordChanged(node?: BytesLike | null, agentId?: BytesLike | null): EventFilter;
    ContenthashChanged(node?: BytesLike | null): EventFilter;
    ContractRecordChanged(node?: BytesLike | null, role?: BytesLike | null, target?: AddressLike | null): EventFilter;
    MulticoinAddrChanged(node?: BytesLike | null, coinType?: BigNumberish | null): EventFilter;
    OwnershipTransferred(previousOwner?: AddressLike | null, newOwner?: AddressLike | null): EventFilter;
    PaymentRouteChanged(node?: BytesLike | null, routeId?: BytesLike | null, recipient?: AddressLike | null): EventFilter;
    RouteRecordChanged(node?: BytesLike | null, routeId?: BytesLike | null): EventFilter;
    TextChanged(node?: BytesLike | null, key?: string | null): EventFilter;
    TrustedWriterChanged(writer?: AddressLike | null): EventFilter;
    WildcardPaymentRoutingChanged(node?: BytesLike | null): EventFilter;
  };
}

export function connectDiesisPublicResolver(address: string, runner: ContractRunner): DiesisPublicResolverContract {
  const contract = new Contract(address, DiesisPublicResolverAbi, runner);
  Object.assign(contract, {
    addrBytes32: contract.getFunction("addr(bytes32)"),
    addrBytes32Uint256: contract.getFunction("addr(bytes32,uint256)"),
    setAddrBytes32Uint256Bytes: contract.getFunction("setAddr(bytes32,uint256,bytes)"),
    setAddrBytes32Address: contract.getFunction("setAddr(bytes32,address)"),
  });
  return contract as unknown as DiesisPublicResolverContract;
}
