// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { DiesisPrivacyPoolsAbi } from '../../generated/viem/DiesisPrivacyPools.abi.js';

export interface DiesisPrivacyPoolsContract {
  acceptOwnership(): Promise<ContractTransactionResponse>;
  artifactClass(): Promise<string>;
  associationVerifier(): Promise<string>;
  initialized(): Promise<boolean>;
  owner(): Promise<string>;
  pendingOwner(): Promise<string>;
  providerCount(): Promise<bigint>;
  providerList(arg0: BigNumberish): Promise<string>;
  providers(arg0: AddressLike): Promise<[string, boolean, string] & { name: string; registered: boolean; associationSetRoot: string }>;
  registerProvider(provider: AddressLike, name: string): Promise<ContractTransactionResponse>;
  transferOwnership(newOwner: AddressLike): Promise<ContractTransactionResponse>;
  updateAssociationSet(newRoot: BytesLike): Promise<ContractTransactionResponse>;
  verifyAssociation(proof: BytesLike, associationSetRoot: BytesLike, nullifier: BytesLike, provider: AddressLike): Promise<boolean>;
  filters: {
    AssociationSetUpdated(provider?: AddressLike | null): EventFilter;
    OwnershipTransferStarted(currentOwner?: AddressLike | null, pendingOwner?: AddressLike | null): EventFilter;
    OwnershipTransferred(previousOwner?: AddressLike | null, newOwner?: AddressLike | null): EventFilter;
    ProviderRegistered(provider?: AddressLike | null): EventFilter;
  };
}

export function connectDiesisPrivacyPools(address: string, runner: ContractRunner): DiesisPrivacyPoolsContract {
  const contract = new Contract(address, DiesisPrivacyPoolsAbi, runner);
  return contract as unknown as DiesisPrivacyPoolsContract;
}
