// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter, type Overrides } from 'ethers';
import { DiesisPatronAbi } from '../../generated/viem/DiesisPatron.abi.js';

export interface DiesisPatronContract {
  accrueSettledBurnV2(blockNumber: BigNumberish, totalActualFee: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  accruedBurn(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  assignAccountGrant(account: AddressLike, grantId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  campaignIdFor(owner: AddressLike, salt: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  campaignOwner(campaignId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  campaignRevoked(campaignId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  campaignVoucherDigest(voucher: { campaignId: BytesLike; beneficiary: AddressLike; target: AddressLike; selector: BytesLike; maxTransactions: BigNumberish; maxLifetimeSpend: BigNumberish; expiry: BigNumberish; nonce: BigNumberish }, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  campaignVoucherUsed(campaignId: BytesLike, beneficiary: AddressLike, nonce: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  cancelGrantV2(reservationId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  claimCampaignVoucherV1(voucher: { campaignId: BytesLike; beneficiary: AddressLike; target: AddressLike; selector: BytesLike; maxTransactions: BigNumberish; maxLifetimeSpend: BigNumberish; expiry: BigNumberish; nonce: BigNumberish }, signature: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  contribute(grantId: BytesLike, overrides?: Overrides): Promise<ContractTransactionResponse>;
  flushBurn(overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  grantAuthorizations(arg0: AddressLike, arg1: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[string, string, bigint, bigint, bigint, bigint, bigint] & { target: string; selector: string; expiry: bigint; maxTransactions: bigint; transactionsUsed: bigint; maxLifetimeSpend: bigint; lifetimeSpent: bigint }>;
  grantGasOverhead(overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint] & { reserveGas: bigint; settleGas: bigint; totalOverhead: bigint }>;
  grantIdForAccount(account: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  grantIdForCampaign(campaignId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  grantIdForReferral(referrer: AddressLike, referred: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  grantIdForWelcome(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  grantInfo(grantId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint] & { balance: bigint; totalContributed: bigint; totalSpent: bigint }>;
  grants(arg0: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint] & { balance: bigint; totalContributed: bigint; totalSpent: bigint }>;
  lastAccruedBlock(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  maxActiveReservationsPerGrant(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  outstandingReservationExitClaims(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  owner(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  paused(overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  pendingReservations(reservationId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[string, string, bigint] & { grantId: string; beneficiary: string; maximumFee: bigint }>;
  registerCampaignV1(salt: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  renounceOwnership(overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  reservationExitSettlement(reservationId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[string, bigint, bigint, bigint, bigint] & { grantId: string; totalRefund: bigint; totalDetachedShares: bigint; remainingDetachedShares: bigint; remainingEscrow: bigint }>;
  reservationExitSnapshot(reservationId: BytesLike, contributor: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, boolean, boolean] & { detachedShares: bigint; claimed: boolean; snapshotted: boolean }>;
  reserveGrantGasLimit(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  reserveGrantV2(reservationId: BytesLike, sender: AddressLike, target: AddressLike, input: BytesLike, maximumFee: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  resolveGrant(sender: AddressLike, target: AddressLike, input: BytesLike, fee: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  resolveGrantContext(sender: AddressLike, target: AddressLike, input: BytesLike, fee: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<[string, bigint, bigint, bigint, bigint, bigint] & { grantId: string; jarBalance: bigint; maxTransactions: bigint; transactionsUsed: bigint; maxLifetimeSpend: bigint; lifetimeSpent: bigint }>;
  revokeCampaignVoucherV1(campaignId: BytesLike, beneficiary: AddressLike, nonce: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  revokeGrantAuthorization(beneficiary: AddressLike, grantId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  rotateCampaignOwnerV1(campaignId: BytesLike, newOwner: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setCampaignRevokedV1(campaignId: BytesLike, revoked: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setGrantAuthorization(beneficiary: AddressLike, grantId: BytesLike, target: AddressLike, selector: BytesLike, maxTransactions: BigNumberish, maxLifetimeSpend: BigNumberish, expiry: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setPaused(paused_: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setReferral(referred: AddressLike, referrer: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  settleGrantGasLimit(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  settleGrantV2(reservationId: BytesLike, actualFee: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  stakingAddress(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  transferOwnership(newOwner: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  updateGasLimits(reserveGas: BigNumberish, settleGas: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  updateStakingAddress(staking_: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  withdrawContribution(grantId: BytesLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  withdrawReservationExit(reservationId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    AccountGrantAssigned(account?: AddressLike | null, grantId?: BytesLike | null): EventFilter;
    BurnFlushFailed(staking?: AddressLike | null): EventFilter;
    BurnFlushed(staking?: AddressLike | null): EventFilter;
    CampaignOwnerRotated(campaignId?: BytesLike | null, previousOwner?: AddressLike | null, newOwner?: AddressLike | null): EventFilter;
    CampaignRegistered(campaignId?: BytesLike | null, owner?: AddressLike | null): EventFilter;
    CampaignRevocationSet(campaignId?: BytesLike | null): EventFilter;
    CampaignVoucherClaimed(campaignId?: BytesLike | null, beneficiary?: AddressLike | null): EventFilter;
    CampaignVoucherRevoked(campaignId?: BytesLike | null, beneficiary?: AddressLike | null): EventFilter;
    GrantAuthorizationRevoked(beneficiary?: AddressLike | null, grantId?: BytesLike | null): EventFilter;
    GrantAuthorizationSet(beneficiary?: AddressLike | null, grantId?: BytesLike | null, target?: AddressLike | null): EventFilter;
    GrantContributed(grantId?: BytesLike | null, contributor?: AddressLike | null): EventFilter;
    GrantGasLimitsUpdated(): EventFilter;
    GrantReservationCancelled(reservationId?: BytesLike | null, grantId?: BytesLike | null): EventFilter;
    GrantReserved(reservationId?: BytesLike | null, grantId?: BytesLike | null, beneficiary?: AddressLike | null): EventFilter;
    GrantSettled(reservationId?: BytesLike | null, grantId?: BytesLike | null): EventFilter;
    GrantWithdrawn(grantId?: BytesLike | null, contributor?: AddressLike | null): EventFilter;
    OwnershipTransferred(previousOwner?: AddressLike | null, newOwner?: AddressLike | null): EventFilter;
    Paused(): EventFilter;
    ReferralGrantSet(referrer?: AddressLike | null, referred?: AddressLike | null): EventFilter;
    ReservationExitSnapshotted(reservationId?: BytesLike | null, grantId?: BytesLike | null, contributor?: AddressLike | null): EventFilter;
    ReservationExitWithdrawn(reservationId?: BytesLike | null, grantId?: BytesLike | null, contributor?: AddressLike | null): EventFilter;
    SettledBurnAccrued(blockNumber?: BigNumberish | null): EventFilter;
    StakingAddressUpdated(newAddress?: AddressLike | null): EventFilter;
  };
}

export function connectDiesisPatron(address: string, runner: ContractRunner): DiesisPatronContract {
  const contract = new Contract(address, DiesisPatronAbi, runner);
  return contract as unknown as DiesisPatronContract;
}
