// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { DiesisShieldedPoolAbi } from '../../generated/viem/DiesisShieldedPool.abi.js';

export interface DiesisShieldedPoolContract {
  DENOMINATION(): Promise<bigint>;
  DEPTH(): Promise<bigint>;
  ENCRYPTED_NOTE_BYTES(): Promise<bigint>;
  MAX_LEAVES(): Promise<bigint>;
  ROOT_HISTORY_SIZE(): Promise<bigint>;
  artifactClass(): Promise<string>;
  commitmentSeen(arg0: BytesLike): Promise<boolean>;
  currentRootIndex(): Promise<bigint>;
  deposit(commitment: BytesLike, encryptedNote: BytesLike): Promise<ContractTransactionResponse>;
  filledSubtrees(arg0: BigNumberish): Promise<string>;
  initialized(): Promise<boolean>;
  isKnownRoot(rootValue: BytesLike): Promise<boolean>;
  nextIndex(): Promise<bigint>;
  nullifiers(arg0: BytesLike): Promise<boolean>;
  outstandingNotes(): Promise<bigint>;
  root(): Promise<string>;
  rootHistory(arg0: BigNumberish): Promise<string>;
  rootReferenceCount(arg0: BytesLike): Promise<bigint>;
  transact(proof: BytesLike, merkleRoot: BytesLike, inputNullifiers: [BytesLike, BytesLike], outputCommitments: [BytesLike, BytesLike], activeCount: BigNumberish, encryptedOutputs: BytesLike): Promise<ContractTransactionResponse>;
  transferVerifier(): Promise<string>;
  treeInitialized(): Promise<boolean>;
  withdraw(proof: BytesLike, merkleRoot: BytesLike, nullifier: BytesLike, recipient: AddressLike, relayer: AddressLike, fee: BigNumberish): Promise<ContractTransactionResponse>;
  withdrawVerifier(): Promise<string>;
  zeros(arg0: BigNumberish): Promise<string>;
  filters: {
    DepositV1(commitment?: BytesLike | null, leafIndex?: BigNumberish | null): EventFilter;
    TransferV1(): EventFilter;
    WithdrawalV1(nullifier?: BytesLike | null, recipient?: AddressLike | null, relayer?: AddressLike | null): EventFilter;
  };
}

export function connectDiesisShieldedPool(address: string, runner: ContractRunner): DiesisShieldedPoolContract {
  const contract = new Contract(address, DiesisShieldedPoolAbi, runner);
  return contract as unknown as DiesisShieldedPoolContract;
}
