// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter, type Overrides } from 'ethers';
import { DiesisShieldedPoolAbi } from '../../generated/viem/DiesisShieldedPool.abi.js';

export interface DiesisShieldedPoolContract {
  DENOMINATION(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  DEPTH(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  ENCRYPTED_NOTE_BYTES(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  MAX_LEAVES(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  ROOT_HISTORY_SIZE(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  artifactClass(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  commitmentSeen(arg0: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  currentRootIndex(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  deposit(commitment: BytesLike, encryptedNote: BytesLike, overrides?: Overrides): Promise<ContractTransactionResponse>;
  filledSubtrees(arg0: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  initialized(overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  isKnownRoot(rootValue: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  nextIndex(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  nullifiers(arg0: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  outstandingNotes(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  root(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  rootHistory(arg0: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  rootReferenceCount(arg0: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  transact(proof: BytesLike, merkleRoot: BytesLike, inputNullifiers: [BytesLike, BytesLike], outputCommitments: [BytesLike, BytesLike], activeCount: BigNumberish, encryptedOutputs: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  transferVerifier(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  treeInitialized(overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  withdraw(proof: BytesLike, merkleRoot: BytesLike, nullifier: BytesLike, recipient: AddressLike, relayer: AddressLike, fee: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  withdrawVerifier(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  zeros(arg0: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  filters: {
    DepositV1(commitment?: BytesLike | null, leafIndex?: BigNumberish | null): EventFilter;
    TransferV1(): EventFilter;
    WithdrawalV1(nullifier?: BytesLike | null, recipient?: AddressLike | null, relayer?: AddressLike | null): EventFilter;
  };
}

export function connectDiesisShieldedPool(address: string, runner: ContractRunner): DiesisShieldedPoolContract {
  const contract = new Contract(address, DiesisShieldedPoolAbi, runner);
  return contract as unknown as DiesisShieldedPoolContract;
}
