// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { IDiesisMarketsAbi } from '../../generated/viem/IDiesisMarkets.abi.js';

export interface IDiesisMarketsContract {
  checkCircuitBreaker(marketId: BytesLike, currentPrice: BigNumberish, referencePrice: BigNumberish, thresholdBps: BigNumberish): Promise<ContractTransactionResponse>;
  createSpotMarket(baseToken: AddressLike, quoteToken: AddressLike, tickSize: BigNumberish, lotSize: BigNumberish, bond: BigNumberish): Promise<ContractTransactionResponse>;
  deployTokenAndSpotBook(symbol: BytesLike, name: string, initialSupply: BigNumberish, dsBond: BigNumberish, usdcFee: BigNumberish): Promise<ContractTransactionResponse>;
  getMarket(marketId: BytesLike): Promise<[string, string, bigint] & { slot0: string; slot1: string; maxOpenInterest: bigint }>;
  resumeMarket(marketId: BytesLike): Promise<ContractTransactionResponse>;
  filters: {
    CircuitBreakerTriggered(marketId?: BytesLike | null): EventFilter;
    MarketCreated(marketId?: BytesLike | null): EventFilter;
  };
}

export function connectIDiesisMarkets(address: string, runner: ContractRunner): IDiesisMarketsContract {
  const contract = new Contract(address, IDiesisMarketsAbi, runner);
  return contract as unknown as IDiesisMarketsContract;
}
