// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { IDiesisNameRegistryAbi } from '../../generated/viem/IDiesisNameRegistry.abi.js';

export interface IDiesisNameRegistryContract {
  controllers(controller: AddressLike): Promise<boolean>;
  expiry(node: BytesLike): Promise<bigint>;
  isApprovedForAll(owner_: AddressLike, operator: AddressLike): Promise<boolean>;
  isAuthorized(node: BytesLike, actor: AddressLike): Promise<boolean>;
  isExpired(node: BytesLike): Promise<boolean>;
  namePolicy(): Promise<string>;
  owner(node: BytesLike): Promise<string>;
  ownershipEpoch(node: BytesLike): Promise<bigint>;
  resolver(node: BytesLike): Promise<string>;
  setApprovalForAll(operator: AddressLike, approved: boolean): Promise<ContractTransactionResponse>;
  setController(controller: AddressLike, approved: boolean): Promise<ContractTransactionResponse>;
  setExpiry(node: BytesLike, expiry_: BigNumberish): Promise<ContractTransactionResponse>;
  setNamePolicy(policy: AddressLike): Promise<ContractTransactionResponse>;
  setOwner(node: BytesLike, owner_: AddressLike): Promise<ContractTransactionResponse>;
  setResolver(node: BytesLike, resolver_: AddressLike): Promise<ContractTransactionResponse>;
  setSubnodeOwner(node: BytesLike, label: BytesLike, owner_: AddressLike): Promise<ContractTransactionResponse>;
  setSubnodeRecord(node: BytesLike, label: BytesLike, owner_: AddressLike, resolver_: AddressLike, ttl_: BigNumberish, expiry_: BigNumberish): Promise<ContractTransactionResponse>;
  setTTL(node: BytesLike, ttl_: BigNumberish): Promise<ContractTransactionResponse>;
  ttl(node: BytesLike): Promise<bigint>;
  filters: {
    ApprovalForAll(owner?: AddressLike | null, operator?: AddressLike | null): EventFilter;
    ControllerChanged(controller?: AddressLike | null): EventFilter;
    ExpiryChanged(node?: BytesLike | null): EventFilter;
    NamePolicyChanged(policy?: AddressLike | null): EventFilter;
    OwnerChanged(node?: BytesLike | null, owner?: AddressLike | null): EventFilter;
    ResolverChanged(node?: BytesLike | null, resolver?: AddressLike | null): EventFilter;
    TTLChanged(node?: BytesLike | null): EventFilter;
  };
}

export function connectIDiesisNameRegistry(address: string, runner: ContractRunner): IDiesisNameRegistryContract {
  const contract = new Contract(address, IDiesisNameRegistryAbi, runner);
  return contract as unknown as IDiesisNameRegistryContract;
}
