// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisPerpsBookAbi } from '../../generated/viem/IDiesisPerpsBook.abi.js';

export interface IDiesisPerpsBookMethods {
  adjustIsolatedMargin(marketId: BytesLike, marginDelta: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  advancePricedPerpRuntime(policyHash: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  amendPerpOrder(orderId: BytesLike, price: BigNumberish, amount: BigNumberish, expiry: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  applyPerpFunding(marketId: BytesLike, fundingRateBps: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  cancelPerpOrder(orderId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  executePerpTrade(makerOrderId: BytesLike, takerOrderId: BytesLike, fillPrice: BigNumberish, fillQty: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  expirePerpOrder(orderId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  finalizePerpFeeEpoch(marketId: BytesLike, epoch: BigNumberish, snapshotHash: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  getIsolatedMargin(trader: AddressLike, marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  getPosition(trader: AddressLike, marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[string, bigint, bigint] & { header: string; size: bigint; entryPrice: bigint }>;
  submitBoundSessionActions(encodedWrapper: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  submitExchangeActions(encodedActions: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  submitPerpOrder(marketId: BytesLike, side: BigNumberish, orderType: BigNumberish, price: BigNumberish, amount: BigNumberish, flags: BigNumberish, marginType: BigNumberish, expiry: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  submitSponsoredPerpActions(signedEnvelope: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  updatePerpMark(marketId: BytesLike, markPrice: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  updatePerpOracle(marketId: BytesLike, indexPrice: BigNumberish, markPrice: BigNumberish, observedAt: BigNumberish, oracleRound: BigNumberish, sourceSetHash: BytesLike, evidenceHash: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  updatePricedOracle(payload: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    ExchangeActionAccepted(clientActionId?: BytesLike | null, actionIndex?: BigNumberish | null, actionTag?: null, marketId?: BytesLike | null): DeferredTopicFilter;
    ExchangeActionRejected(clientActionId?: BytesLike | null, actionIndex?: BigNumberish | null, actionTag?: null, marketId?: BytesLike | null): DeferredTopicFilter;
    ExchangeL3Mutation(marketId?: BytesLike | null, orderId?: BytesLike | null, trader?: AddressLike | null): DeferredTopicFilter;
    FundingApplied(marketId?: BytesLike | null): DeferredTopicFilter;
    IsolatedMarginAdjusted(marketId?: BytesLike | null, trader?: AddressLike | null): DeferredTopicFilter;
    MarkPriceUpdated(marketId?: BytesLike | null): DeferredTopicFilter;
    OrderCancelled(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: AddressLike | null): DeferredTopicFilter;
    OrderFilled(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: AddressLike | null): DeferredTopicFilter;
    OrderPlaced(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: AddressLike | null): DeferredTopicFilter;
    PositionClosed(marketId?: BytesLike | null, trader?: AddressLike | null): DeferredTopicFilter;
    PositionCollateralAdjusted(marketId?: BytesLike | null, trader?: AddressLike | null): DeferredTopicFilter;
  };
}

export type IDiesisPerpsBookContract = Omit<BaseContract, keyof IDiesisPerpsBookMethods | 'connect'> &
  IDiesisPerpsBookMethods & {
    connect(runner: ContractRunner | null): IDiesisPerpsBookContract;
  };

export function connectIDiesisPerpsBook(address: string, runner: ContractRunner): IDiesisPerpsBookContract {
  const contract = new Contract(address, IDiesisPerpsBookAbi, runner);
  return contract as unknown as IDiesisPerpsBookContract;
}
