// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisReverseRegistrarAbi } from '../../generated/viem/IDiesisReverseRegistrar.abi.js';

export interface IDiesisReverseRegistrarMethods {
  controllers(controller: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  name(addr: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  node(addr: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  setController(controller: AddressLike, approved: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setName(name_: string, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setNameForAddr(addr: AddressLike, name_: string, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    ControllerChanged(controller?: AddressLike | null): DeferredTopicFilter;
    ReverseNameChanged(addr?: AddressLike | null): DeferredTopicFilter;
  };
}

export type IDiesisReverseRegistrarContract = Omit<BaseContract, keyof IDiesisReverseRegistrarMethods | 'connect'> &
  IDiesisReverseRegistrarMethods & {
    connect(runner: ContractRunner | null): IDiesisReverseRegistrarContract;
  };

export function connectIDiesisReverseRegistrar(address: string, runner: ContractRunner): IDiesisReverseRegistrarContract {
  const contract = new Contract(address, IDiesisReverseRegistrarAbi, runner);
  return contract as unknown as IDiesisReverseRegistrarContract;
}
