// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter, type Overrides } from 'ethers';
import { IDiesisBuybackBurnAbi } from '../../generated/viem/IDiesisBuybackBurn.abi.js';

export interface IDiesisBuybackBurnContract {
  cumulativeBurnedDs(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  lastTwapAveragePrice(token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  nextWindowStartBlock(token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  pendingPurchaseByAsset(token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  windowState(token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & { windowStartBlock: bigint; windowEndBlock: bigint; windowLengthBlocks: bigint; chunksTotal: bigint; chunksRemaining: bigint; initialPending: bigint; twapAveragePrice: bigint }>;
  filters: {
    AssetApproved(token?: AddressLike | null): EventFilter;
    BurnChunk(token?: AddressLike | null): EventFilter;
    DsBurned(): EventFilter;
  };
}

export function connectIDiesisBuybackBurn(address: string, runner: ContractRunner): IDiesisBuybackBurnContract {
  const contract = new Contract(address, IDiesisBuybackBurnAbi, runner);
  return contract as unknown as IDiesisBuybackBurnContract;
}
