// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { IDiesisCoreVaultAbi } from '../../generated/viem/IDiesisCoreVault.abi.js';

export interface IDiesisCoreVaultContract {
  cancelExit(id: BigNumberish, queueIndex: BigNumberish): Promise<ContractTransactionResponse>;
  deposit(id: BigNumberish, amount: BigNumberish): Promise<ContractTransactionResponse>;
  executeRiskParamChange(id: BigNumberish): Promise<ContractTransactionResponse>;
  exitQueue(id: BigNumberish): Promise<([string, bigint, bigint, bigint, bigint] & { depositor: string; sharesBurned: bigint; requestedBlock: bigint; pricedNavBlock: bigint; pricedSharePriceQ96: bigint })[]>;
  getCheckpoint(id: BigNumberish, blockNumber: BigNumberish): Promise<[bigint, bigint, bigint, bigint] & { blockNumber: bigint; totalAssets: bigint; totalShares: bigint; sharePriceQ96: bigint }>;
  getRiskParams(id: BigNumberish): Promise<[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & { maxNotionalPerMarket: bigint; maxLeverage: bigint; maxSingleFillSlippageBps: bigint; adlCallRatioBps: bigint; insuranceCallCapBpsOfTvl: bigint; maxPositionConcentrationBps: bigint; liquidationEngineMode: bigint }>;
  pauseState(id: BigNumberish): Promise<[boolean, bigint, bigint] & { paused: boolean; lastPauseBlock: bigint; expiresAtBlock: bigint }>;
  pauseStrategy(id: BigNumberish): Promise<ContractTransactionResponse>;
  proposeRiskParamChange(id: BigNumberish, newParams: { maxNotionalPerMarket: BigNumberish; maxLeverage: BigNumberish; maxSingleFillSlippageBps: BigNumberish; adlCallRatioBps: BigNumberish; insuranceCallCapBpsOfTvl: BigNumberish; maxPositionConcentrationBps: BigNumberish; liquidationEngineMode: BigNumberish }): Promise<ContractTransactionResponse>;
  requestExit(id: BigNumberish, shares: BigNumberish): Promise<ContractTransactionResponse>;
  shareBalance(id: BigNumberish, depositor: AddressLike): Promise<bigint>;
  totalAssets(id: BigNumberish): Promise<bigint>;
  totalShares(id: BigNumberish): Promise<bigint>;
  filters: {
    Deposited(id?: BigNumberish | null, depositor?: AddressLike | null): EventFilter;
    ExitCancelled(id?: BigNumberish | null, depositor?: AddressLike | null): EventFilter;
    ExitProcessed(id?: BigNumberish | null, depositor?: AddressLike | null): EventFilter;
    ExitRequested(id?: BigNumberish | null, depositor?: AddressLike | null): EventFilter;
    RiskParamChangeExecuted(id?: BigNumberish | null): EventFilter;
    RiskParamChangeProposed(id?: BigNumberish | null): EventFilter;
    StrategyPaused(id?: BigNumberish | null): EventFilter;
  };
}

export function connectIDiesisCoreVault(address: string, runner: ContractRunner): IDiesisCoreVaultContract {
  const contract = new Contract(address, IDiesisCoreVaultAbi, runner);
  return contract as unknown as IDiesisCoreVaultContract;
}
