// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisCoreVaultAbi } from '../../generated/viem/IDiesisCoreVault.abi.js';

export interface IDiesisCoreVaultMethods {
  cancelExit(id: BigNumberish, queueIndex: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  deposit(id: BigNumberish, amount: BigNumberish, overrides?: Overrides): Promise<ContractTransactionResponse>;
  executeRiskParamChange(id: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  exitQueue(id: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<([string, bigint, bigint, bigint, bigint] & { depositor: string; sharesBurned: bigint; requestedBlock: bigint; pricedNavBlock: bigint; pricedSharePriceQ96: bigint })[]>;
  getCheckpoint(id: BigNumberish, blockNumber: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint, bigint] & { blockNumber: bigint; totalAssets: bigint; totalShares: bigint; sharePriceQ96: bigint }>;
  getRiskParams(id: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & { maxNotionalPerMarket: bigint; maxLeverage: bigint; maxSingleFillSlippageBps: bigint; adlCallRatioBps: bigint; insuranceCallCapBpsOfTvl: bigint; maxPositionConcentrationBps: bigint; liquidationEngineMode: bigint }>;
  pauseState(id: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<[boolean, bigint, bigint] & { paused: boolean; lastPauseBlock: bigint; expiresAtBlock: bigint }>;
  pauseStrategy(id: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  proposeRiskParamChange(id: BigNumberish, newParams: { maxNotionalPerMarket: BigNumberish; maxLeverage: BigNumberish; maxSingleFillSlippageBps: BigNumberish; adlCallRatioBps: BigNumberish; insuranceCallCapBpsOfTvl: BigNumberish; maxPositionConcentrationBps: BigNumberish; liquidationEngineMode: BigNumberish }, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  requestExit(id: BigNumberish, shares: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  shareBalance(id: BigNumberish, depositor: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  totalAssets(id: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  totalShares(id: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  filters: {
    Deposited(id?: BigNumberish | null, depositor?: AddressLike | null): DeferredTopicFilter;
    ExitCancelled(id?: BigNumberish | null, depositor?: AddressLike | null): DeferredTopicFilter;
    ExitProcessed(id?: BigNumberish | null, depositor?: AddressLike | null): DeferredTopicFilter;
    ExitRequested(id?: BigNumberish | null, depositor?: AddressLike | null): DeferredTopicFilter;
    RiskParamChangeExecuted(id?: BigNumberish | null): DeferredTopicFilter;
    RiskParamChangeProposed(id?: BigNumberish | null): DeferredTopicFilter;
    StrategyPaused(id?: BigNumberish | null): DeferredTopicFilter;
  };
}

export type IDiesisCoreVaultContract = Omit<BaseContract, keyof IDiesisCoreVaultMethods | 'connect'> &
  IDiesisCoreVaultMethods & {
    connect(runner: ContractRunner | null): IDiesisCoreVaultContract;
  };

export function connectIDiesisCoreVault(address: string, runner: ContractRunner): IDiesisCoreVaultContract {
  const contract = new Contract(address, IDiesisCoreVaultAbi, runner);
  return contract as unknown as IDiesisCoreVaultContract;
}
