// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisMarginAbi } from '../../generated/viem/IDiesisMargin.abi.js';

export interface IDiesisMarginMethods {
  resolvePerpProtectionV1(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    AutoDeleverage(marketId?: BytesLike | null, deleveraged?: AddressLike | null, counterparty?: AddressLike | null): DeferredTopicFilter;
    Liquidation(marketId?: BytesLike | null, trader?: AddressLike | null): DeferredTopicFilter;
  };
}

export type IDiesisMarginContract = Omit<BaseContract, keyof IDiesisMarginMethods | 'connect'> &
  IDiesisMarginMethods & {
    connect(runner: ContractRunner | null): IDiesisMarginContract;
  };

export function connectIDiesisMargin(address: string, runner: ContractRunner): IDiesisMarginContract {
  const contract = new Contract(address, IDiesisMarginAbi, runner);
  return contract as unknown as IDiesisMarginContract;
}
