// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisNamePolicyAbi } from '../../generated/viem/IDiesisNamePolicy.abi.js';

export interface IDiesisNamePolicyMethods {
  approveRecovery(node: BytesLike, newOwner: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  cancelRecovery(node: BytesLike, newOwner: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  finalizeRecovery(node: BytesLike, newOwner: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  guardedTransfer(node: BytesLike, newOwner: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  guardians(node: BytesLike, guardian: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  isTransferLocked(node: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  recoveryDelay(node: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  recoveryEnabled(node: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  recoveryFallbackOwner(node: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  recoveryThreshold(node: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  setGuardian(node: BytesLike, guardian: AddressLike, approved: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setRecoveryConfig(node: BytesLike, threshold: BigNumberish, delay: BigNumberish, fallbackOwner: AddressLike, enabled: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setTransferLock(node: BytesLike, lockedUntil: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  transferLockUntil(node: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  filters: {
    GuardianChanged(node?: BytesLike | null, guardian?: AddressLike | null): DeferredTopicFilter;
    NameRecovered(node?: BytesLike | null, requestId?: BytesLike | null, newOwner?: AddressLike | null): DeferredTopicFilter;
    RecoveryApproved(node?: BytesLike | null, requestId?: BytesLike | null, guardian?: AddressLike | null): DeferredTopicFilter;
    RecoveryCancelled(node?: BytesLike | null, requestId?: BytesLike | null): DeferredTopicFilter;
    RecoveryConfigChanged(node?: BytesLike | null): DeferredTopicFilter;
    TransferLockChanged(node?: BytesLike | null): DeferredTopicFilter;
  };
}

export type IDiesisNamePolicyContract = Omit<BaseContract, keyof IDiesisNamePolicyMethods | 'connect'> &
  IDiesisNamePolicyMethods & {
    connect(runner: ContractRunner | null): IDiesisNamePolicyContract;
  };

export function connectIDiesisNamePolicy(address: string, runner: ContractRunner): IDiesisNamePolicyContract {
  const contract = new Contract(address, IDiesisNamePolicyAbi, runner);
  return contract as unknown as IDiesisNamePolicyContract;
}
