// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { IDiesisNameVerifierAbi } from '../../generated/viem/IDiesisNameVerifier.abi.js';

export interface IDiesisNameVerifierContract {
  attest(node: BytesLike, subject: AddressLike, kind: BytesLike, digest: BytesLike, expiresAt: BigNumberish): Promise<ContractTransactionResponse>;
  attestationDigest(attestation: { node: BytesLike; attestationType: BytesLike; issuer: AddressLike; subjectHash: BytesLike; evidenceHash: BytesLike; issuedAt: BigNumberish; validUntil: BigNumberish; extraData: BytesLike }): Promise<string>;
  attestationHash(attestation: { node: BytesLike; attestationType: BytesLike; issuer: AddressLike; subjectHash: BytesLike; evidenceHash: BytesLike; issuedAt: BigNumberish; validUntil: BigNumberish; extraData: BytesLike }): Promise<string>;
  attestationsBytes32Bytes32(node: BytesLike, attestationType: BytesLike): Promise<string[]>;
  attestationsBytes32(attestationId: BytesLike): Promise<[string, string, string, string, string, bigint, bigint, boolean] & { node: string; subject: string; kind: string; digest: string; issuer: string; issuedAt: bigint; expiresAt: bigint; revoked: boolean }>;
  isAttested(node: BytesLike, attestationType: BytesLike, issuer: AddressLike): Promise<boolean>;
  isValid(attestationId: BytesLike): Promise<boolean>;
  issuers(issuer: AddressLike): Promise<boolean>;
  revoke(attestationId: BytesLike): Promise<ContractTransactionResponse>;
  revokeAttestation(node: BytesLike, attestationHash: BytesLike): Promise<ContractTransactionResponse>;
  setIssuer(issuer: AddressLike, approved: boolean): Promise<ContractTransactionResponse>;
  submitAttestation(attestation: { node: BytesLike; attestationType: BytesLike; issuer: AddressLike; subjectHash: BytesLike; evidenceHash: BytesLike; issuedAt: BigNumberish; validUntil: BigNumberish; extraData: BytesLike }, signature: BytesLike): Promise<ContractTransactionResponse>;
  filters: {
    AttestationRevoked(node?: BytesLike | null, attestationHash?: BytesLike | null, issuer?: AddressLike | null): EventFilter;
    AttestationSubmitted(node?: BytesLike | null, attestationType?: BytesLike | null, issuer?: AddressLike | null): EventFilter;
    Attested(attestationId?: BytesLike | null, node?: BytesLike | null, subject?: AddressLike | null): EventFilter;
    IssuerChanged(issuer?: AddressLike | null): EventFilter;
    Revoked(attestationId?: BytesLike | null): EventFilter;
  };
}

export function connectIDiesisNameVerifier(address: string, runner: ContractRunner): IDiesisNameVerifierContract {
  const contract = new Contract(address, IDiesisNameVerifierAbi, runner);
  Object.assign(contract, {
    attestationsBytes32Bytes32: contract.getFunction("attestations(bytes32,bytes32)"),
    attestationsBytes32: contract.getFunction("attestations(bytes32)"),
  });
  return contract as unknown as IDiesisNameVerifierContract;
}
