// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisBuybackBurnAbi } from '../../generated/viem/IDiesisBuybackBurn.abi.js';

export interface IDiesisBuybackBurnMethods {
  cumulativeBurnedDs(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  lastTwapAveragePrice(token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  nextWindowStartBlock(token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  pendingPurchaseByAsset(token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  windowState(token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & { windowStartBlock: bigint; windowEndBlock: bigint; windowLengthBlocks: bigint; chunksTotal: bigint; chunksRemaining: bigint; initialPending: bigint; twapAveragePrice: bigint }>;
  filters: {
    AssetApproved(token?: AddressLike | null): DeferredTopicFilter;
    BurnChunk(token?: AddressLike | null): DeferredTopicFilter;
    DsBurned(): DeferredTopicFilter;
  };
}

export type IDiesisBuybackBurnContract = Omit<BaseContract, keyof IDiesisBuybackBurnMethods | 'connect'> &
  IDiesisBuybackBurnMethods & {
    connect(runner: ContractRunner | null): IDiesisBuybackBurnContract;
  };

export function connectIDiesisBuybackBurn(address: string, runner: ContractRunner): IDiesisBuybackBurnContract {
  const contract = new Contract(address, IDiesisBuybackBurnAbi, runner);
  return contract as unknown as IDiesisBuybackBurnContract;
}
