// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { IDiesisErc20FactoryAbi } from '../../generated/viem/IDiesisErc20Factory.abi.js';

export interface IDiesisErc20FactoryContract {
  deploy(params: { symbol: BytesLike; name: string; initialSupply: BigNumberish; deployer: AddressLike }): Promise<ContractTransactionResponse>;
  executeTemplateUpdate(): Promise<ContractTransactionResponse>;
  predictAddress(deployer: AddressLike, symbol: BytesLike): Promise<string>;
  proposeTemplateUpdate(newHash: BytesLike): Promise<ContractTransactionResponse>;
  templateBytecodeHash(): Promise<string>;
  filters: {
    Erc20Deployed(token?: AddressLike | null, deployer?: AddressLike | null, symbol?: BytesLike | null): EventFilter;
    TemplateUpdated(): EventFilter;
  };
}

export function connectIDiesisErc20Factory(address: string, runner: ContractRunner): IDiesisErc20FactoryContract {
  const contract = new Contract(address, IDiesisErc20FactoryAbi, runner);
  return contract as unknown as IDiesisErc20FactoryContract;
}
