// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { IDiesisPerpDeployAbi } from '../../generated/viem/IDiesisPerpDeploy.abi.js';

export interface IDiesisPerpDeployContract {
  applyPerpAbandonmentV1(marketId: BytesLike, parentHash: BytesLike, blockNumber: BigNumberish, policyEpoch: BigNumberish, policyHash: BytesLike, windowStart: BigNumberish, windowEnd: BigNumberish, filledVolume: BigNumberish, operatorFees: BigNumberish, lastMetadataUpdate: BigNumberish, inputHash: BytesLike, committeeEpoch: BigNumberish, committeeIdentity: BytesLike, quorumPower: BigNumberish, attestingPower: BigNumberish, voterCount: BigNumberish, evidenceHash: BytesLike): Promise<ContractTransactionResponse>;
  applySlash(marketId: BytesLike, reason: BigNumberish): Promise<ContractTransactionResponse>;
  deployPerp(slotId: BytesLike, marketId: BytesLike, sourceList: BytesLike, metadata: BytesLike, signatures: BytesLike): Promise<ContractTransactionResponse>;
  expireNextUnactivatedPerpV1(): Promise<ContractTransactionResponse>;
  expireUnactivatedPerpV1(marketId: BytesLike): Promise<ContractTransactionResponse>;
  finalizeClose(marketId: BytesLike): Promise<ContractTransactionResponse>;
  finalizePerpPolicyV1(marketId: BytesLike, revision: BigNumberish, proposalId: BytesLike): Promise<ContractTransactionResponse>;
  getDeploymentState(marketId: BytesLike): Promise<[bigint, bigint, bigint, bigint] & { stateTag: bigint; deadlineOrLiveBlock: bigint; windowCloseBlock: bigint; slashReason: bigint }>;
  getMarketDeploymentState(marketId: BytesLike): Promise<[bigint, bigint, bigint, bigint] & { stateTag: bigint; deadlineOrLiveBlock: bigint; windowCloseBlock: bigint; slashReason: bigint }>;
  getOperatorBalance(operator: AddressLike): Promise<bigint>;
  getPerpPolicyV1(marketId: BytesLike): Promise<[[bigint, bigint, ([bigint, bigint, bigint] & { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint })[]] & { revision: bigint; backstopTopupBps: bigint; tiers: ([bigint, bigint, bigint] & { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint })[] }, [bigint, bigint, string[]] & { epoch: bigint; threshold: bigint; signers: string[] }] & { policy: [bigint, bigint, ([bigint, bigint, bigint] & { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint })[]] & { revision: bigint; backstopTopupBps: bigint; tiers: ([bigint, bigint, bigint] & { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint })[] }; keyset: [bigint, bigint, string[]] & { epoch: bigint; threshold: bigint; signers: string[] } }>;
  initializePerpMarketV1(baseToken: AddressLike, quoteToken: AddressLike, tickSize: BigNumberish, lotSize: BigNumberish, maxOpenInterest: BigNumberish, initialMark: BigNumberish, maxLeverage: BigNumberish): Promise<ContractTransactionResponse>;
  initializePerpMarketV2(baseToken: AddressLike, quoteToken: AddressLike, tickSize: BigNumberish, lotSize: BigNumberish, maxOpenInterest: BigNumberish, initialMark: BigNumberish, policy: { revision: BigNumberish; backstopTopupBps: BigNumberish; tiers: { maxNotional: BigNumberish; maxLeverage: BigNumberish; maintenanceMarginBps: BigNumberish }[] }, keyset: { epoch: BigNumberish; threshold: BigNumberish; signers: AddressLike[] }): Promise<ContractTransactionResponse>;
  initiateDelist(marketId: BytesLike): Promise<ContractTransactionResponse>;
  preparePerpMarketCloseV1(marketId: BytesLike, maxOrders: BigNumberish, maxPositions: BigNumberish): Promise<ContractTransactionResponse>;
  promoteToLive(marketId: BytesLike): Promise<ContractTransactionResponse>;
  proposePerpPolicyV1(marketId: BytesLike, expectedRevision: BigNumberish, expectedKeysetEpoch: BigNumberish, backstopTopupBps: BigNumberish, tiers: { maxNotional: BigNumberish; maxLeverage: BigNumberish; maintenanceMarginBps: BigNumberish }[], nextSigners: AddressLike[], nextThreshold: BigNumberish, signatures: { signer: AddressLike; r: BytesLike; s: BytesLike; v: BigNumberish }[]): Promise<ContractTransactionResponse>;
  recordAuctionWin(marketId: BytesLike, operator: AddressLike, registrationDigest: BytesLike, evidenceHash: BytesLike): Promise<ContractTransactionResponse>;
  filters: {
    Activated(marketId?: BytesLike | null): EventFilter;
    AuctionWinRecorded(marketId?: BytesLike | null, operator?: AddressLike | null): EventFilter;
    Closed(marketId?: BytesLike | null): EventFilter;
    Delisting(marketId?: BytesLike | null): EventFilter;
    LiveStarted(marketId?: BytesLike | null): EventFilter;
    PerpMarketClosePreparedV1(marketId?: BytesLike | null): EventFilter;
    PerpMarketInitializedV1(marketId?: BytesLike | null): EventFilter;
    PerpMarketInitializedV2(marketId?: BytesLike | null): EventFilter;
    Slashed(marketId?: BytesLike | null): EventFilter;
  };
}

export function connectIDiesisPerpDeploy(address: string, runner: ContractRunner): IDiesisPerpDeployContract {
  const contract = new Contract(address, IDiesisPerpDeployAbi, runner);
  return contract as unknown as IDiesisPerpDeployContract;
}
