// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { IDiesisPerpsBookAbi } from '../../generated/viem/IDiesisPerpsBook.abi.js';

export interface IDiesisPerpsBookContract {
  adjustIsolatedMargin(marketId: BytesLike, marginDelta: BigNumberish): Promise<ContractTransactionResponse>;
  amendPerpOrderV1(orderId: BytesLike, price: BigNumberish, amount: BigNumberish, expiry: BigNumberish): Promise<ContractTransactionResponse>;
  applyPerpFundingV1(marketId: BytesLike, fundingRateBps: BigNumberish): Promise<ContractTransactionResponse>;
  cancelPerpOrderV1(orderId: BytesLike): Promise<ContractTransactionResponse>;
  executePerpTradeV1(makerOrderId: BytesLike, takerOrderId: BytesLike, fillPrice: BigNumberish, fillQty: BigNumberish): Promise<ContractTransactionResponse>;
  expirePerpOrderV1(orderId: BytesLike): Promise<ContractTransactionResponse>;
  finalizePerpFeeEpochV2(marketId: BytesLike, epoch: BigNumberish, snapshotHash: BytesLike): Promise<ContractTransactionResponse>;
  getIsolatedMargin(trader: AddressLike, marketId: BytesLike): Promise<bigint>;
  getPosition(trader: AddressLike, marketId: BytesLike): Promise<[string, bigint, bigint] & { header: string; size: bigint; entryPrice: bigint }>;
  submitExchangeActionsV2(encodedActions: BytesLike): Promise<ContractTransactionResponse>;
  submitPerpOrderV1(marketId: BytesLike, side: BigNumberish, orderType: BigNumberish, price: BigNumberish, amount: BigNumberish, flags: BigNumberish, marginType: BigNumberish, expiry: BigNumberish): Promise<ContractTransactionResponse>;
  submitSignedPerpActionsV2(signedEnvelope: BytesLike): Promise<ContractTransactionResponse>;
  updatePerpMarkV1(marketId: BytesLike, markPrice: BigNumberish): Promise<ContractTransactionResponse>;
  updatePerpOracleV1(marketId: BytesLike, indexPrice: BigNumberish, markPrice: BigNumberish, observedAt: BigNumberish, oracleRound: BigNumberish, sourceSetHash: BytesLike, evidenceHash: BytesLike): Promise<ContractTransactionResponse>;
  filters: {
    ExchangeActionAcceptedV2(clientActionId?: BytesLike | null, actionIndex?: BigNumberish | null, actionTag?: null, marketId?: BytesLike | null): EventFilter;
    ExchangeActionRejectedV2(clientActionId?: BytesLike | null, actionIndex?: BigNumberish | null, actionTag?: null, marketId?: BytesLike | null): EventFilter;
    ExchangeL3MutationV2(marketId?: BytesLike | null, orderId?: BytesLike | null, trader?: AddressLike | null): EventFilter;
    FundingApplied(marketId?: BytesLike | null): EventFilter;
    IsolatedMarginAdjusted(marketId?: BytesLike | null, trader?: AddressLike | null): EventFilter;
    MarkPriceUpdated(marketId?: BytesLike | null): EventFilter;
    OrderCancelled(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: AddressLike | null): EventFilter;
    OrderFilled(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: AddressLike | null): EventFilter;
    OrderPlaced(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: AddressLike | null): EventFilter;
    PositionClosed(marketId?: BytesLike | null, trader?: AddressLike | null): EventFilter;
  };
}

export function connectIDiesisPerpsBook(address: string, runner: ContractRunner): IDiesisPerpsBookContract {
  const contract = new Contract(address, IDiesisPerpsBookAbi, runner);
  return contract as unknown as IDiesisPerpsBookContract;
}
