// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisMarketsAbi } from '../../generated/viem/IDiesisMarkets.abi.js';

export interface IDiesisMarketsMethods {
  checkCircuitBreaker(marketId: BytesLike, currentPrice: BigNumberish, referencePrice: BigNumberish, thresholdBps: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  createPricedSpotMarket(baseToken: AddressLike, quoteToken: AddressLike, tickSize: BigNumberish, lotSize: BigNumberish, priceDenominator: BigNumberish, bond: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  createSpotMarket(baseToken: AddressLike, quoteToken: AddressLike, tickSize: BigNumberish, lotSize: BigNumberish, bond: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  deployTokenAndSpotBook(symbol: BytesLike, name: string, initialSupply: BigNumberish, dsBond: BigNumberish, usdcFee: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  getMarket(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[string, string, bigint] & { slot0: string; slot1: string; maxOpenInterest: bigint }>;
  getMarketPricing(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint] & { pricingVersion: bigint; priceDenominator: bigint }>;
  resumeMarket(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    CircuitBreakerTriggered(marketId?: BytesLike | null): DeferredTopicFilter;
    MarketCreated(marketId?: BytesLike | null): DeferredTopicFilter;
  };
}

export type IDiesisMarketsContract = Omit<BaseContract, keyof IDiesisMarketsMethods | 'connect'> &
  IDiesisMarketsMethods & {
    connect(runner: ContractRunner | null): IDiesisMarketsContract;
  };

export function connectIDiesisMarkets(address: string, runner: ContractRunner): IDiesisMarketsContract {
  const contract = new Contract(address, IDiesisMarketsAbi, runner);
  return contract as unknown as IDiesisMarketsContract;
}
