// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { IDiesisOperatorBondAbi } from '../../generated/viem/IDiesisOperatorBond.abi.js';

export interface IDiesisOperatorBondContract {
  finalizeRelease(marketId: BytesLike): Promise<ContractTransactionResponse>;
  getBond(marketId: BytesLike): Promise<[string, string, bigint, bigint] & { operator: string; marketId: string; bondDs: bigint; releaseUnlockBlock: bigint }>;
  postBond(marketId: BytesLike): Promise<ContractTransactionResponse>;
  requestRelease(marketId: BytesLike): Promise<ContractTransactionResponse>;
  filters: {
    BondPosted(operator?: AddressLike | null, marketId?: BytesLike | null): EventFilter;
    BondSlashed(marketId?: BytesLike | null): EventFilter;
    ReleaseFinalized(marketId?: BytesLike | null): EventFilter;
    ReleaseRequested(marketId?: BytesLike | null): EventFilter;
  };
}

export function connectIDiesisOperatorBond(address: string, runner: ContractRunner): IDiesisOperatorBondContract {
  const contract = new Contract(address, IDiesisOperatorBondAbi, runner);
  return contract as unknown as IDiesisOperatorBondContract;
}
