// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisPerpDeployAbi } from '../../generated/viem/IDiesisPerpDeploy.abi.js';

export interface IDiesisPerpDeployMethods {
  applyPerpAbandonmentV1(marketId: BytesLike, parentHash: BytesLike, blockNumber: BigNumberish, policyEpoch: BigNumberish, policyHash: BytesLike, windowStart: BigNumberish, windowEnd: BigNumberish, filledVolume: BigNumberish, operatorFees: BigNumberish, lastMetadataUpdate: BigNumberish, inputHash: BytesLike, committeeEpoch: BigNumberish, committeeIdentity: BytesLike, quorumPower: BigNumberish, attestingPower: BigNumberish, voterCount: BigNumberish, evidenceHash: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  applySlash(marketId: BytesLike, reason: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  deployPerp(slotId: BytesLike, marketId: BytesLike, sourceList: BytesLike, metadata: BytesLike, signatures: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  expireNextUnactivatedPerpV1(overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  expireUnactivatedPerpV1(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  finalizeClose(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  finalizePerpPolicyV1(marketId: BytesLike, revision: BigNumberish, proposalId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  getDeploymentState(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint, bigint] & { stateTag: bigint; deadlineOrLiveBlock: bigint; windowCloseBlock: bigint; slashReason: bigint }>;
  getMarketDeploymentState(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint, bigint] & { stateTag: bigint; deadlineOrLiveBlock: bigint; windowCloseBlock: bigint; slashReason: bigint }>;
  getOperatorBalance(operator: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  getPerpPolicyV1(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[[bigint, bigint, ([bigint, bigint, bigint] & { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint })[]] & { revision: bigint; backstopTopupBps: bigint; tiers: ([bigint, bigint, bigint] & { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint })[] }, [bigint, bigint, string[]] & { epoch: bigint; threshold: bigint; signers: string[] }] & { policy: [bigint, bigint, ([bigint, bigint, bigint] & { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint })[]] & { revision: bigint; backstopTopupBps: bigint; tiers: ([bigint, bigint, bigint] & { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint })[] }; keyset: [bigint, bigint, string[]] & { epoch: bigint; threshold: bigint; signers: string[] } }>;
  initializePerpMarketV1(baseToken: AddressLike, quoteToken: AddressLike, tickSize: BigNumberish, lotSize: BigNumberish, maxOpenInterest: BigNumberish, initialMark: BigNumberish, maxLeverage: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  initializePerpMarketV2(baseToken: AddressLike, quoteToken: AddressLike, tickSize: BigNumberish, lotSize: BigNumberish, maxOpenInterest: BigNumberish, initialMark: BigNumberish, policy: { revision: BigNumberish; backstopTopupBps: BigNumberish; tiers: { maxNotional: BigNumberish; maxLeverage: BigNumberish; maintenanceMarginBps: BigNumberish }[] }, keyset: { epoch: BigNumberish; threshold: BigNumberish; signers: AddressLike[] }, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  initiateDelist(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  preparePerpMarketCloseV1(marketId: BytesLike, maxOrders: BigNumberish, maxPositions: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  promoteToLive(marketId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  proposePerpPolicyV1(marketId: BytesLike, expectedRevision: BigNumberish, expectedKeysetEpoch: BigNumberish, backstopTopupBps: BigNumberish, tiers: { maxNotional: BigNumberish; maxLeverage: BigNumberish; maintenanceMarginBps: BigNumberish }[], nextSigners: AddressLike[], nextThreshold: BigNumberish, signatures: { signer: AddressLike; r: BytesLike; s: BytesLike; v: BigNumberish }[], overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  recordAuctionWin(marketId: BytesLike, operator: AddressLike, registrationDigest: BytesLike, evidenceHash: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    Activated(marketId?: BytesLike | null): DeferredTopicFilter;
    AuctionWinRecorded(marketId?: BytesLike | null, operator?: AddressLike | null): DeferredTopicFilter;
    Closed(marketId?: BytesLike | null): DeferredTopicFilter;
    Delisting(marketId?: BytesLike | null): DeferredTopicFilter;
    LiveStarted(marketId?: BytesLike | null): DeferredTopicFilter;
    PerpMarketClosePreparedV1(marketId?: BytesLike | null): DeferredTopicFilter;
    PerpMarketInitializedV1(marketId?: BytesLike | null): DeferredTopicFilter;
    PerpMarketInitializedV2(marketId?: BytesLike | null): DeferredTopicFilter;
    Slashed(marketId?: BytesLike | null): DeferredTopicFilter;
  };
}

export type IDiesisPerpDeployContract = Omit<BaseContract, keyof IDiesisPerpDeployMethods | 'connect'> &
  IDiesisPerpDeployMethods & {
    connect(runner: ContractRunner | null): IDiesisPerpDeployContract;
  };

export function connectIDiesisPerpDeploy(address: string, runner: ContractRunner): IDiesisPerpDeployContract {
  const contract = new Contract(address, IDiesisPerpDeployAbi, runner);
  return contract as unknown as IDiesisPerpDeployContract;
}
