// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisSettlementAbi } from '../../generated/viem/IDiesisSettlement.abi.js';

export interface IDiesisSettlementMethods {
  authorizeSessionKey(sessionKey: AddressLike, actionScope: BigNumberish, validUntil: BigNumberish, maxNotionalOrSpend: BigNumberish, allowedMarketsMask: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  availableBalance(user: AddressLike, token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  cancelNonceWord(wordPos: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  cancelOrderNonce(nonce: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  creditRouterDeposit(user: AddressLike, token: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  debitRouterWithdrawal(user: AddressLike, token: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  deposit(token: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  fundPerpBackstop(marketId: BytesLike, amount: BigNumberish, nonce: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  getTradingKeyAuth(owner: AddressLike, tradingKey: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<[string, bigint, string] & { header: string; maxOrderNotional: bigint; allowedMarketsMask: string }>;
  isNonceUsed(user: AddressLike, nonce: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  registerTradingKey(tradingKey: AddressLike, validUntil: BigNumberish, maxOrderNotional: BigNumberish, allowedMarketsMask: BytesLike, canWithdraw: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  revokeSessionKey(sessionKey: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  revokeTradingKey(tradingKey: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  totalBalance(user: AddressLike, token: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  withdraw(token: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    Deposit(user?: AddressLike | null, token?: AddressLike | null): DeferredTopicFilter;
    NonceCancelled(user?: AddressLike | null): DeferredTopicFilter;
    PerpBackstopFunded(funder?: AddressLike | null, marketId?: BytesLike | null, quoteToken?: AddressLike | null): DeferredTopicFilter;
    TradingKeyRegistered(owner?: AddressLike | null, tradingKey?: AddressLike | null): DeferredTopicFilter;
    TradingKeyRevoked(owner?: AddressLike | null, tradingKey?: AddressLike | null): DeferredTopicFilter;
    Withdrawal(user?: AddressLike | null, token?: AddressLike | null): DeferredTopicFilter;
  };
}

export type IDiesisSettlementContract = Omit<BaseContract, keyof IDiesisSettlementMethods | 'connect'> &
  IDiesisSettlementMethods & {
    connect(runner: ContractRunner | null): IDiesisSettlementContract;
  };

export function connectIDiesisSettlement(address: string, runner: ContractRunner): IDiesisSettlementContract {
  const contract = new Contract(address, IDiesisSettlementAbi, runner);
  return contract as unknown as IDiesisSettlementContract;
}
