// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisNameVerifierAbi } from '../../generated/viem/IDiesisNameVerifier.abi.js';

export interface IDiesisNameVerifierMethods {
  attest(node: BytesLike, subject: AddressLike, kind: BytesLike, digest: BytesLike, expiresAt: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  attestationDigest(attestation: { node: BytesLike; attestationType: BytesLike; issuer: AddressLike; subjectHash: BytesLike; evidenceHash: BytesLike; issuedAt: BigNumberish; validUntil: BigNumberish; extraData: BytesLike }, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  attestationHash(attestation: { node: BytesLike; attestationType: BytesLike; issuer: AddressLike; subjectHash: BytesLike; evidenceHash: BytesLike; issuedAt: BigNumberish; validUntil: BigNumberish; extraData: BytesLike }, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  attestationsBytes32Bytes32(node: BytesLike, attestationType: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<string[]>;
  attestationsBytes32(attestationId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<[string, string, string, string, string, bigint, bigint, boolean] & { node: string; subject: string; kind: string; digest: string; issuer: string; issuedAt: bigint; expiresAt: bigint; revoked: boolean }>;
  isAttested(node: BytesLike, attestationType: BytesLike, issuer: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  isValid(attestationId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  issuers(issuer: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  revoke(attestationId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  revokeAttestation(node: BytesLike, attestationHash: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setIssuer(issuer: AddressLike, approved: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  submitAttestation(attestation: { node: BytesLike; attestationType: BytesLike; issuer: AddressLike; subjectHash: BytesLike; evidenceHash: BytesLike; issuedAt: BigNumberish; validUntil: BigNumberish; extraData: BytesLike }, signature: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    AttestationRevoked(node?: BytesLike | null, attestationHash?: BytesLike | null, issuer?: AddressLike | null): DeferredTopicFilter;
    AttestationSubmitted(node?: BytesLike | null, attestationType?: BytesLike | null, issuer?: AddressLike | null): DeferredTopicFilter;
    Attested(attestationId?: BytesLike | null, node?: BytesLike | null, subject?: AddressLike | null): DeferredTopicFilter;
    IssuerChanged(issuer?: AddressLike | null): DeferredTopicFilter;
    Revoked(attestationId?: BytesLike | null): DeferredTopicFilter;
  };
}

export type IDiesisNameVerifierContract = Omit<BaseContract, keyof IDiesisNameVerifierMethods | 'connect'> &
  IDiesisNameVerifierMethods & {
    connect(runner: ContractRunner | null): IDiesisNameVerifierContract;
  };

export function connectIDiesisNameVerifier(address: string, runner: ContractRunner): IDiesisNameVerifierContract {
  const contract = new Contract(address, IDiesisNameVerifierAbi, runner);
  Object.assign(contract, {
    attestationsBytes32Bytes32: contract.getFunction("attestations(bytes32,bytes32)"),
    attestationsBytes32: contract.getFunction("attestations(bytes32)"),
  });
  return contract as unknown as IDiesisNameVerifierContract;
}
