// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { IDiesisMarginAbi } from '../../generated/viem/IDiesisMargin.abi.js';

export interface IDiesisMarginContract {
  resolvePerpProtectionV1(marketId: BytesLike): Promise<ContractTransactionResponse>;
  filters: {
    AutoDeleverage(marketId?: BytesLike | null, deleveraged?: AddressLike | null, counterparty?: AddressLike | null): EventFilter;
    Liquidation(marketId?: BytesLike | null, trader?: AddressLike | null): EventFilter;
  };
}

export function connectIDiesisMargin(address: string, runner: ContractRunner): IDiesisMarginContract {
  const contract = new Contract(address, IDiesisMarginAbi, runner);
  return contract as unknown as IDiesisMarginContract;
}
