// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IDiesisPositionAbi } from '../../generated/viem/IDiesisPosition.abi.js';

export interface IDiesisPositionMethods {
  approve(to: AddressLike, tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  balanceOf(owner: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  claimRewards(tokenId: BigNumberish, recipient: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  delegate(tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransactionResponse>;
  effectiveLockUntil(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  freeCollateralOf(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  getApproved(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  hasLockCapacity(tokenId: BigNumberish, manager: AddressLike, lockId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  isApprovedForAll(owner: AddressLike, operator: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  isFunctionApproved(tokenId: BigNumberish, fn: BigNumberish, caller: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  lockPosition(tokenId: BigNumberish, lockDuration: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  lockPositionFor(tokenId: BigNumberish, lockId: BytesLike, lockDuration: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  lockRecordAt(tokenId: BigNumberish, index: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<[string, string, bigint] & { manager: string; lockId: string; lockedUntil: bigint }>;
  lockRecordCount(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  lockUntilFor(tokenId: BigNumberish, manager: AddressLike, lockId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  mergePosition(fromTokenId: BigNumberish, intoTokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  mint(validator: BigNumberish, overrides?: Overrides): Promise<ContractTransactionResponse>;
  mintLiquidToken(tokenId: BigNumberish, mintAmount: BigNumberish, recipient: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  mintShareDebt(tokenId: BigNumberish, shareDebt: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  ownerOf(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<string>;
  positionInfo(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint, bigint, bigint[]] & { debtAmount: bigint; lifetimeDelegated: bigint; lifetimeRewardsClaimed: bigint; lockedUntil: bigint; pendingWithdrawals: bigint[] }>;
  redeemShareBacking(fromTokenId: BigNumberish, toTokenId: BigNumberish, shareAmount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  repayLiquidToken(tokenId: BigNumberish, burnAmount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  restakeRewards(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  revokeFunctionApproval(tokenId: BigNumberish, fn: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  safeTransferFromAddressAddressUint256(from: AddressLike, to: AddressLike, tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  safeTransferFromAddressAddressUint256Bytes(from: AddressLike, to: AddressLike, tokenId: BigNumberish, data: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setApprovalForAll(operator: AddressLike, approved: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  setFunctionApproval(tokenId: BigNumberish, fn: BigNumberish, delegatee: AddressLike, expires: BigNumberish, revokable: boolean, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  shareDebtOf(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  splitPosition(fromTokenId: BigNumberish, splitAmount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  stakedAmountOf(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  supportsInterface(interfaceId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<boolean>;
  swapDelegate(fromTokenId: BigNumberish, toTokenId: BigNumberish, swapAmount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  totalDebtOf(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  totalStakedByValidator(validator: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  transferFrom(from: AddressLike, to: AddressLike, tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  undelegate(tokenId: BigNumberish, wrId: BigNumberish, undelegateAmount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  unlockPosition(tokenId: BigNumberish, lockId: BytesLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  validatorOf(tokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  withdraw(tokenId: BigNumberish, wrId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  withdrawTo(tokenId: BigNumberish, wrId: BigNumberish, recipient: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    Approval(owner?: AddressLike | null, approved?: AddressLike | null, tokenId?: BigNumberish | null): DeferredTopicFilter;
    ApprovalForAll(owner?: AddressLike | null, operator?: AddressLike | null): DeferredTopicFilter;
    Delegated(tokenId?: BigNumberish | null, validator?: BigNumberish | null): DeferredTopicFilter;
    FunctionApprovalRevoked(tokenId?: BigNumberish | null, fn?: BigNumberish | null): DeferredTopicFilter;
    FunctionApprovalSet(tokenId?: BigNumberish | null, fn?: BigNumberish | null, delegatee?: AddressLike | null): DeferredTopicFilter;
    InstantWithdrawExecuted(tokenId?: BigNumberish | null, withdrawAmount?: null, fee?: null, receiver?: AddressLike | null): DeferredTopicFilter;
    LiquidTokenMinted(tokenId?: BigNumberish | null, recipient?: AddressLike | null): DeferredTopicFilter;
    LiquidTokenRepaid(tokenId?: BigNumberish | null, payer?: AddressLike | null): DeferredTopicFilter;
    LockManagerSet(manager?: AddressLike | null): DeferredTopicFilter;
    LockRemoved(tokenId?: BigNumberish | null, manager?: AddressLike | null, lockId?: BytesLike | null): DeferredTopicFilter;
    LockSet(tokenId?: BigNumberish | null, manager?: AddressLike | null, lockId?: BytesLike | null): DeferredTopicFilter;
    Minted(tokenId?: BigNumberish | null, owner?: AddressLike | null, validator?: BigNumberish | null): DeferredTopicFilter;
    PositionMerged(fromTokenId?: BigNumberish | null, intoTokenId?: BigNumberish | null): DeferredTopicFilter;
    PositionSplit(fromTokenId?: BigNumberish | null, newTokenId?: BigNumberish | null): DeferredTopicFilter;
    RewardsClaimed(tokenId?: BigNumberish | null, recipient?: AddressLike | null): DeferredTopicFilter;
    RewardsRestaked(tokenId?: BigNumberish | null): DeferredTopicFilter;
    ShareBackingRedeemed(fromTokenId?: BigNumberish | null, toTokenId?: BigNumberish | null): DeferredTopicFilter;
    SwapDelegated(fromTokenId?: BigNumberish | null, toTokenId?: BigNumberish | null): DeferredTopicFilter;
    Transfer(from?: AddressLike | null, to?: AddressLike | null, tokenId?: BigNumberish | null): DeferredTopicFilter;
    Undelegated(tokenId?: BigNumberish | null, validator?: BigNumberish | null, wrId?: BigNumberish | null): DeferredTopicFilter;
    ValidatorExitFeeSet(validatorId_?: BigNumberish | null): DeferredTopicFilter;
    ValidatorShareSet(validatorShare?: AddressLike | null): DeferredTopicFilter;
    Withdrawn(tokenId?: BigNumberish | null, wrId?: BigNumberish | null): DeferredTopicFilter;
  };
}

export type IDiesisPositionContract = Omit<BaseContract, keyof IDiesisPositionMethods | 'connect'> &
  IDiesisPositionMethods & {
    connect(runner: ContractRunner | null): IDiesisPositionContract;
  };

export function connectIDiesisPosition(address: string, runner: ContractRunner): IDiesisPositionContract {
  const contract = new Contract(address, IDiesisPositionAbi, runner);
  Object.assign(contract, {
    safeTransferFromAddressAddressUint256: contract.getFunction("safeTransferFrom(address,address,uint256)"),
    safeTransferFromAddressAddressUint256Bytes: contract.getFunction("safeTransferFrom(address,address,uint256,bytes)"),
  });
  return contract as unknown as IDiesisPositionContract;
}
