// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { ILiquidStakedDSAbi } from '../../generated/viem/ILiquidStakedDS.abi.js';

export interface ILiquidStakedDSMethods {
  allowance(owner: AddressLike, spender: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  approve(spender: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  balanceOf(account: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  burn(amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  burnFrom(from: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  decimals(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  mint(to: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  name(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  symbol(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  totalSupply(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  transfer(to: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  transferFrom(from: AddressLike, to: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    Approval(owner?: AddressLike | null, spender?: AddressLike | null): DeferredTopicFilter;
    Transfer(from?: AddressLike | null, to?: AddressLike | null): DeferredTopicFilter;
  };
}

export type ILiquidStakedDSContract = Omit<BaseContract, keyof ILiquidStakedDSMethods | 'connect'> &
  ILiquidStakedDSMethods & {
    connect(runner: ContractRunner | null): ILiquidStakedDSContract;
  };

export function connectILiquidStakedDS(address: string, runner: ContractRunner): ILiquidStakedDSContract {
  const contract = new Contract(address, ILiquidStakedDSAbi, runner);
  return contract as unknown as ILiquidStakedDSContract;
}
