// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';
import { ILiquidStakedDSAbi } from '../../generated/viem/ILiquidStakedDS.abi.js';

export interface ILiquidStakedDSContract {
  allowance(owner: AddressLike, spender: AddressLike): Promise<bigint>;
  approve(spender: AddressLike, amount: BigNumberish): Promise<ContractTransactionResponse>;
  balanceOf(account: AddressLike): Promise<bigint>;
  burn(amount: BigNumberish): Promise<ContractTransactionResponse>;
  burnFrom(from: AddressLike, amount: BigNumberish): Promise<ContractTransactionResponse>;
  decimals(): Promise<bigint>;
  mint(to: AddressLike, amount: BigNumberish): Promise<ContractTransactionResponse>;
  name(): Promise<string>;
  symbol(): Promise<string>;
  totalSupply(): Promise<bigint>;
  transfer(to: AddressLike, amount: BigNumberish): Promise<ContractTransactionResponse>;
  transferFrom(from: AddressLike, to: AddressLike, amount: BigNumberish): Promise<ContractTransactionResponse>;
  filters: {
    Approval(owner?: AddressLike | null, spender?: AddressLike | null): EventFilter;
    Transfer(from?: AddressLike | null, to?: AddressLike | null): EventFilter;
  };
}

export function connectILiquidStakedDS(address: string, runner: ContractRunner): ILiquidStakedDSContract {
  const contract = new Contract(address, ILiquidStakedDSAbi, runner);
  return contract as unknown as ILiquidStakedDSContract;
}
