// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BaseContract, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type DeferredTopicFilter, type Overrides } from 'ethers';
import { IValidatorShareAbi } from '../../generated/viem/IValidatorShare.abi.js';

export interface IValidatorShareMethods {
  DIESIS_POSITION(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  MAX_LOTS_PER_REDEMPTION(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  MIN_BACKING_LOT(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  backingLot(validator: BigNumberish, slot: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint, boolean] & { sourcePositionId: bigint; remaining: bigint; next: bigint; active: boolean }>;
  backingLotForPosition(validator: BigNumberish, sourcePositionId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, boolean] & { slot: bigint; remaining: bigint; active: boolean }>;
  backingPoolState(validator: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<[bigint, bigint, bigint, bigint] & { head: bigint; tail: bigint; liveLots: bigint; backing: bigint }>;
  mintShares(positionTokenId: BigNumberish, shareAmount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  pooledBacking(validator: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  redeemShares(receiverPositionId: BigNumberish, shareTokenId: BigNumberish, shareAmount: BigNumberish, maxLots: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  repayShares(sourcePositionId: BigNumberish, shareAmount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  swapPositionBalance(fromTokenId: BigNumberish, toTokenId: BigNumberish, swapAmount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  totalSupply(shareTokenId: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  validatorShareTokenId(validator: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  filters: {
    BackingAdded(validator?: BigNumberish | null, sourcePositionId?: BigNumberish | null): DeferredTopicFilter;
    BackingConsumed(validator?: BigNumberish | null, sourcePositionId?: BigNumberish | null, receiverPositionId?: BigNumberish | null): DeferredTopicFilter;
    BackingRepaid(validator?: BigNumberish | null, sourcePositionId?: BigNumberish | null): DeferredTopicFilter;
    PositionBalanceSwapped(fromTokenId?: BigNumberish | null, toTokenId?: BigNumberish | null): DeferredTopicFilter;
    SharesMinted(positionTokenId?: BigNumberish | null, shareTokenId?: BigNumberish | null): DeferredTopicFilter;
    SharesRedeemed(receiverPositionId?: BigNumberish | null, shareTokenId?: BigNumberish | null): DeferredTopicFilter;
  };
}

export type IValidatorShareContract = Omit<BaseContract, keyof IValidatorShareMethods | 'connect'> &
  IValidatorShareMethods & {
    connect(runner: ContractRunner | null): IValidatorShareContract;
  };

export function connectIValidatorShare(address: string, runner: ContractRunner): IValidatorShareContract {
  const contract = new Contract(address, IValidatorShareAbi, runner);
  return contract as unknown as IValidatorShareContract;
}
