// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter, type Overrides } from 'ethers';
import { IWrappedDSAbi } from '../../generated/viem/IWrappedDS.abi.js';

export interface IWrappedDSContract {
  allowance(owner: AddressLike, spender: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  approve(spender: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  balanceOf(account: AddressLike, overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  decimals(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  deposit(overrides?: Overrides): Promise<ContractTransactionResponse>;
  name(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  symbol(overrides?: Omit<Overrides, 'value'>): Promise<string>;
  totalSupply(overrides?: Omit<Overrides, 'value'>): Promise<bigint>;
  transfer(to: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  transferFrom(from: AddressLike, to: AddressLike, amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  withdraw(amount: BigNumberish, overrides?: Omit<Overrides, 'value'>): Promise<ContractTransactionResponse>;
  filters: {
    Approval(owner?: AddressLike | null, spender?: AddressLike | null): EventFilter;
    Deposit(dst?: AddressLike | null): EventFilter;
    Transfer(from?: AddressLike | null, to?: AddressLike | null): EventFilter;
    Withdrawal(src?: AddressLike | null): EventFilter;
  };
}

export function connectIWrappedDS(address: string, runner: ContractRunner): IWrappedDSContract {
  const contract = new Contract(address, IWrappedDSAbi, runner);
  return contract as unknown as IWrappedDSContract;
}
