// Generated by scripts/generate-contract-bindings.mjs. Do not edit.

/**
 * Fixed-address Diesis system contracts, each paired with its typed ABI.
 * Spread an entry into viem `getContract` or wagmi `useReadContract`, or pass
 * its `address` to a generated `connect*` or `get*Contract` wrapper.
 */
import {
  DIESIS_BASE_REGISTRAR,
  DIESIS_BUNDLE_ESCROW,
  DIESIS_BUYBACK_BURN,
  DIESIS_CONDUCTORS,
  DIESIS_CONFIG,
  DIESIS_CORE_VAULT,
  DIESIS_ERC20_FACTORY,
  DIESIS_ISSUANCE_AUCTION,
  DIESIS_MARGIN,
  DIESIS_MARKETS,
  DIESIS_NAME_POLICY,
  DIESIS_NAME_REGISTRY,
  DIESIS_NAME_VERIFIER,
  DIESIS_OPERATOR_BOND,
  DIESIS_PATRON,
  DIESIS_PERPS_BOOK,
  DIESIS_PERP_DEPLOY,
  DIESIS_POSITION,
  DIESIS_PUBLIC_RESOLVER,
  DIESIS_REVERSE_REGISTRAR,
  DIESIS_SETTLEMENT,
  DIESIS_SETTLEMENT_ROUTER,
  DIESIS_SPOT_BOOK,
  DIESIS_STAKING,
  LIQUID_STAKED_DS,
  PRIVACY_POOLS,
  SHIELDED_POOL,
  WRAPPED_DS,
} from '../../addresses.js'
import {
  DiesisBaseRegistrarAbi,
  DiesisConfigAbi,
  DiesisPatronAbi,
  DiesisPrivacyPoolsAbi,
  DiesisPublicResolverAbi,
  DiesisSettlementRouterAbi,
  DiesisShieldedPoolAbi,
  DiesisStakingAbi,
  IDiesisBundleEscrowAbi,
  IDiesisBuybackBurnAbi,
  IDiesisConductorsAbi,
  IDiesisCoreVaultAbi,
  IDiesisErc20FactoryAbi,
  IDiesisIssuanceAuctionAbi,
  IDiesisMarginAbi,
  IDiesisMarketsAbi,
  IDiesisNamePolicyAbi,
  IDiesisNameRegistryAbi,
  IDiesisNameVerifierAbi,
  IDiesisOperatorBondAbi,
  IDiesisPerpDeployAbi,
  IDiesisPerpsBookAbi,
  IDiesisPositionAbi,
  IDiesisReverseRegistrarAbi,
  IDiesisSettlementAbi,
  IDiesisSpotBookAbi,
  ILiquidStakedDSAbi,
  IWrappedDSAbi,
} from '../generated/viem/index.js'

export const diesisContracts = {
  markets: {
    address: DIESIS_MARKETS,
    abi: IDiesisMarketsAbi,
  },
  spotBook: {
    address: DIESIS_SPOT_BOOK,
    abi: IDiesisSpotBookAbi,
  },
  perpsBook: {
    address: DIESIS_PERPS_BOOK,
    abi: IDiesisPerpsBookAbi,
  },
  margin: {
    address: DIESIS_MARGIN,
    abi: IDiesisMarginAbi,
  },
  settlement: {
    address: DIESIS_SETTLEMENT,
    abi: IDiesisSettlementAbi,
  },
  settlementRouter: {
    address: DIESIS_SETTLEMENT_ROUTER,
    abi: DiesisSettlementRouterAbi,
  },
  conductors: {
    address: DIESIS_CONDUCTORS,
    abi: IDiesisConductorsAbi,
  },
  erc20Factory: {
    address: DIESIS_ERC20_FACTORY,
    abi: IDiesisErc20FactoryAbi,
  },
  perpDeploy: {
    address: DIESIS_PERP_DEPLOY,
    abi: IDiesisPerpDeployAbi,
  },
  operatorBond: {
    address: DIESIS_OPERATOR_BOND,
    abi: IDiesisOperatorBondAbi,
  },
  bundleEscrow: {
    address: DIESIS_BUNDLE_ESCROW,
    abi: IDiesisBundleEscrowAbi,
  },
  staking: {
    address: DIESIS_STAKING,
    abi: DiesisStakingAbi,
  },
  position: {
    address: DIESIS_POSITION,
    abi: IDiesisPositionAbi,
  },
  liquidStakedDS: {
    address: LIQUID_STAKED_DS,
    abi: ILiquidStakedDSAbi,
  },
  wrappedDS: {
    address: WRAPPED_DS,
    abi: IWrappedDSAbi,
  },
  patron: {
    address: DIESIS_PATRON,
    abi: DiesisPatronAbi,
  },
  config: {
    address: DIESIS_CONFIG,
    abi: DiesisConfigAbi,
  },
  coreVault: {
    address: DIESIS_CORE_VAULT,
    abi: IDiesisCoreVaultAbi,
  },
  issuanceAuction: {
    address: DIESIS_ISSUANCE_AUCTION,
    abi: IDiesisIssuanceAuctionAbi,
  },
  buybackBurn: {
    address: DIESIS_BUYBACK_BURN,
    abi: IDiesisBuybackBurnAbi,
  },
  shieldedPool: {
    address: SHIELDED_POOL,
    abi: DiesisShieldedPoolAbi,
  },
  privacyPools: {
    address: PRIVACY_POOLS,
    abi: DiesisPrivacyPoolsAbi,
  },
  nameRegistry: {
    address: DIESIS_NAME_REGISTRY,
    abi: IDiesisNameRegistryAbi,
  },
  baseRegistrar: {
    address: DIESIS_BASE_REGISTRAR,
    abi: DiesisBaseRegistrarAbi,
  },
  publicResolver: {
    address: DIESIS_PUBLIC_RESOLVER,
    abi: DiesisPublicResolverAbi,
  },
  reverseRegistrar: {
    address: DIESIS_REVERSE_REGISTRAR,
    abi: IDiesisReverseRegistrarAbi,
  },
  nameVerifier: {
    address: DIESIS_NAME_VERIFIER,
    abi: IDiesisNameVerifierAbi,
  },
  namePolicy: {
    address: DIESIS_NAME_POLICY,
    abi: IDiesisNamePolicyAbi,
  },
} as const

export type DiesisContractName = keyof typeof diesisContracts
