// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { DiesisConfigAbi } from '../../generated/viem/DiesisConfig.abi.js';

export interface DiesisConfigContract {
  methods: {
    CUT_RATE_UPPER(): { call(): Promise<bigint>; };
    DEFAULT_DELEGATION_FANOUT_LIMIT(): { call(): Promise<bigint>; };
    DEFAULT_EXIT_DELAY_CHECKPOINTS(): { call(): Promise<bigint>; };
    DEFAULT_EXIT_DELAY_SECONDS(): { call(): Promise<bigint>; };
    DEFAULT_LIVENESS_DOWNTIME_LIMIT(): { call(): Promise<bigint>; };
    DEFAULT_LIVENESS_MISSED_BLOCK_LIMIT(): { call(): Promise<bigint>; };
    DEFAULT_NETWORK_BURN_CUT(): { call(): Promise<bigint>; };
    DEFAULT_OPERATOR_TAKE_RATE(): { call(): Promise<bigint>; };
    DEFAULT_RELIABILITY_FLOOR(): { call(): Promise<bigint>; };
    DEFAULT_RELIABILITY_SAMPLE_CHECKPOINTS(): { call(): Promise<bigint>; };
    DEFAULT_REWARD_STREAM_PER_SECOND(): { call(): Promise<bigint>; };
    DEFAULT_SURPLUS_REWARD_BURN_CUT(): { call(): Promise<bigint>; };
    DEFAULT_TREASURY_CUT(): { call(): Promise<bigint>; };
    DEFAULT_VALIDATOR_BOND_FLOOR(): { call(): Promise<bigint>; };
    DELEGATION_FANOUT_LIMIT_LOWER(): { call(): Promise<bigint>; };
    DELEGATION_FANOUT_LIMIT_UPPER(): { call(): Promise<bigint>; };
    EXIT_DELAY_CHECKPOINTS_LOWER(): { call(): Promise<bigint>; };
    EXIT_DELAY_CHECKPOINTS_UPPER(): { call(): Promise<bigint>; };
    EXIT_DELAY_SECONDS_LOWER(): { call(): Promise<bigint>; };
    EXIT_DELAY_SECONDS_UPPER(): { call(): Promise<bigint>; };
    LIVENESS_DOWNTIME_LIMIT_LOWER(): { call(): Promise<bigint>; };
    LIVENESS_DOWNTIME_LIMIT_UPPER(): { call(): Promise<bigint>; };
    LIVENESS_MISSED_BLOCK_LIMIT_LOWER(): { call(): Promise<bigint>; };
    LIVENESS_MISSED_BLOCK_LIMIT_UPPER(): { call(): Promise<bigint>; };
    OPERATOR_TAKE_RATE_UPPER(): { call(): Promise<bigint>; };
    RELIABILITY_FLOOR_UPPER(): { call(): Promise<bigint>; };
    RELIABILITY_SAMPLE_LOWER(): { call(): Promise<bigint>; };
    RELIABILITY_SAMPLE_UPPER(): { call(): Promise<bigint>; };
    REWARD_STREAM_PER_SECOND_UPPER(): { call(): Promise<bigint>; };
    SURPLUS_REWARD_BURN_CUT_UPPER(): { call(): Promise<bigint>; };
    VALIDATOR_BOND_FLOOR_LOWER(): { call(): Promise<bigint>; };
    VALIDATOR_BOND_FLOOR_UPPER(): { call(): Promise<bigint>; };
    delegationFanoutLimit(): { call(): Promise<bigint>; };
    exitDelayCheckpoints(): { call(): Promise<bigint>; };
    exitDelaySeconds(): { call(): Promise<bigint>; };
    livenessDowntimeLimit(): { call(): Promise<bigint>; };
    livenessMissedBlockLimit(): { call(): Promise<bigint>; };
    mintReceiver(): { call(): Promise<string>; };
    networkBurnCut(): { call(): Promise<bigint>; };
    operatorTakeRate(): { call(): Promise<bigint>; };
    owner(): { call(): Promise<string>; };
    reliabilityFloor(): { call(): Promise<bigint>; };
    reliabilitySampleCheckpoints(): { call(): Promise<bigint>; };
    renounceOwnership(): { send(options: { from: string }): Promise<unknown>; };
    rewardStreamPerSecond(): { call(): Promise<bigint>; };
    setDelegationFanoutLimit(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setExitDelayCheckpoints(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setExitDelaySeconds(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setLivenessDowntimeLimit(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setLivenessMissedBlockLimit(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setMintReceiver(v: string): { send(options: { from: string }): Promise<unknown>; };
    setNetworkBurnCut(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setOperatorTakeRate(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setReliabilityFloor(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setReliabilitySampleCheckpoints(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setRewardStreamPerSecond(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setSurplusRewardBurnCut(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setTreasuryCut(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    setValidatorBondFloor(v: Numbers): { send(options: { from: string }): Promise<unknown>; };
    surplusRewardBurnCut(): { call(): Promise<bigint>; };
    transferOwnership(newOwner: string): { send(options: { from: string }): Promise<unknown>; };
    treasuryCut(): { call(): Promise<bigint>; };
    validatorBondFloor(): { call(): Promise<bigint>; };
  };
  events: {
    DelegationFanoutLimitUpdated: { (options?: {}): unknown; };
    ExitDelayCheckpointsUpdated: { (options?: {}): unknown; };
    ExitDelaySecondsUpdated: { (options?: {}): unknown; };
    LivenessDowntimeLimitUpdated: { (options?: {}): unknown; };
    LivenessMissedBlockLimitUpdated: { (options?: {}): unknown; };
    MintReceiverUpdated: { (options?: { filter?: { value?: string } }): unknown; };
    NetworkBurnCutUpdated: { (options?: {}): unknown; };
    OperatorTakeRateUpdated: { (options?: {}): unknown; };
    OwnershipTransferred: { (options?: { filter?: { previousOwner?: string; newOwner?: string } }): unknown; };
    ReliabilityFloorUpdated: { (options?: {}): unknown; };
    ReliabilitySampleCheckpointsUpdated: { (options?: {}): unknown; };
    RewardStreamPerSecondUpdated: { (options?: {}): unknown; };
    SurplusRewardBurnCutUpdated: { (options?: {}): unknown; };
    TreasuryCutUpdated: { (options?: {}): unknown; };
    ValidatorBondFloorUpdated: { (options?: {}): unknown; };
  };
}

export function createDiesisConfig(web3: Web3, address: string): DiesisConfigContract {
  return new Contract(DiesisConfigAbi as any, address, web3) as unknown as DiesisConfigContract;
}
