// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisMarketsAbi } from '../../generated/viem/IDiesisMarkets.abi.js';

export interface IDiesisMarketsContract {
  methods: {
    checkCircuitBreaker(marketId: string, currentPrice: Numbers, referencePrice: Numbers, thresholdBps: Numbers): { send(options: { from: string }): Promise<unknown>; };
    createSpotMarket(baseToken: string, quoteToken: string, tickSize: Numbers, lotSize: Numbers, bond: Numbers): { send(options: { from: string }): Promise<unknown>; };
    deployTokenAndSpotBook(symbol: string, name: string, initialSupply: Numbers, dsBond: Numbers, usdcFee: Numbers): { send(options: { from: string }): Promise<unknown>; };
    getMarket(marketId: string): { call(): Promise<{ slot0: string; slot1: string; maxOpenInterest: bigint }>; };
    resumeMarket(marketId: string): { send(options: { from: string }): Promise<unknown>; };
  };
  events: {
    CircuitBreakerTriggered: { (options?: { filter?: { marketId?: string } }): unknown; };
    MarketCreated: { (options?: { filter?: { marketId?: string } }): unknown; };
  };
}

export function createIDiesisMarkets(web3: Web3, address: string): IDiesisMarketsContract {
  return new Contract(IDiesisMarketsAbi as any, address, web3) as unknown as IDiesisMarketsContract;
}
