// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisSpotBookAbi } from '../../generated/viem/IDiesisSpotBook.abi.js';

type IDiesisSpotBookMethodObject<Mutability extends 'payable' | 'nonpayable'> = ReturnType<
  Contract<
    readonly [
      {
        readonly type: 'function';
        readonly name: 'm';
        readonly stateMutability: Mutability;
        readonly inputs: readonly [];
        readonly outputs: readonly [];
      },
    ]
  >['methods']['m']
>;
type IDiesisSpotBookMethod<Mutability extends 'payable' | 'nonpayable', Output> = Omit<
  IDiesisSpotBookMethodObject<Mutability>,
  'call'
> & {
  call(...args: Parameters<IDiesisSpotBookMethodObject<Mutability>['call']>): Promise<Output>;
};

export interface IDiesisSpotBookMethods {
  amendOrder(orderId: string, newPrice: Numbers, newAmount: Numbers, newFlags: Numbers): IDiesisSpotBookMethod<'nonpayable', string>;
  cancelOrder(orderId: string): IDiesisSpotBookMethod<'nonpayable', void>;
  executeSpotFill(orderId: string, fillPrice: Numbers, fillQty: Numbers): IDiesisSpotBookMethod<'nonpayable', { 0: bigint; 1: bigint; filledQty: bigint; executionPrice: bigint; __length__: number }>;
  executeSpotTrade(makerOrderId: string, takerOrderId: string, fillPrice: Numbers, fillQty: Numbers): IDiesisSpotBookMethod<'nonpayable', { 0: bigint; 1: bigint; filledQty: bigint; executionPrice: bigint; __length__: number }>;
  finalizeOpeningAuction(marketId: string): IDiesisSpotBookMethod<'nonpayable', { 0: bigint; 1: bigint; clearingPrice: bigint; totalVolume: bigint; __length__: number }>;
  getBestAsk(marketId: string): IDiesisSpotBookMethod<'nonpayable', { 0: bigint; 1: bigint; priceTicks: bigint; amountLots: bigint; __length__: number }>;
  getBestBid(marketId: string): IDiesisSpotBookMethod<'nonpayable', { 0: bigint; 1: bigint; priceTicks: bigint; amountLots: bigint; __length__: number }>;
  getOpeningAuction(marketId: string): IDiesisSpotBookMethod<'nonpayable', { 0: bigint; 1: bigint; 2: bigint; 3: boolean; 4: bigint; 5: bigint; startBlock: bigint; endBlock: bigint; referencePrice: bigint; finalized: boolean; clearingPrice: bigint; totalVolume: bigint; __length__: number }>;
  getOrderBookDepth(marketId: string, levels: Numbers): IDiesisSpotBookMethod<'nonpayable', { 0: bigint[]; 1: bigint[]; 2: bigint[]; 3: bigint[]; bidPrices: bigint[]; bidAmounts: bigint[]; askPrices: bigint[]; askAmounts: bigint[]; __length__: number }>;
  getUserOrders(user: string, marketId: string): IDiesisSpotBookMethod<'nonpayable', string[]>;
  startOpeningAuction(marketId: string, startBlock: Numbers, endBlock: Numbers, referencePrice: Numbers): IDiesisSpotBookMethod<'nonpayable', void>;
  submitBoundSessionActions(encodedWrapper: string): IDiesisSpotBookMethod<'nonpayable', { 0: string; 1: bigint; 2: bigint; resultHash: string; acceptedCount: bigint; rejectedCount: bigint; __length__: number }>;
  submitExchangeActions(encodedActions: string): IDiesisSpotBookMethod<'nonpayable', { 0: string; 1: bigint; 2: bigint; resultHash: string; acceptedCount: bigint; rejectedCount: bigint; __length__: number }>;
  submitLimitOrder(marketId: string, side: Numbers, priceTicks: Numbers, amountLots: Numbers, flags: Numbers): IDiesisSpotBookMethod<'nonpayable', string>;
  submitMarketOrder(marketId: string, side: Numbers, amountLots: Numbers): IDiesisSpotBookMethod<'nonpayable', { 0: bigint; 1: string; filledAmount: bigint; orderId: string; __length__: number }>;
  submitSignedCancelAllSpotIntent(signedCancelAllJson: string): IDiesisSpotBookMethod<'nonpayable', bigint>;
  submitSignedSpotIntent(signedIntentJson: string): IDiesisSpotBookMethod<'nonpayable', void>;
  triggerSpotStops(marketId: string, maxOrders: Numbers): IDiesisSpotBookMethod<'nonpayable', { 0: bigint; 1: boolean; activated: bigint; hasMore: boolean; __length__: number }>;
}

export type IDiesisSpotBookContract = Omit<Contract<typeof IDiesisSpotBookAbi>, 'methods'> & {
  readonly methods: IDiesisSpotBookMethods;
};

export function createIDiesisSpotBook(web3: Web3, address: string): IDiesisSpotBookContract {
  return new Contract(IDiesisSpotBookAbi, address, web3) as unknown as IDiesisSpotBookContract;
}
