// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisPerpsBookAbi } from '../../generated/viem/IDiesisPerpsBook.abi.js';

type IDiesisPerpsBookMethodObject<Mutability extends 'payable' | 'nonpayable'> = ReturnType<
  Contract<
    readonly [
      {
        readonly type: 'function';
        readonly name: 'm';
        readonly stateMutability: Mutability;
        readonly inputs: readonly [];
        readonly outputs: readonly [];
      },
    ]
  >['methods']['m']
>;
type IDiesisPerpsBookMethod<Mutability extends 'payable' | 'nonpayable', Output> = Omit<
  IDiesisPerpsBookMethodObject<Mutability>,
  'call'
> & {
  call(...args: Parameters<IDiesisPerpsBookMethodObject<Mutability>['call']>): Promise<Output>;
};

export interface IDiesisPerpsBookMethods {
  adjustIsolatedMargin(marketId: string, marginDelta: Numbers): IDiesisPerpsBookMethod<'nonpayable', void>;
  amendPerpOrderV1(orderId: string, price: Numbers, amount: Numbers, expiry: Numbers): IDiesisPerpsBookMethod<'nonpayable', string>;
  applyPerpFundingV1(marketId: string, fundingRateBps: Numbers): IDiesisPerpsBookMethod<'nonpayable', void>;
  cancelPerpOrderV1(orderId: string): IDiesisPerpsBookMethod<'nonpayable', void>;
  executePerpTradeV1(makerOrderId: string, takerOrderId: string, fillPrice: Numbers, fillQty: Numbers): IDiesisPerpsBookMethod<'nonpayable', string>;
  expirePerpOrderV1(orderId: string): IDiesisPerpsBookMethod<'nonpayable', void>;
  finalizePerpFeeEpochV2(marketId: string, epoch: Numbers, snapshotHash: string): IDiesisPerpsBookMethod<'nonpayable', void>;
  getIsolatedMargin(trader: string, marketId: string): IDiesisPerpsBookMethod<'nonpayable', bigint>;
  getPosition(trader: string, marketId: string): IDiesisPerpsBookMethod<'nonpayable', { header: string; size: bigint; entryPrice: bigint }>;
  submitExchangeActionsV2(encodedActions: string): IDiesisPerpsBookMethod<'nonpayable', { 0: string; 1: bigint; 2: bigint; resultHash: string; acceptedCount: bigint; rejectedCount: bigint; __length__: number }>;
  submitPerpOrderV1(marketId: string, side: Numbers, orderType: Numbers, price: Numbers, amount: Numbers, flags: Numbers, marginType: Numbers, expiry: Numbers): IDiesisPerpsBookMethod<'nonpayable', string>;
  submitSignedPerpActionsV2(signedEnvelope: string): IDiesisPerpsBookMethod<'nonpayable', string>;
  updatePerpMarkV1(marketId: string, markPrice: Numbers): IDiesisPerpsBookMethod<'nonpayable', void>;
  updatePerpOracleV1(marketId: string, indexPrice: Numbers, markPrice: Numbers, observedAt: Numbers, oracleRound: Numbers, sourceSetHash: string, evidenceHash: string): IDiesisPerpsBookMethod<'nonpayable', void>;
}

export type IDiesisPerpsBookContract = Omit<Contract<typeof IDiesisPerpsBookAbi>, 'methods'> & {
  readonly methods: IDiesisPerpsBookMethods;
};

export function createIDiesisPerpsBook(web3: Web3, address: string): IDiesisPerpsBookContract {
  return new Contract(IDiesisPerpsBookAbi, address, web3) as unknown as IDiesisPerpsBookContract;
}
