// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisPerpDeployAbi } from '../../generated/viem/IDiesisPerpDeploy.abi.js';

type IDiesisPerpDeployMethodObject<Mutability extends 'payable' | 'nonpayable'> = ReturnType<
  Contract<
    readonly [
      {
        readonly type: 'function';
        readonly name: 'm';
        readonly stateMutability: Mutability;
        readonly inputs: readonly [];
        readonly outputs: readonly [];
      },
    ]
  >['methods']['m']
>;
type IDiesisPerpDeployMethod<Mutability extends 'payable' | 'nonpayable', Output> = Omit<
  IDiesisPerpDeployMethodObject<Mutability>,
  'call'
> & {
  call(...args: Parameters<IDiesisPerpDeployMethodObject<Mutability>['call']>): Promise<Output>;
};

export interface IDiesisPerpDeployMethods {
  applyPerpAbandonment(marketId: string, parentHash: string, blockNumber: Numbers, policyEpoch: Numbers, policyHash: string, windowStart: Numbers, windowEnd: Numbers, filledVolume: Numbers, operatorFees: Numbers, lastMetadataUpdate: Numbers, inputHash: string, committeeEpoch: Numbers, committeeIdentity: string, quorumPower: Numbers, attestingPower: Numbers, voterCount: Numbers, evidenceHash: string): IDiesisPerpDeployMethod<'nonpayable', void>;
  applySlash(marketId: string, reason: Numbers): IDiesisPerpDeployMethod<'nonpayable', void>;
  deployPerp(slotId: string, marketId: string, sourceList: string, metadata: string, signatures: string): IDiesisPerpDeployMethod<'nonpayable', string>;
  expireNextUnactivatedPerp(): IDiesisPerpDeployMethod<'nonpayable', void>;
  expireUnactivatedPerp(marketId: string): IDiesisPerpDeployMethod<'nonpayable', void>;
  finalizeClose(marketId: string): IDiesisPerpDeployMethod<'nonpayable', void>;
  finalizePerpPolicy(marketId: string, revision: Numbers, proposalId: string): IDiesisPerpDeployMethod<'nonpayable', void>;
  getDeploymentState(marketId: string): IDiesisPerpDeployMethod<'nonpayable', { stateTag: bigint; deadlineOrLiveBlock: bigint; windowCloseBlock: bigint; slashReason: bigint }>;
  getMarketDeploymentState(marketId: string): IDiesisPerpDeployMethod<'nonpayable', { stateTag: bigint; deadlineOrLiveBlock: bigint; windowCloseBlock: bigint; slashReason: bigint }>;
  getOperatorBalance(operator: string): IDiesisPerpDeployMethod<'nonpayable', bigint>;
  getPerpPolicy(marketId: string): IDiesisPerpDeployMethod<'nonpayable', { 0: { revision: bigint; backstopTopupBps: bigint; tiers: { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint }[] }; 1: { epoch: bigint; threshold: bigint; signers: string[] }; policy: { revision: bigint; backstopTopupBps: bigint; tiers: { maxNotional: bigint; maxLeverage: bigint; maintenanceMarginBps: bigint }[] }; keyset: { epoch: bigint; threshold: bigint; signers: string[] }; __length__: number }>;
  initializeBasicPerpMarket(baseToken: string, quoteToken: string, tickSize: Numbers, lotSize: Numbers, maxOpenInterest: Numbers, initialMark: Numbers, maxLeverage: Numbers): IDiesisPerpDeployMethod<'nonpayable', string>;
  initializePolicyPerpMarket(baseToken: string, quoteToken: string, tickSize: Numbers, lotSize: Numbers, maxOpenInterest: Numbers, initialMark: Numbers, policy: { revision: Numbers; backstopTopupBps: Numbers; tiers: { maxNotional: Numbers; maxLeverage: Numbers; maintenanceMarginBps: Numbers }[] }, keyset: { epoch: Numbers; threshold: Numbers; signers: string[] }): IDiesisPerpDeployMethod<'nonpayable', string>;
  initializePricedPerpMarket(baseToken: string, quoteToken: string, tickSize: Numbers, lotSize: Numbers, priceDenominator: Numbers, maxOpenInterest: Numbers, initialMark: Numbers, policy: { revision: Numbers; backstopTopupBps: Numbers; tiers: { maxNotional: Numbers; maxLeverage: Numbers; maintenanceMarginBps: Numbers }[] }, keyset: { epoch: Numbers; threshold: Numbers; signers: string[] }): IDiesisPerpDeployMethod<'nonpayable', string>;
  initiateDelist(marketId: string): IDiesisPerpDeployMethod<'nonpayable', void>;
  installPricedOracleDescriptor(marketId: string, baseDecimals: Numbers, quoteDecimals: Numbers, roundingPolicy: Numbers, sourceSetHash: string): IDiesisPerpDeployMethod<'nonpayable', void>;
  preparePerpMarketClose(marketId: string, maxOrders: Numbers, maxPositions: Numbers): IDiesisPerpDeployMethod<'nonpayable', boolean>;
  promoteToLive(marketId: string): IDiesisPerpDeployMethod<'nonpayable', void>;
  proposePerpPolicy(marketId: string, expectedRevision: Numbers, expectedKeysetEpoch: Numbers, backstopTopupBps: Numbers, tiers: { maxNotional: Numbers; maxLeverage: Numbers; maintenanceMarginBps: Numbers }[], nextSigners: string[], nextThreshold: Numbers, signatures: { signer: string; r: string; s: string; v: Numbers }[]): IDiesisPerpDeployMethod<'nonpayable', { 0: string; 1: bigint; proposalId: string; executeAfter: bigint; __length__: number }>;
  recordAuctionWin(marketId: string, operator: string, registrationDigest: string, evidenceHash: string): IDiesisPerpDeployMethod<'nonpayable', void>;
}

export type IDiesisPerpDeployContract = Omit<Contract<typeof IDiesisPerpDeployAbi>, 'methods'> & {
  readonly methods: IDiesisPerpDeployMethods;
};

export function createIDiesisPerpDeploy(web3: Web3, address: string): IDiesisPerpDeployContract {
  return new Contract(IDiesisPerpDeployAbi, address, web3) as unknown as IDiesisPerpDeployContract;
}
