// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisConductorsAbi } from '../../generated/viem/IDiesisConductors.abi.js';

type IDiesisConductorsMethodObject<Mutability extends 'payable' | 'nonpayable'> = ReturnType<
  Contract<
    readonly [
      {
        readonly type: 'function';
        readonly name: 'm';
        readonly stateMutability: Mutability;
        readonly inputs: readonly [];
        readonly outputs: readonly [];
      },
    ]
  >['methods']['m']
>;
type IDiesisConductorsMethod<Mutability extends 'payable' | 'nonpayable', Output> = Omit<
  IDiesisConductorsMethodObject<Mutability>,
  'call'
> & {
  call(...args: Parameters<IDiesisConductorsMethodObject<Mutability>['call']>): Promise<Output>;
};

export interface IDiesisConductorsMethods {
  finalizeDecrease(): IDiesisConductorsMethod<'nonpayable', void>;
  getConductor(conductor: string): IDiesisConductorsMethod<'nonpayable', { conductor: string; bond: bigint; tier: bigint; totalEarned: bigint; todayEarned: bigint; todayCapacityRemainingDs: bigint; bondAvailableAfterBlock: bigint; pendingRefund: bigint }>;
  registerOrTopup(): IDiesisConductorsMethod<'payable', void>;
  requestDecrease(amount: Numbers): IDiesisConductorsMethod<'nonpayable', void>;
}

export type IDiesisConductorsContract = Omit<Contract<typeof IDiesisConductorsAbi>, 'methods'> & {
  readonly methods: IDiesisConductorsMethods;
};

export function createIDiesisConductors(web3: Web3, address: string): IDiesisConductorsContract {
  return new Contract(IDiesisConductorsAbi, address, web3) as unknown as IDiesisConductorsContract;
}
