// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisSettlementAbi } from '../../generated/viem/IDiesisSettlement.abi.js';

export interface IDiesisSettlementContract {
  methods: {
    authorizeSessionKeyV2(sessionKey: string, actionScope: Numbers, validUntil: Numbers, maxNotionalOrSpend: Numbers, allowedMarketsMask: string): { send(options: { from: string }): Promise<unknown>; };
    availableBalance(user: string, token: string): { call(): Promise<bigint>; };
    cancelNonceWord(wordPos: Numbers): { send(options: { from: string }): Promise<unknown>; };
    cancelOrderNonce(nonce: Numbers): { send(options: { from: string }): Promise<unknown>; };
    creditRouterDeposit(user: string, token: string, amount: Numbers): { send(options: { from: string }): Promise<unknown>; };
    debitRouterWithdrawal(user: string, token: string, amount: Numbers): { send(options: { from: string }): Promise<unknown>; };
    deposit(token: string, amount: Numbers): { send(options: { from: string }): Promise<unknown>; };
    fundPerpBackstopV1(marketId: string, amount: Numbers, nonce: Numbers): { send(options: { from: string }): Promise<unknown>; };
    getTradingKeyAuth(owner: string, tradingKey: string): { call(): Promise<{ header: string; maxOrderNotional: bigint; allowedMarketsMask: string }>; };
    isNonceUsed(user: string, nonce: Numbers): { call(): Promise<boolean>; };
    registerTradingKey(tradingKey: string, validUntil: Numbers, maxOrderNotional: Numbers, allowedMarketsMask: string, canWithdraw: boolean): { send(options: { from: string }): Promise<unknown>; };
    revokeSessionKeyV2(sessionKey: string): { send(options: { from: string }): Promise<unknown>; };
    revokeTradingKey(tradingKey: string): { send(options: { from: string }): Promise<unknown>; };
    totalBalance(user: string, token: string): { call(): Promise<bigint>; };
    withdraw(token: string, amount: Numbers): { send(options: { from: string }): Promise<unknown>; };
  };
  events: {
    Deposit: { (options?: { filter?: { user?: string; token?: string } }): unknown; };
    NonceCancelled: { (options?: { filter?: { user?: string } }): unknown; };
    PerpBackstopFunded: { (options?: { filter?: { funder?: string; marketId?: string; quoteToken?: string } }): unknown; };
    TradingKeyRegistered: { (options?: { filter?: { owner?: string; tradingKey?: string } }): unknown; };
    TradingKeyRevoked: { (options?: { filter?: { owner?: string; tradingKey?: string } }): unknown; };
    Withdrawal: { (options?: { filter?: { user?: string; token?: string } }): unknown; };
  };
}

export function createIDiesisSettlement(web3: Web3, address: string): IDiesisSettlementContract {
  return new Contract(IDiesisSettlementAbi as any, address, web3) as unknown as IDiesisSettlementContract;
}
