// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisMarginAbi } from '../../generated/viem/IDiesisMargin.abi.js';

export interface IDiesisMarginContract {
  methods: {
    resolvePerpProtectionV1(marketId: string): { send(options: { from: string }): Promise<unknown>; };
  };
  events: {
    AutoDeleverage: { (options?: { filter?: { marketId?: string; deleveraged?: string; counterparty?: string } }): unknown; };
    Liquidation: { (options?: { filter?: { marketId?: string; trader?: string } }): unknown; };
  };
}

export function createIDiesisMargin(web3: Web3, address: string): IDiesisMarginContract {
  return new Contract(IDiesisMarginAbi as any, address, web3) as unknown as IDiesisMarginContract;
}
