// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisErc20FactoryAbi } from '../../generated/viem/IDiesisErc20Factory.abi.js';

export interface IDiesisErc20FactoryContract {
  methods: {
    deploy(params: { symbol: string; name: string; initialSupply: Numbers; deployer: string }): { send(options: { from: string }): Promise<unknown>; };
    executeTemplateUpdate(): { send(options: { from: string }): Promise<unknown>; };
    predictAddress(deployer: string, symbol: string): { call(): Promise<string>; };
    proposeTemplateUpdate(newHash: string): { send(options: { from: string }): Promise<unknown>; };
    templateBytecodeHash(): { call(): Promise<string>; };
  };
  events: {
    Erc20Deployed: { (options?: { filter?: { token?: string; deployer?: string; symbol?: string } }): unknown; };
    TemplateUpdated: { (options?: {}): unknown; };
  };
}

export function createIDiesisErc20Factory(web3: Web3, address: string): IDiesisErc20FactoryContract {
  return new Contract(IDiesisErc20FactoryAbi as any, address, web3) as unknown as IDiesisErc20FactoryContract;
}
