// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisReverseRegistrarAbi } from '../../generated/viem/IDiesisReverseRegistrar.abi.js';

type IDiesisReverseRegistrarMethodObject<Mutability extends 'payable' | 'nonpayable'> = ReturnType<
  Contract<
    readonly [
      {
        readonly type: 'function';
        readonly name: 'm';
        readonly stateMutability: Mutability;
        readonly inputs: readonly [];
        readonly outputs: readonly [];
      },
    ]
  >['methods']['m']
>;
type IDiesisReverseRegistrarMethod<Mutability extends 'payable' | 'nonpayable', Output> = Omit<
  IDiesisReverseRegistrarMethodObject<Mutability>,
  'call'
> & {
  call(...args: Parameters<IDiesisReverseRegistrarMethodObject<Mutability>['call']>): Promise<Output>;
};

export interface IDiesisReverseRegistrarMethods {
  controllers(controller: string): IDiesisReverseRegistrarMethod<'nonpayable', boolean>;
  name(addr: string): IDiesisReverseRegistrarMethod<'nonpayable', string>;
  node(addr: string): IDiesisReverseRegistrarMethod<'nonpayable', string>;
  setController(controller: string, approved: boolean): IDiesisReverseRegistrarMethod<'nonpayable', void>;
  setName(name_: string): IDiesisReverseRegistrarMethod<'nonpayable', string>;
  setNameForAddr(addr: string, name_: string): IDiesisReverseRegistrarMethod<'nonpayable', string>;
}

export type IDiesisReverseRegistrarContract = Omit<Contract<typeof IDiesisReverseRegistrarAbi>, 'methods'> & {
  readonly methods: IDiesisReverseRegistrarMethods;
};

export function createIDiesisReverseRegistrar(web3: Web3, address: string): IDiesisReverseRegistrarContract {
  return new Contract(IDiesisReverseRegistrarAbi, address, web3) as unknown as IDiesisReverseRegistrarContract;
}
