// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisConductorsAbi } from '../../generated/viem/IDiesisConductors.abi.js';

export interface IDiesisConductorsContract {
  methods: {
    finalizeDecrease(): { send(options: { from: string }): Promise<unknown>; };
    getConductor(conductor: string): { call(): Promise<{ conductor: string; bond: bigint; tier: bigint; totalEarned: bigint; todayEarned: bigint; todayCapacityRemainingDs: bigint; bondAvailableAfterBlock: bigint; pendingRefund: bigint }>; };
    registerOrTopup(): { send(options: { from: string; value?: Numbers }): Promise<unknown>; };
    requestDecrease(amount: Numbers): { send(options: { from: string }): Promise<unknown>; };
  };
  events: {
    DecreaseFinalized: { (options?: { filter?: { conductor?: string } }): unknown; };
    DecreaseRequested: { (options?: { filter?: { conductor?: string } }): unknown; };
    Registered: { (options?: { filter?: { conductor?: string } }): unknown; };
    ShareEarned: { (options?: { filter?: { conductor?: string } }): unknown; };
  };
}

export function createIDiesisConductors(web3: Web3, address: string): IDiesisConductorsContract {
  return new Contract(IDiesisConductorsAbi as any, address, web3) as unknown as IDiesisConductorsContract;
}
