// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisNamePolicyAbi } from '../../generated/viem/IDiesisNamePolicy.abi.js';

export interface IDiesisNamePolicyContract {
  methods: {
    approveRecovery(node: string, newOwner: string): { send(options: { from: string }): Promise<unknown>; };
    cancelRecovery(node: string, newOwner: string): { send(options: { from: string }): Promise<unknown>; };
    finalizeRecovery(node: string, newOwner: string): { send(options: { from: string }): Promise<unknown>; };
    guardedTransfer(node: string, newOwner: string): { send(options: { from: string }): Promise<unknown>; };
    guardians(node: string, guardian: string): { call(): Promise<boolean>; };
    isTransferLocked(node: string): { call(): Promise<boolean>; };
    recoveryDelay(node: string): { call(): Promise<bigint>; };
    recoveryEnabled(node: string): { call(): Promise<boolean>; };
    recoveryFallbackOwner(node: string): { call(): Promise<string>; };
    recoveryThreshold(node: string): { call(): Promise<bigint>; };
    setGuardian(node: string, guardian: string, approved: boolean): { send(options: { from: string }): Promise<unknown>; };
    setRecoveryConfig(node: string, threshold: Numbers, delay: Numbers, fallbackOwner: string, enabled: boolean): { send(options: { from: string }): Promise<unknown>; };
    setTransferLock(node: string, lockedUntil: Numbers): { send(options: { from: string }): Promise<unknown>; };
    transferLockUntil(node: string): { call(): Promise<bigint>; };
  };
  events: {
    GuardianChanged: { (options?: { filter?: { node?: string; guardian?: string } }): unknown; };
    NameRecovered: { (options?: { filter?: { node?: string; requestId?: string; newOwner?: string } }): unknown; };
    RecoveryApproved: { (options?: { filter?: { node?: string; requestId?: string; guardian?: string } }): unknown; };
    RecoveryCancelled: { (options?: { filter?: { node?: string; requestId?: string } }): unknown; };
    RecoveryConfigChanged: { (options?: { filter?: { node?: string } }): unknown; };
    TransferLockChanged: { (options?: { filter?: { node?: string } }): unknown; };
  };
}

export function createIDiesisNamePolicy(web3: Web3, address: string): IDiesisNamePolicyContract {
  return new Contract(IDiesisNamePolicyAbi as any, address, web3) as unknown as IDiesisNamePolicyContract;
}
