// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisNameVerifierAbi } from '../../generated/viem/IDiesisNameVerifier.abi.js';

type IDiesisNameVerifierMethodObject<Mutability extends 'payable' | 'nonpayable'> = ReturnType<
  Contract<
    readonly [
      {
        readonly type: 'function';
        readonly name: 'm';
        readonly stateMutability: Mutability;
        readonly inputs: readonly [];
        readonly outputs: readonly [];
      },
    ]
  >['methods']['m']
>;
type IDiesisNameVerifierMethod<Mutability extends 'payable' | 'nonpayable', Output> = Omit<
  IDiesisNameVerifierMethodObject<Mutability>,
  'call'
> & {
  call(...args: Parameters<IDiesisNameVerifierMethodObject<Mutability>['call']>): Promise<Output>;
};

export interface IDiesisNameVerifierMethods {
  attest(node: string, subject: string, kind: string, digest: string, expiresAt: Numbers): IDiesisNameVerifierMethod<'nonpayable', string>;
  attestationDigest(attestation: { node: string; attestationType: string; issuer: string; subjectHash: string; evidenceHash: string; issuedAt: Numbers; validUntil: Numbers; extraData: string }): IDiesisNameVerifierMethod<'nonpayable', string>;
  attestationHash(attestation: { node: string; attestationType: string; issuer: string; subjectHash: string; evidenceHash: string; issuedAt: Numbers; validUntil: Numbers; extraData: string }): IDiesisNameVerifierMethod<'nonpayable', string>;
  attestations(node: string, attestationType: string): IDiesisNameVerifierMethod<'nonpayable', string[]>;
  "attestations(bytes32,bytes32)"(node: string, attestationType: string): IDiesisNameVerifierMethod<'nonpayable', string[]>;
  attestations(attestationId: string): IDiesisNameVerifierMethod<'nonpayable', { node: string; subject: string; kind: string; digest: string; issuer: string; issuedAt: bigint; expiresAt: bigint; revoked: boolean }>;
  "attestations(bytes32)"(attestationId: string): IDiesisNameVerifierMethod<'nonpayable', { node: string; subject: string; kind: string; digest: string; issuer: string; issuedAt: bigint; expiresAt: bigint; revoked: boolean }>;
  isAttested(node: string, attestationType: string, issuer: string): IDiesisNameVerifierMethod<'nonpayable', boolean>;
  isValid(attestationId: string): IDiesisNameVerifierMethod<'nonpayable', boolean>;
  issuers(issuer: string): IDiesisNameVerifierMethod<'nonpayable', boolean>;
  revoke(attestationId: string): IDiesisNameVerifierMethod<'nonpayable', void>;
  revokeAttestation(node: string, attestationHash: string): IDiesisNameVerifierMethod<'nonpayable', void>;
  setIssuer(issuer: string, approved: boolean): IDiesisNameVerifierMethod<'nonpayable', void>;
  submitAttestation(attestation: { node: string; attestationType: string; issuer: string; subjectHash: string; evidenceHash: string; issuedAt: Numbers; validUntil: Numbers; extraData: string }, signature: string): IDiesisNameVerifierMethod<'nonpayable', void>;
}

export type IDiesisNameVerifierContract = Omit<Contract<typeof IDiesisNameVerifierAbi>, 'methods'> & {
  readonly methods: IDiesisNameVerifierMethods;
};

export function createIDiesisNameVerifier(web3: Web3, address: string): IDiesisNameVerifierContract {
  return new Contract(IDiesisNameVerifierAbi, address, web3) as unknown as IDiesisNameVerifierContract;
}
