// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IDiesisNameVerifierAbi } from '../../generated/viem/IDiesisNameVerifier.abi.js';

export interface IDiesisNameVerifierContract {
  methods: {
    attest(node: string, subject: string, kind: string, digest: string, expiresAt: Numbers): { send(options: { from: string }): Promise<unknown>; };
    attestationDigest(attestation: { node: string; attestationType: string; issuer: string; subjectHash: string; evidenceHash: string; issuedAt: Numbers; validUntil: Numbers; extraData: string }): { call(): Promise<string>; };
    attestationHash(attestation: { node: string; attestationType: string; issuer: string; subjectHash: string; evidenceHash: string; issuedAt: Numbers; validUntil: Numbers; extraData: string }): { call(): Promise<string>; };
    attestationsBytes32Bytes32(node: string, attestationType: string): { call(): Promise<string[]>; };
    attestationsBytes32(attestationId: string): { call(): Promise<{ node: string; subject: string; kind: string; digest: string; issuer: string; issuedAt: bigint; expiresAt: bigint; revoked: boolean }>; };
    isAttested(node: string, attestationType: string, issuer: string): { call(): Promise<boolean>; };
    isValid(attestationId: string): { call(): Promise<boolean>; };
    issuers(issuer: string): { call(): Promise<boolean>; };
    revoke(attestationId: string): { send(options: { from: string }): Promise<unknown>; };
    revokeAttestation(node: string, attestationHash: string): { send(options: { from: string }): Promise<unknown>; };
    setIssuer(issuer: string, approved: boolean): { send(options: { from: string }): Promise<unknown>; };
    submitAttestation(attestation: { node: string; attestationType: string; issuer: string; subjectHash: string; evidenceHash: string; issuedAt: Numbers; validUntil: Numbers; extraData: string }, signature: string): { send(options: { from: string }): Promise<unknown>; };
  };
  events: {
    AttestationRevoked: { (options?: { filter?: { node?: string; attestationHash?: string; issuer?: string } }): unknown; };
    AttestationSubmitted: { (options?: { filter?: { node?: string; attestationType?: string; issuer?: string } }): unknown; };
    Attested: { (options?: { filter?: { attestationId?: string; node?: string; subject?: string } }): unknown; };
    IssuerChanged: { (options?: { filter?: { issuer?: string } }): unknown; };
    Revoked: { (options?: { filter?: { attestationId?: string } }): unknown; };
  };
}

export function createIDiesisNameVerifier(web3: Web3, address: string): IDiesisNameVerifierContract {
  return new Contract(IDiesisNameVerifierAbi as any, address, web3) as unknown as IDiesisNameVerifierContract;
}
