// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IValidatorShareAbi } from '../../generated/viem/IValidatorShare.abi.js';

type IValidatorShareMethodObject<Mutability extends 'payable' | 'nonpayable'> = ReturnType<
  Contract<
    readonly [
      {
        readonly type: 'function';
        readonly name: 'm';
        readonly stateMutability: Mutability;
        readonly inputs: readonly [];
        readonly outputs: readonly [];
      },
    ]
  >['methods']['m']
>;
type IValidatorShareMethod<Mutability extends 'payable' | 'nonpayable', Output> = Omit<
  IValidatorShareMethodObject<Mutability>,
  'call'
> & {
  call(...args: Parameters<IValidatorShareMethodObject<Mutability>['call']>): Promise<Output>;
};

export interface IValidatorShareMethods {
  DIESIS_POSITION(): IValidatorShareMethod<'nonpayable', string>;
  MAX_LOTS_PER_REDEMPTION(): IValidatorShareMethod<'nonpayable', bigint>;
  MIN_BACKING_LOT(): IValidatorShareMethod<'nonpayable', bigint>;
  backingLot(validator: Numbers, slot: Numbers): IValidatorShareMethod<'nonpayable', { 0: bigint; 1: bigint; 2: bigint; 3: boolean; sourcePositionId: bigint; remaining: bigint; next: bigint; active: boolean; __length__: number }>;
  backingLotForPosition(validator: Numbers, sourcePositionId: Numbers): IValidatorShareMethod<'nonpayable', { 0: bigint; 1: bigint; 2: boolean; slot: bigint; remaining: bigint; active: boolean; __length__: number }>;
  backingPoolState(validator: Numbers): IValidatorShareMethod<'nonpayable', { 0: bigint; 1: bigint; 2: bigint; 3: bigint; head: bigint; tail: bigint; liveLots: bigint; backing: bigint; __length__: number }>;
  mintShares(positionTokenId: Numbers, shareAmount: Numbers): IValidatorShareMethod<'nonpayable', void>;
  pooledBacking(validator: Numbers): IValidatorShareMethod<'nonpayable', bigint>;
  redeemShares(receiverPositionId: Numbers, shareTokenId: Numbers, shareAmount: Numbers, maxLots: Numbers): IValidatorShareMethod<'nonpayable', void>;
  repayShares(sourcePositionId: Numbers, shareAmount: Numbers): IValidatorShareMethod<'nonpayable', void>;
  swapPositionBalance(fromTokenId: Numbers, toTokenId: Numbers, swapAmount: Numbers): IValidatorShareMethod<'nonpayable', void>;
  totalSupply(shareTokenId: Numbers): IValidatorShareMethod<'nonpayable', bigint>;
  validatorShareTokenId(validator: Numbers): IValidatorShareMethod<'nonpayable', bigint>;
}

export type IValidatorShareContract = Omit<Contract<typeof IValidatorShareAbi>, 'methods'> & {
  readonly methods: IValidatorShareMethods;
};

export function createIValidatorShare(web3: Web3, address: string): IValidatorShareContract {
  return new Contract(IValidatorShareAbi, address, web3) as unknown as IValidatorShareContract;
}
