// Auto-generated by abi-typegen. Do not edit manually.
import { Contract, type Numbers, type Web3 } from 'web3';
import { IWrappedDSAbi } from '../../generated/viem/IWrappedDS.abi.js';

export interface IWrappedDSContract {
  methods: {
    allowance(owner: string, spender: string): { call(): Promise<bigint>; };
    approve(spender: string, amount: Numbers): { send(options: { from: string }): Promise<unknown>; };
    balanceOf(account: string): { call(): Promise<bigint>; };
    decimals(): { call(): Promise<bigint>; };
    deposit(): { send(options: { from: string; value?: Numbers }): Promise<unknown>; };
    name(): { call(): Promise<string>; };
    symbol(): { call(): Promise<string>; };
    totalSupply(): { call(): Promise<bigint>; };
    transfer(to: string, amount: Numbers): { send(options: { from: string }): Promise<unknown>; };
    transferFrom(from: string, to: string, amount: Numbers): { send(options: { from: string }): Promise<unknown>; };
    withdraw(amount: Numbers): { send(options: { from: string }): Promise<unknown>; };
  };
  events: {
    Approval: { (options?: { filter?: { owner?: string; spender?: string } }): unknown; };
    Deposit: { (options?: { filter?: { dst?: string } }): unknown; };
    Transfer: { (options?: { filter?: { from?: string; to?: string } }): unknown; };
    Withdrawal: { (options?: { filter?: { src?: string } }): unknown; };
  };
}

export function createIWrappedDs(web3: Web3, address: string): IWrappedDSContract {
  return new Contract(IWrappedDSAbi as any, address, web3) as unknown as IWrappedDSContract;
}
