// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { DiesisPrivacyPoolsAbi } from '../../generated/viem/DiesisPrivacyPools.abi.js';

export interface DiesisPrivacyPoolsContract extends ethers.Contract {
  acceptOwnership(overrides?: Overrides): Promise<ethers.ContractTransaction>;
  artifactClass(overrides?: CallOverrides): Promise<string>;
  associationVerifier(overrides?: CallOverrides): Promise<string>;
  initialized(overrides?: CallOverrides): Promise<boolean>;
  owner(overrides?: CallOverrides): Promise<string>;
  pendingOwner(overrides?: CallOverrides): Promise<string>;
  providerCount(overrides?: CallOverrides): Promise<BigNumber>;
  providerList(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  providers(arg0: string, overrides?: CallOverrides): Promise<[string, boolean, string] & { name: string; registered: boolean; associationSetRoot: string }>;
  registerProvider(provider: string, name: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  transferOwnership(newOwner: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  updateAssociationSet(newRoot: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  verifyAssociation(proof: BytesLike, associationSetRoot: BytesLike, nullifier: BytesLike, provider: string, overrides?: CallOverrides): Promise<boolean>;
  filters: {
    AssociationSetUpdated(provider?: string | null): ethers.EventFilter;
    OwnershipTransferStarted(currentOwner?: string | null, pendingOwner?: string | null): ethers.EventFilter;
    OwnershipTransferred(previousOwner?: string | null, newOwner?: string | null): ethers.EventFilter;
    ProviderRegistered(provider?: string | null): ethers.EventFilter;
  };
}

export function connectDiesisPrivacyPools(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): DiesisPrivacyPoolsContract {
  const contract = new ethers.Contract(address, DiesisPrivacyPoolsAbi, signerOrProvider);
  return contract as unknown as DiesisPrivacyPoolsContract;
}
