// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { DiesisShieldedPoolAbi } from '../../generated/viem/DiesisShieldedPool.abi.js';

export interface DiesisShieldedPoolContract extends ethers.Contract {
  DENOMINATION(): Promise<BigNumber>;
  DEPTH(): Promise<BigNumber>;
  ENCRYPTED_NOTE_BYTES(): Promise<BigNumber>;
  MAX_LEAVES(): Promise<BigNumber>;
  ROOT_HISTORY_SIZE(): Promise<BigNumber>;
  artifactClass(): Promise<string>;
  commitmentSeen(arg0: BytesLike): Promise<boolean>;
  currentRootIndex(): Promise<BigNumber>;
  deposit(commitment: BytesLike, encryptedNote: BytesLike): Promise<ethers.ContractTransaction>;
  filledSubtrees(arg0: BigNumberish): Promise<string>;
  initialized(): Promise<boolean>;
  isKnownRoot(rootValue: BytesLike): Promise<boolean>;
  nextIndex(): Promise<BigNumber>;
  nullifiers(arg0: BytesLike): Promise<boolean>;
  outstandingNotes(): Promise<BigNumber>;
  root(): Promise<string>;
  rootHistory(arg0: BigNumberish): Promise<string>;
  rootReferenceCount(arg0: BytesLike): Promise<number>;
  transact(proof: BytesLike, merkleRoot: BytesLike, inputNullifiers: [BytesLike, BytesLike], outputCommitments: [BytesLike, BytesLike], activeCount: BigNumberish, encryptedOutputs: BytesLike): Promise<ethers.ContractTransaction>;
  transferVerifier(): Promise<string>;
  treeInitialized(): Promise<boolean>;
  withdraw(proof: BytesLike, merkleRoot: BytesLike, nullifier: BytesLike, recipient: string, relayer: string, fee: BigNumberish): Promise<ethers.ContractTransaction>;
  withdrawVerifier(): Promise<string>;
  zeros(arg0: BigNumberish): Promise<string>;
  filters: {
    DepositV1(commitment?: BytesLike | null, leafIndex?: BigNumberish | null): ethers.EventFilter;
    TransferV1(): ethers.EventFilter;
    WithdrawalV1(nullifier?: BytesLike | null, recipient?: string | null, relayer?: string | null): ethers.EventFilter;
  };
}

export function connectDiesisShieldedPool(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): DiesisShieldedPoolContract {
  const contract = new ethers.Contract(address, DiesisShieldedPoolAbi, signerOrProvider);
  return contract as unknown as DiesisShieldedPoolContract;
}
