// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { DiesisPatronAbi } from '../../generated/viem/DiesisPatron.abi.js';

export interface DiesisPatronContract extends ethers.Contract {
  accrueSettledBurnV2(blockNumber: BigNumberish, totalActualFee: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  accruedBurn(overrides?: CallOverrides): Promise<BigNumber>;
  assignAccountGrant(account: string, grantId: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  campaignIdFor(owner: string, salt: BytesLike, overrides?: CallOverrides): Promise<string>;
  campaignOwner(campaignId: BytesLike, overrides?: CallOverrides): Promise<string>;
  campaignRevoked(campaignId: BytesLike, overrides?: CallOverrides): Promise<boolean>;
  campaignVoucherDigest(voucher: { campaignId: BytesLike; beneficiary: string; target: string; selector: BytesLike; maxTransactions: BigNumberish; maxLifetimeSpend: BigNumberish; expiry: BigNumberish; nonce: BigNumberish }, overrides?: CallOverrides): Promise<string>;
  campaignVoucherUsed(campaignId: BytesLike, beneficiary: string, nonce: BigNumberish, overrides?: CallOverrides): Promise<boolean>;
  cancelGrantV2(reservationId: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  claimCampaignVoucherV1(voucher: { campaignId: BytesLike; beneficiary: string; target: string; selector: BytesLike; maxTransactions: BigNumberish; maxLifetimeSpend: BigNumberish; expiry: BigNumberish; nonce: BigNumberish }, signature: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  contribute(grantId: BytesLike, overrides?: PayableOverrides): Promise<ethers.ContractTransaction>;
  flushBurn(overrides?: Overrides): Promise<ethers.ContractTransaction>;
  grantAuthorizations(arg0: string, arg1: BytesLike, overrides?: CallOverrides): Promise<[string, string, BigNumber, number, number, BigNumber, BigNumber] & { target: string; selector: string; expiry: BigNumber; maxTransactions: number; transactionsUsed: number; maxLifetimeSpend: BigNumber; lifetimeSpent: BigNumber }>;
  grantGasOverhead(overrides?: CallOverrides): Promise<[BigNumber, BigNumber, BigNumber] & { reserveGas: BigNumber; settleGas: BigNumber; totalOverhead: BigNumber }>;
  grantIdForAccount(account: string, overrides?: CallOverrides): Promise<string>;
  grantIdForCampaign(campaignId: BytesLike, overrides?: CallOverrides): Promise<string>;
  grantIdForReferral(referrer: string, referred: string, overrides?: CallOverrides): Promise<string>;
  grantIdForWelcome(overrides?: CallOverrides): Promise<string>;
  grantInfo(grantId: BytesLike, overrides?: CallOverrides): Promise<[BigNumber, BigNumber, BigNumber] & { balance: BigNumber; totalContributed: BigNumber; totalSpent: BigNumber }>;
  grants(arg0: BytesLike, overrides?: CallOverrides): Promise<[BigNumber, BigNumber, BigNumber] & { balance: BigNumber; totalContributed: BigNumber; totalSpent: BigNumber }>;
  lastAccruedBlock(overrides?: CallOverrides): Promise<BigNumber>;
  maxActiveReservationsPerGrant(overrides?: CallOverrides): Promise<BigNumber>;
  outstandingReservationExitClaims(overrides?: CallOverrides): Promise<BigNumber>;
  owner(overrides?: CallOverrides): Promise<string>;
  paused(overrides?: CallOverrides): Promise<boolean>;
  pendingReservations(reservationId: BytesLike, overrides?: CallOverrides): Promise<[string, string, BigNumber] & { grantId: string; beneficiary: string; maximumFee: BigNumber }>;
  registerCampaignV1(salt: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  renounceOwnership(overrides?: Overrides): Promise<ethers.ContractTransaction>;
  reservationExitSettlement(reservationId: BytesLike, overrides?: CallOverrides): Promise<[string, BigNumber, BigNumber, BigNumber, BigNumber] & { grantId: string; totalRefund: BigNumber; totalDetachedShares: BigNumber; remainingDetachedShares: BigNumber; remainingEscrow: BigNumber }>;
  reservationExitSnapshot(reservationId: BytesLike, contributor: string, overrides?: CallOverrides): Promise<[BigNumber, boolean, boolean] & { detachedShares: BigNumber; claimed: boolean; snapshotted: boolean }>;
  reserveGrantGasLimit(overrides?: CallOverrides): Promise<BigNumber>;
  reserveGrantV2(reservationId: BytesLike, sender: string, target: string, input: BytesLike, maximumFee: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  resolveGrant(sender: string, target: string, input: BytesLike, fee: BigNumberish, overrides?: CallOverrides): Promise<string>;
  resolveGrantContext(sender: string, target: string, input: BytesLike, fee: BigNumberish, overrides?: CallOverrides): Promise<[string, BigNumber, number, number, BigNumber, BigNumber] & { grantId: string; jarBalance: BigNumber; maxTransactions: number; transactionsUsed: number; maxLifetimeSpend: BigNumber; lifetimeSpent: BigNumber }>;
  revokeCampaignVoucherV1(campaignId: BytesLike, beneficiary: string, nonce: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  revokeGrantAuthorization(beneficiary: string, grantId: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  rotateCampaignOwnerV1(campaignId: BytesLike, newOwner: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  setCampaignRevokedV1(campaignId: BytesLike, revoked: boolean, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  setGrantAuthorization(beneficiary: string, grantId: BytesLike, target: string, selector: BytesLike, maxTransactions: BigNumberish, maxLifetimeSpend: BigNumberish, expiry: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  setPaused(paused_: boolean, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  setReferral(referred: string, referrer: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  settleGrantGasLimit(overrides?: CallOverrides): Promise<BigNumber>;
  settleGrantV2(reservationId: BytesLike, actualFee: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  stakingAddress(overrides?: CallOverrides): Promise<string>;
  transferOwnership(newOwner: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  updateGasLimits(reserveGas: BigNumberish, settleGas: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  updateStakingAddress(staking_: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  withdrawContribution(grantId: BytesLike, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  withdrawReservationExit(reservationId: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  filters: {
    AccountGrantAssigned(account?: string | null, grantId?: BytesLike | null): ethers.EventFilter;
    BurnFlushFailed(staking?: string | null): ethers.EventFilter;
    BurnFlushed(staking?: string | null): ethers.EventFilter;
    CampaignOwnerRotated(campaignId?: BytesLike | null, previousOwner?: string | null, newOwner?: string | null): ethers.EventFilter;
    CampaignRegistered(campaignId?: BytesLike | null, owner?: string | null): ethers.EventFilter;
    CampaignRevocationSet(campaignId?: BytesLike | null): ethers.EventFilter;
    CampaignVoucherClaimed(campaignId?: BytesLike | null, beneficiary?: string | null): ethers.EventFilter;
    CampaignVoucherRevoked(campaignId?: BytesLike | null, beneficiary?: string | null): ethers.EventFilter;
    GrantAuthorizationRevoked(beneficiary?: string | null, grantId?: BytesLike | null): ethers.EventFilter;
    GrantAuthorizationSet(beneficiary?: string | null, grantId?: BytesLike | null, target?: string | null): ethers.EventFilter;
    GrantContributed(grantId?: BytesLike | null, contributor?: string | null): ethers.EventFilter;
    GrantGasLimitsUpdated(): ethers.EventFilter;
    GrantReservationCancelled(reservationId?: BytesLike | null, grantId?: BytesLike | null): ethers.EventFilter;
    GrantReserved(reservationId?: BytesLike | null, grantId?: BytesLike | null, beneficiary?: string | null): ethers.EventFilter;
    GrantSettled(reservationId?: BytesLike | null, grantId?: BytesLike | null): ethers.EventFilter;
    GrantWithdrawn(grantId?: BytesLike | null, contributor?: string | null): ethers.EventFilter;
    OwnershipTransferred(previousOwner?: string | null, newOwner?: string | null): ethers.EventFilter;
    Paused(): ethers.EventFilter;
    ReferralGrantSet(referrer?: string | null, referred?: string | null): ethers.EventFilter;
    ReservationExitSnapshotted(reservationId?: BytesLike | null, grantId?: BytesLike | null, contributor?: string | null): ethers.EventFilter;
    ReservationExitWithdrawn(reservationId?: BytesLike | null, grantId?: BytesLike | null, contributor?: string | null): ethers.EventFilter;
    SettledBurnAccrued(blockNumber?: BigNumberish | null): ethers.EventFilter;
    StakingAddressUpdated(newAddress?: string | null): ethers.EventFilter;
  };
}

export function connectDiesisPatron(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): DiesisPatronContract {
  const contract = new ethers.Contract(address, DiesisPatronAbi, signerOrProvider);
  return contract as unknown as DiesisPatronContract;
}
