// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { DiesisConfigAbi } from '../../generated/viem/DiesisConfig.abi.js';

export interface DiesisConfigContract extends ethers.Contract {
  CUT_RATE_UPPER(): Promise<BigNumber>;
  DEFAULT_DELEGATION_FANOUT_LIMIT(): Promise<BigNumber>;
  DEFAULT_EXIT_DELAY_CHECKPOINTS(): Promise<BigNumber>;
  DEFAULT_EXIT_DELAY_SECONDS(): Promise<BigNumber>;
  DEFAULT_LIVENESS_DOWNTIME_LIMIT(): Promise<BigNumber>;
  DEFAULT_LIVENESS_MISSED_BLOCK_LIMIT(): Promise<BigNumber>;
  DEFAULT_NETWORK_BURN_CUT(): Promise<BigNumber>;
  DEFAULT_OPERATOR_TAKE_RATE(): Promise<BigNumber>;
  DEFAULT_RELIABILITY_FLOOR(): Promise<BigNumber>;
  DEFAULT_RELIABILITY_SAMPLE_CHECKPOINTS(): Promise<number>;
  DEFAULT_REWARD_STREAM_PER_SECOND(): Promise<BigNumber>;
  DEFAULT_SURPLUS_REWARD_BURN_CUT(): Promise<BigNumber>;
  DEFAULT_TREASURY_CUT(): Promise<BigNumber>;
  DEFAULT_VALIDATOR_BOND_FLOOR(): Promise<BigNumber>;
  DELEGATION_FANOUT_LIMIT_LOWER(): Promise<BigNumber>;
  DELEGATION_FANOUT_LIMIT_UPPER(): Promise<BigNumber>;
  EXIT_DELAY_CHECKPOINTS_LOWER(): Promise<BigNumber>;
  EXIT_DELAY_CHECKPOINTS_UPPER(): Promise<BigNumber>;
  EXIT_DELAY_SECONDS_LOWER(): Promise<BigNumber>;
  EXIT_DELAY_SECONDS_UPPER(): Promise<BigNumber>;
  LIVENESS_DOWNTIME_LIMIT_LOWER(): Promise<BigNumber>;
  LIVENESS_DOWNTIME_LIMIT_UPPER(): Promise<BigNumber>;
  LIVENESS_MISSED_BLOCK_LIMIT_LOWER(): Promise<BigNumber>;
  LIVENESS_MISSED_BLOCK_LIMIT_UPPER(): Promise<BigNumber>;
  OPERATOR_TAKE_RATE_UPPER(): Promise<BigNumber>;
  RELIABILITY_FLOOR_UPPER(): Promise<BigNumber>;
  RELIABILITY_SAMPLE_LOWER(): Promise<number>;
  RELIABILITY_SAMPLE_UPPER(): Promise<number>;
  REWARD_STREAM_PER_SECOND_UPPER(): Promise<BigNumber>;
  SURPLUS_REWARD_BURN_CUT_UPPER(): Promise<BigNumber>;
  VALIDATOR_BOND_FLOOR_LOWER(): Promise<BigNumber>;
  VALIDATOR_BOND_FLOOR_UPPER(): Promise<BigNumber>;
  delegationFanoutLimit(): Promise<BigNumber>;
  exitDelayCheckpoints(): Promise<BigNumber>;
  exitDelaySeconds(): Promise<BigNumber>;
  livenessDowntimeLimit(): Promise<BigNumber>;
  livenessMissedBlockLimit(): Promise<BigNumber>;
  mintReceiver(): Promise<string>;
  networkBurnCut(): Promise<BigNumber>;
  operatorTakeRate(): Promise<BigNumber>;
  owner(): Promise<string>;
  reliabilityFloor(): Promise<BigNumber>;
  reliabilitySampleCheckpoints(): Promise<number>;
  renounceOwnership(): Promise<ethers.ContractTransaction>;
  rewardStreamPerSecond(): Promise<BigNumber>;
  setDelegationFanoutLimit(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setExitDelayCheckpoints(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setExitDelaySeconds(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setLivenessDowntimeLimit(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setLivenessMissedBlockLimit(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setMintReceiver(v: string): Promise<ethers.ContractTransaction>;
  setNetworkBurnCut(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setOperatorTakeRate(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setReliabilityFloor(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setReliabilitySampleCheckpoints(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setRewardStreamPerSecond(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setSurplusRewardBurnCut(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setTreasuryCut(v: BigNumberish): Promise<ethers.ContractTransaction>;
  setValidatorBondFloor(v: BigNumberish): Promise<ethers.ContractTransaction>;
  surplusRewardBurnCut(): Promise<BigNumber>;
  transferOwnership(newOwner: string): Promise<ethers.ContractTransaction>;
  treasuryCut(): Promise<BigNumber>;
  validatorBondFloor(): Promise<BigNumber>;
  filters: {
    DelegationFanoutLimitUpdated(): ethers.EventFilter;
    ExitDelayCheckpointsUpdated(): ethers.EventFilter;
    ExitDelaySecondsUpdated(): ethers.EventFilter;
    LivenessDowntimeLimitUpdated(): ethers.EventFilter;
    LivenessMissedBlockLimitUpdated(): ethers.EventFilter;
    MintReceiverUpdated(value?: string | null): ethers.EventFilter;
    NetworkBurnCutUpdated(): ethers.EventFilter;
    OperatorTakeRateUpdated(): ethers.EventFilter;
    OwnershipTransferred(previousOwner?: string | null, newOwner?: string | null): ethers.EventFilter;
    ReliabilityFloorUpdated(): ethers.EventFilter;
    ReliabilitySampleCheckpointsUpdated(): ethers.EventFilter;
    RewardStreamPerSecondUpdated(): ethers.EventFilter;
    SurplusRewardBurnCutUpdated(): ethers.EventFilter;
    TreasuryCutUpdated(): ethers.EventFilter;
    ValidatorBondFloorUpdated(): ethers.EventFilter;
  };
}

export function connectDiesisConfig(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): DiesisConfigContract {
  const contract = new ethers.Contract(address, DiesisConfigAbi, signerOrProvider);
  return contract as unknown as DiesisConfigContract;
}
