// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { DiesisBaseRegistrarAbi } from '../../generated/viem/DiesisBaseRegistrar.abi.js';

export interface DiesisBaseRegistrarContract extends ethers.Contract {
  DEFAULT_YEAR_PRICE(): Promise<BigNumber>;
  DS_NODE(): Promise<string>;
  FOUR_CHAR_YEAR_PRICE(): Promise<BigNumber>;
  GRACE_PERIOD(): Promise<BigNumber>;
  MAX_COMMITMENT_AGE(): Promise<BigNumber>;
  MAX_REGISTRATION_DURATION(): Promise<BigNumber>;
  MIN_COMMITMENT_AGE(): Promise<BigNumber>;
  MIN_REGISTRATION_DURATION(): Promise<BigNumber>;
  PREMIUM_PERIOD(): Promise<BigNumber>;
  START_PREMIUM(): Promise<BigNumber>;
  THREE_CHAR_YEAR_PRICE(): Promise<BigNumber>;
  available(label: string): Promise<boolean>;
  burnShare(): Promise<BigNumber>;
  burnSink(): Promise<string>;
  commit(commitment: BytesLike): Promise<ethers.ContractTransaction>;
  commitmentAge(commitment: BytesLike): Promise<BigNumber>;
  commitments(commitment: BytesLike): Promise<BigNumber>;
  currentPremium(label: string): Promise<BigNumber>;
  defaultYearPrice(): Promise<BigNumber>;
  fourCharYearPrice(): Promise<BigNumber>;
  gracePeriod(): Promise<BigNumber>;
  maintenance(): Promise<string>;
  maintenanceShare(): Promise<BigNumber>;
  makeCommitment(label: string, owner_: string, resolver_: string, recordsHash: BytesLike, duration: BigNumberish, secret: BytesLike, reverseRecord: boolean, nonce: BigNumberish): Promise<string>;
  maxCommitmentAge(): Promise<BigNumber>;
  maxRegistrationDuration(): Promise<BigNumber>;
  minCommitmentAge(): Promise<BigNumber>;
  minRegistrationDuration(): Promise<BigNumber>;
  nameExpires(labelhash: BytesLike): Promise<BigNumber>;
  normalizeLabel(label: string): Promise<string>;
  owner(): Promise<string>;
  premiumPeriod(): Promise<BigNumber>;
  register(label: string, owner_: string, resolver_: string, duration: BigNumberish, secret: BytesLike, reverseRecord: boolean, nonce: BigNumberish, resolverCalls: BytesLike[]): Promise<ethers.ContractTransaction>;
  registry(): Promise<string>;
  renew(label: string, duration: BigNumberish): Promise<ethers.ContractTransaction>;
  renounceOwnership(): Promise<ethers.ContractTransaction>;
  rentPrice(label: string, duration: BigNumberish): Promise<BigNumber>;
  reservedLabels(labelhash: BytesLike): Promise<boolean>;
  reverseRegistrar(): Promise<string>;
  setFeeSplit(burnShare_: BigNumberish, treasuryShare_: BigNumberish, maintenanceShare_: BigNumberish): Promise<ethers.ContractTransaction>;
  setPricing(threeCharYearPrice_: BigNumberish, fourCharYearPrice_: BigNumberish, defaultYearPrice_: BigNumberish, startPremium_: BigNumberish): Promise<ethers.ContractTransaction>;
  setReservedLabel(label: string, reserved: boolean): Promise<ethers.ContractTransaction>;
  setReverseRegistrar(reverseRegistrar_: string): Promise<ethers.ContractTransaction>;
  setTiming(minCommitmentAge_: BigNumberish, maxCommitmentAge_: BigNumberish, minRegistrationDuration_: BigNumberish, maxRegistrationDuration_: BigNumberish, gracePeriod_: BigNumberish, premiumPeriod_: BigNumberish): Promise<ethers.ContractTransaction>;
  startPremium(): Promise<BigNumber>;
  threeCharYearPrice(): Promise<BigNumber>;
  transferOwnership(newOwner: string): Promise<ethers.ContractTransaction>;
  treasury(): Promise<string>;
  treasuryShare(): Promise<BigNumber>;
  usedCommitments(commitment: BytesLike): Promise<boolean>;
  filters: {
    FeeSplitUpdated(): ethers.EventFilter;
    NameCommitted(commitment?: BytesLike | null): ethers.EventFilter;
    NameRegistered(labelhash?: BytesLike | null, node?: BytesLike | null, label?: null, owner?: string | null): ethers.EventFilter;
    NameRenewed(labelhash?: BytesLike | null): ethers.EventFilter;
    NameReserved(labelhash?: BytesLike | null): ethers.EventFilter;
    OwnershipTransferred(previousOwner?: string | null, newOwner?: string | null): ethers.EventFilter;
    PricingUpdated(): ethers.EventFilter;
    RentPaid(labelhash?: BytesLike | null): ethers.EventFilter;
    ReverseRegistrarChanged(reverseRegistrar?: string | null): ethers.EventFilter;
    TimingUpdated(): ethers.EventFilter;
  };
}

export function connectDiesisBaseRegistrar(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): DiesisBaseRegistrarContract {
  const contract = new ethers.Contract(address, DiesisBaseRegistrarAbi, signerOrProvider);
  return contract as unknown as DiesisBaseRegistrarContract;
}
