// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { IDiesisBuybackBurnAbi } from '../../generated/viem/IDiesisBuybackBurn.abi.js';

export interface IDiesisBuybackBurnContract extends ethers.Contract {
  cumulativeBurnedDs(): Promise<BigNumber>;
  lastTwapAveragePrice(token: string): Promise<BigNumber>;
  nextWindowStartBlock(token: string): Promise<BigNumber>;
  pendingPurchaseByAsset(token: string): Promise<BigNumber>;
  windowState(token: string): Promise<[BigNumber, BigNumber, BigNumber, number, number, BigNumber, BigNumber] & { windowStartBlock: BigNumber; windowEndBlock: BigNumber; windowLengthBlocks: BigNumber; chunksTotal: number; chunksRemaining: number; initialPending: BigNumber; twapAveragePrice: BigNumber }>;
  filters: {
    AssetApproved(token?: string | null): ethers.EventFilter;
    BurnChunk(token?: string | null): ethers.EventFilter;
    DsBurned(): ethers.EventFilter;
  };
}

export function connectIDiesisBuybackBurn(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisBuybackBurnContract {
  const contract = new ethers.Contract(address, IDiesisBuybackBurnAbi, signerOrProvider);
  return contract as unknown as IDiesisBuybackBurnContract;
}
