// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { IDiesisOperatorBondAbi } from '../../generated/viem/IDiesisOperatorBond.abi.js';

export interface IDiesisOperatorBondContract extends ethers.Contract {
  finalizeRelease(marketId: BytesLike): Promise<ethers.ContractTransaction>;
  getBond(marketId: BytesLike): Promise<[string, string, BigNumber, BigNumber] & { operator: string; marketId: string; bondDs: BigNumber; releaseUnlockBlock: BigNumber }>;
  postBond(marketId: BytesLike): Promise<ethers.ContractTransaction>;
  requestRelease(marketId: BytesLike): Promise<ethers.ContractTransaction>;
  filters: {
    BondPosted(operator?: string | null, marketId?: BytesLike | null): ethers.EventFilter;
    BondSlashed(marketId?: BytesLike | null): ethers.EventFilter;
    ReleaseFinalized(marketId?: BytesLike | null): ethers.EventFilter;
    ReleaseRequested(marketId?: BytesLike | null): ethers.EventFilter;
  };
}

export function connectIDiesisOperatorBond(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisOperatorBondContract {
  const contract = new ethers.Contract(address, IDiesisOperatorBondAbi, signerOrProvider);
  return contract as unknown as IDiesisOperatorBondContract;
}
