// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { IDiesisNamePolicyAbi } from '../../generated/viem/IDiesisNamePolicy.abi.js';

export interface IDiesisNamePolicyContract extends ethers.Contract {
  approveRecovery(node: BytesLike, newOwner: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  cancelRecovery(node: BytesLike, newOwner: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  finalizeRecovery(node: BytesLike, newOwner: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  guardedTransfer(node: BytesLike, newOwner: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  guardians(node: BytesLike, guardian: string, overrides?: CallOverrides): Promise<boolean>;
  isTransferLocked(node: BytesLike, overrides?: CallOverrides): Promise<boolean>;
  recoveryDelay(node: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  recoveryEnabled(node: BytesLike, overrides?: CallOverrides): Promise<boolean>;
  recoveryFallbackOwner(node: BytesLike, overrides?: CallOverrides): Promise<string>;
  recoveryThreshold(node: BytesLike, overrides?: CallOverrides): Promise<number>;
  setGuardian(node: BytesLike, guardian: string, approved: boolean, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  setRecoveryConfig(node: BytesLike, threshold: BigNumberish, delay: BigNumberish, fallbackOwner: string, enabled: boolean, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  setTransferLock(node: BytesLike, lockedUntil: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  transferLockUntil(node: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  filters: {
    GuardianChanged(node?: BytesLike | null, guardian?: string | null): ethers.EventFilter;
    NameRecovered(node?: BytesLike | null, requestId?: BytesLike | null, newOwner?: string | null): ethers.EventFilter;
    RecoveryApproved(node?: BytesLike | null, requestId?: BytesLike | null, guardian?: string | null): ethers.EventFilter;
    RecoveryCancelled(node?: BytesLike | null, requestId?: BytesLike | null): ethers.EventFilter;
    RecoveryConfigChanged(node?: BytesLike | null): ethers.EventFilter;
    TransferLockChanged(node?: BytesLike | null): ethers.EventFilter;
  };
}

export function connectIDiesisNamePolicy(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisNamePolicyContract {
  const contract = new ethers.Contract(address, IDiesisNamePolicyAbi, signerOrProvider);
  return contract as unknown as IDiesisNamePolicyContract;
}
