// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { IDiesisPerpsBookAbi } from '../../generated/viem/IDiesisPerpsBook.abi.js';

export interface IDiesisPerpsBookContract extends ethers.Contract {
  adjustIsolatedMargin(marketId: BytesLike, marginDelta: BigNumberish): Promise<ethers.ContractTransaction>;
  amendPerpOrderV1(orderId: BytesLike, price: BigNumberish, amount: BigNumberish, expiry: BigNumberish): Promise<ethers.ContractTransaction>;
  applyPerpFundingV1(marketId: BytesLike, fundingRateBps: BigNumberish): Promise<ethers.ContractTransaction>;
  cancelPerpOrderV1(orderId: BytesLike): Promise<ethers.ContractTransaction>;
  executePerpTradeV1(makerOrderId: BytesLike, takerOrderId: BytesLike, fillPrice: BigNumberish, fillQty: BigNumberish): Promise<ethers.ContractTransaction>;
  expirePerpOrderV1(orderId: BytesLike): Promise<ethers.ContractTransaction>;
  finalizePerpFeeEpochV2(marketId: BytesLike, epoch: BigNumberish, snapshotHash: BytesLike): Promise<ethers.ContractTransaction>;
  getIsolatedMargin(trader: string, marketId: BytesLike): Promise<BigNumber>;
  getPosition(trader: string, marketId: BytesLike): Promise<[string, BigNumber, BigNumber] & { header: string; size: BigNumber; entryPrice: BigNumber }>;
  submitExchangeActionsV2(encodedActions: BytesLike): Promise<ethers.ContractTransaction>;
  submitPerpOrderV1(marketId: BytesLike, side: BigNumberish, orderType: BigNumberish, price: BigNumberish, amount: BigNumberish, flags: BigNumberish, marginType: BigNumberish, expiry: BigNumberish): Promise<ethers.ContractTransaction>;
  submitSignedPerpActionsV2(signedEnvelope: BytesLike): Promise<ethers.ContractTransaction>;
  updatePerpMarkV1(marketId: BytesLike, markPrice: BigNumberish): Promise<ethers.ContractTransaction>;
  updatePerpOracleV1(marketId: BytesLike, indexPrice: BigNumberish, markPrice: BigNumberish, observedAt: BigNumberish, oracleRound: BigNumberish, sourceSetHash: BytesLike, evidenceHash: BytesLike): Promise<ethers.ContractTransaction>;
  filters: {
    ExchangeActionAcceptedV2(clientActionId?: BytesLike | null, actionIndex?: BigNumberish | null, actionTag?: null, marketId?: BytesLike | null): ethers.EventFilter;
    ExchangeActionRejectedV2(clientActionId?: BytesLike | null, actionIndex?: BigNumberish | null, actionTag?: null, marketId?: BytesLike | null): ethers.EventFilter;
    ExchangeL3MutationV2(marketId?: BytesLike | null, orderId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    FundingApplied(marketId?: BytesLike | null): ethers.EventFilter;
    IsolatedMarginAdjusted(marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    MarkPriceUpdated(marketId?: BytesLike | null): ethers.EventFilter;
    OrderCancelled(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    OrderFilled(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    OrderPlaced(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    PositionClosed(marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
  };
}

export function connectIDiesisPerpsBook(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisPerpsBookContract {
  const contract = new ethers.Contract(address, IDiesisPerpsBookAbi, signerOrProvider);
  return contract as unknown as IDiesisPerpsBookContract;
}
