// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { IDiesisReverseRegistrarAbi } from '../../generated/viem/IDiesisReverseRegistrar.abi.js';

export interface IDiesisReverseRegistrarContract extends ethers.Contract {
  controllers(controller: string, overrides?: CallOverrides): Promise<boolean>;
  name(addr: string, overrides?: CallOverrides): Promise<string>;
  node(addr: string, overrides?: CallOverrides): Promise<string>;
  setController(controller: string, approved: boolean, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  setName(name_: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  setNameForAddr(addr: string, name_: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  filters: {
    ControllerChanged(controller?: string | null): ethers.EventFilter;
    ReverseNameChanged(addr?: string | null): ethers.EventFilter;
  };
}

export function connectIDiesisReverseRegistrar(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisReverseRegistrarContract {
  const contract = new ethers.Contract(address, IDiesisReverseRegistrarAbi, signerOrProvider);
  return contract as unknown as IDiesisReverseRegistrarContract;
}
