// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { IDiesisPositionAbi } from '../../generated/viem/IDiesisPosition.abi.js';

export interface IDiesisPositionContract extends ethers.Contract {
  approve(to: string, tokenId: BigNumberish): Promise<ethers.ContractTransaction>;
  balanceOf(owner: string): Promise<BigNumber>;
  claimRewards(tokenId: BigNumberish, recipient: string): Promise<ethers.ContractTransaction>;
  delegate(tokenId: BigNumberish): Promise<ethers.ContractTransaction>;
  effectiveLockUntil(tokenId: BigNumberish): Promise<number>;
  freeCollateralOf(tokenId: BigNumberish): Promise<BigNumber>;
  getApproved(tokenId: BigNumberish): Promise<string>;
  hasLockCapacity(tokenId: BigNumberish, manager: string, lockId: BytesLike): Promise<boolean>;
  isApprovedForAll(owner: string, operator: string): Promise<boolean>;
  isFunctionApproved(tokenId: BigNumberish, fn: BigNumberish, caller: string): Promise<boolean>;
  lockPosition(tokenId: BigNumberish, lockDuration: BigNumberish): Promise<ethers.ContractTransaction>;
  lockPositionFor(tokenId: BigNumberish, lockId: BytesLike, lockDuration: BigNumberish): Promise<ethers.ContractTransaction>;
  lockRecordAt(tokenId: BigNumberish, index: BigNumberish): Promise<[string, string, number] & { manager: string; lockId: string; lockedUntil: number }>;
  lockRecordCount(tokenId: BigNumberish): Promise<BigNumber>;
  lockUntilFor(tokenId: BigNumberish, manager: string, lockId: BytesLike): Promise<number>;
  mergePosition(fromTokenId: BigNumberish, intoTokenId: BigNumberish): Promise<ethers.ContractTransaction>;
  mint(validator: BigNumberish): Promise<ethers.ContractTransaction>;
  mintLiquidToken(tokenId: BigNumberish, mintAmount: BigNumberish, recipient: string): Promise<ethers.ContractTransaction>;
  mintShareDebt(tokenId: BigNumberish, shareDebt: BigNumberish): Promise<ethers.ContractTransaction>;
  ownerOf(tokenId: BigNumberish): Promise<string>;
  positionInfo(tokenId: BigNumberish): Promise<[BigNumber, BigNumber, BigNumber, number, BigNumber[]] & { debtAmount: BigNumber; lifetimeDelegated: BigNumber; lifetimeRewardsClaimed: BigNumber; lockedUntil: number; pendingWithdrawals: BigNumber[] }>;
  redeemShareBacking(fromTokenId: BigNumberish, toTokenId: BigNumberish, shareAmount: BigNumberish): Promise<ethers.ContractTransaction>;
  repayLiquidToken(tokenId: BigNumberish, burnAmount: BigNumberish): Promise<ethers.ContractTransaction>;
  restakeRewards(tokenId: BigNumberish): Promise<ethers.ContractTransaction>;
  revokeFunctionApproval(tokenId: BigNumberish, fn: BigNumberish): Promise<ethers.ContractTransaction>;
  safeTransferFromAddressAddressUint256(from: string, to: string, tokenId: BigNumberish): Promise<ethers.ContractTransaction>;
  safeTransferFromAddressAddressUint256Bytes(from: string, to: string, tokenId: BigNumberish, data: BytesLike): Promise<ethers.ContractTransaction>;
  setApprovalForAll(operator: string, approved: boolean): Promise<ethers.ContractTransaction>;
  setFunctionApproval(tokenId: BigNumberish, fn: BigNumberish, delegatee: string, expires: BigNumberish, revokable: boolean): Promise<ethers.ContractTransaction>;
  shareDebtOf(tokenId: BigNumberish): Promise<BigNumber>;
  splitPosition(fromTokenId: BigNumberish, splitAmount: BigNumberish): Promise<ethers.ContractTransaction>;
  stakedAmountOf(tokenId: BigNumberish): Promise<BigNumber>;
  supportsInterface(interfaceId: BytesLike): Promise<boolean>;
  swapDelegate(fromTokenId: BigNumberish, toTokenId: BigNumberish, swapAmount: BigNumberish): Promise<ethers.ContractTransaction>;
  totalDebtOf(tokenId: BigNumberish): Promise<BigNumber>;
  totalStakedByValidator(validator: BigNumberish): Promise<BigNumber>;
  transferFrom(from: string, to: string, tokenId: BigNumberish): Promise<ethers.ContractTransaction>;
  undelegate(tokenId: BigNumberish, wrId: BigNumberish, undelegateAmount: BigNumberish): Promise<ethers.ContractTransaction>;
  unlockPosition(tokenId: BigNumberish, lockId: BytesLike): Promise<ethers.ContractTransaction>;
  validatorOf(tokenId: BigNumberish): Promise<number>;
  withdraw(tokenId: BigNumberish, wrId: BigNumberish): Promise<ethers.ContractTransaction>;
  withdrawTo(tokenId: BigNumberish, wrId: BigNumberish, recipient: string): Promise<ethers.ContractTransaction>;
  filters: {
    Approval(owner?: string | null, approved?: string | null, tokenId?: BigNumberish | null): ethers.EventFilter;
    ApprovalForAll(owner?: string | null, operator?: string | null): ethers.EventFilter;
    Delegated(tokenId?: BigNumberish | null, validator?: BigNumberish | null): ethers.EventFilter;
    FunctionApprovalRevoked(tokenId?: BigNumberish | null, fn?: BigNumberish | null): ethers.EventFilter;
    FunctionApprovalSet(tokenId?: BigNumberish | null, fn?: BigNumberish | null, delegatee?: string | null): ethers.EventFilter;
    InstantWithdrawExecuted(tokenId?: BigNumberish | null, withdrawAmount?: null, fee?: null, receiver?: string | null): ethers.EventFilter;
    LiquidTokenMinted(tokenId?: BigNumberish | null, recipient?: string | null): ethers.EventFilter;
    LiquidTokenRepaid(tokenId?: BigNumberish | null, payer?: string | null): ethers.EventFilter;
    LockRemoved(tokenId?: BigNumberish | null, manager?: string | null, lockId?: BytesLike | null): ethers.EventFilter;
    LockSet(tokenId?: BigNumberish | null, manager?: string | null, lockId?: BytesLike | null): ethers.EventFilter;
    Minted(tokenId?: BigNumberish | null, owner?: string | null, validator?: BigNumberish | null): ethers.EventFilter;
    PositionMerged(fromTokenId?: BigNumberish | null, intoTokenId?: BigNumberish | null): ethers.EventFilter;
    PositionSplit(fromTokenId?: BigNumberish | null, newTokenId?: BigNumberish | null): ethers.EventFilter;
    RewardsClaimed(tokenId?: BigNumberish | null, recipient?: string | null): ethers.EventFilter;
    RewardsRestaked(tokenId?: BigNumberish | null): ethers.EventFilter;
    ShareBackingRedeemed(fromTokenId?: BigNumberish | null, toTokenId?: BigNumberish | null): ethers.EventFilter;
    SwapDelegated(fromTokenId?: BigNumberish | null, toTokenId?: BigNumberish | null): ethers.EventFilter;
    Transfer(from?: string | null, to?: string | null, tokenId?: BigNumberish | null): ethers.EventFilter;
    Undelegated(tokenId?: BigNumberish | null, validator?: BigNumberish | null, wrId?: BigNumberish | null): ethers.EventFilter;
    ValidatorExitFeeSet(validatorId_?: BigNumberish | null): ethers.EventFilter;
    Withdrawn(tokenId?: BigNumberish | null, wrId?: BigNumberish | null): ethers.EventFilter;
  };
}

export function connectIDiesisPosition(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisPositionContract {
  const contract = new ethers.Contract(address, IDiesisPositionAbi, signerOrProvider);
  Object.assign(contract, {
    safeTransferFromAddressAddressUint256: contract["safeTransferFrom(address,address,uint256)"],
    safeTransferFromAddressAddressUint256Bytes: contract["safeTransferFrom(address,address,uint256,bytes)"],
  });
  return contract as unknown as IDiesisPositionContract;
}
