// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { IDiesisConductorsAbi } from '../../generated/viem/IDiesisConductors.abi.js';

export interface IDiesisConductorsContract extends ethers.Contract {
  finalizeDecrease(overrides?: Overrides): Promise<ethers.ContractTransaction>;
  getConductor(conductor: string, overrides?: CallOverrides): Promise<[string, BigNumber, number, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & { conductor: string; bond: BigNumber; tier: number; totalEarned: BigNumber; todayEarned: BigNumber; todayCapacityRemainingDs: BigNumber; bondAvailableAfterBlock: BigNumber; pendingRefund: BigNumber }>;
  registerOrTopup(overrides?: PayableOverrides): Promise<ethers.ContractTransaction>;
  requestDecrease(amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  filters: {
    DecreaseFinalized(conductor?: string | null): ethers.EventFilter;
    DecreaseRequested(conductor?: string | null): ethers.EventFilter;
    Registered(conductor?: string | null): ethers.EventFilter;
    ShareEarned(conductor?: string | null): ethers.EventFilter;
  };
}

export function connectIDiesisConductors(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisConductorsContract {
  const contract = new ethers.Contract(address, IDiesisConductorsAbi, signerOrProvider);
  return contract as unknown as IDiesisConductorsContract;
}
