// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { IDiesisNameVerifierAbi } from '../../generated/viem/IDiesisNameVerifier.abi.js';

export interface IDiesisNameVerifierContract extends ethers.Contract {
  attest(node: BytesLike, subject: string, kind: BytesLike, digest: BytesLike, expiresAt: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  attestationDigest(attestation: { node: BytesLike; attestationType: BytesLike; issuer: string; subjectHash: BytesLike; evidenceHash: BytesLike; issuedAt: BigNumberish; validUntil: BigNumberish; extraData: BytesLike }, overrides?: CallOverrides): Promise<string>;
  attestationHash(attestation: { node: BytesLike; attestationType: BytesLike; issuer: string; subjectHash: BytesLike; evidenceHash: BytesLike; issuedAt: BigNumberish; validUntil: BigNumberish; extraData: BytesLike }, overrides?: CallOverrides): Promise<string>;
  attestationsBytes32Bytes32(node: BytesLike, attestationType: BytesLike, overrides?: CallOverrides): Promise<string[]>;
  attestationsBytes32(attestationId: BytesLike, overrides?: CallOverrides): Promise<[string, string, string, string, string, BigNumber, BigNumber, boolean] & { node: string; subject: string; kind: string; digest: string; issuer: string; issuedAt: BigNumber; expiresAt: BigNumber; revoked: boolean }>;
  isAttested(node: BytesLike, attestationType: BytesLike, issuer: string, overrides?: CallOverrides): Promise<boolean>;
  isValid(attestationId: BytesLike, overrides?: CallOverrides): Promise<boolean>;
  issuers(issuer: string, overrides?: CallOverrides): Promise<boolean>;
  revoke(attestationId: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  revokeAttestation(node: BytesLike, attestationHash: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  setIssuer(issuer: string, approved: boolean, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  submitAttestation(attestation: { node: BytesLike; attestationType: BytesLike; issuer: string; subjectHash: BytesLike; evidenceHash: BytesLike; issuedAt: BigNumberish; validUntil: BigNumberish; extraData: BytesLike }, signature: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  filters: {
    AttestationRevoked(node?: BytesLike | null, attestationHash?: BytesLike | null, issuer?: string | null): ethers.EventFilter;
    AttestationSubmitted(node?: BytesLike | null, attestationType?: BytesLike | null, issuer?: string | null): ethers.EventFilter;
    Attested(attestationId?: BytesLike | null, node?: BytesLike | null, subject?: string | null): ethers.EventFilter;
    IssuerChanged(issuer?: string | null): ethers.EventFilter;
    Revoked(attestationId?: BytesLike | null): ethers.EventFilter;
  };
}

export function connectIDiesisNameVerifier(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisNameVerifierContract {
  const contract = new ethers.Contract(address, IDiesisNameVerifierAbi, signerOrProvider);
  Object.assign(contract, {
    attestationsBytes32Bytes32: contract["attestations(bytes32,bytes32)"],
    attestationsBytes32: contract["attestations(bytes32)"],
  });
  return contract as unknown as IDiesisNameVerifierContract;
}
