// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { IDiesisSettlementAbi } from '../../generated/viem/IDiesisSettlement.abi.js';

export interface IDiesisSettlementContract extends ethers.Contract {
  authorizeSessionKey(sessionKey: string, actionScope: BigNumberish, validUntil: BigNumberish, maxNotionalOrSpend: BigNumberish, allowedMarketsMask: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  availableBalance(user: string, token: string, overrides?: CallOverrides): Promise<BigNumber>;
  cancelNonceWord(wordPos: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  cancelOrderNonce(nonce: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  creditRouterDeposit(user: string, token: string, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  debitRouterWithdrawal(user: string, token: string, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  deposit(token: string, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  fundPerpBackstop(marketId: BytesLike, amount: BigNumberish, nonce: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  getTradingKeyAuth(owner: string, tradingKey: string, overrides?: CallOverrides): Promise<[string, BigNumber, string] & { header: string; maxOrderNotional: BigNumber; allowedMarketsMask: string }>;
  isNonceUsed(user: string, nonce: BigNumberish, overrides?: CallOverrides): Promise<boolean>;
  registerTradingKey(tradingKey: string, validUntil: BigNumberish, maxOrderNotional: BigNumberish, allowedMarketsMask: BytesLike, canWithdraw: boolean, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  revokeSessionKey(sessionKey: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  revokeTradingKey(tradingKey: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  totalBalance(user: string, token: string, overrides?: CallOverrides): Promise<BigNumber>;
  withdraw(token: string, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  filters: {
    Deposit(user?: string | null, token?: string | null): ethers.EventFilter;
    NonceCancelled(user?: string | null): ethers.EventFilter;
    PerpBackstopFunded(funder?: string | null, marketId?: BytesLike | null, quoteToken?: string | null): ethers.EventFilter;
    TradingKeyRegistered(owner?: string | null, tradingKey?: string | null): ethers.EventFilter;
    TradingKeyRevoked(owner?: string | null, tradingKey?: string | null): ethers.EventFilter;
    Withdrawal(user?: string | null, token?: string | null): ethers.EventFilter;
  };
}

export function connectIDiesisSettlement(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisSettlementContract {
  const contract = new ethers.Contract(address, IDiesisSettlementAbi, signerOrProvider);
  return contract as unknown as IDiesisSettlementContract;
}
