// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { IDiesisMarginAbi } from '../../generated/viem/IDiesisMargin.abi.js';

export interface IDiesisMarginContract extends ethers.Contract {
  resolvePerpProtection(marketId: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  filters: {
    AutoDeleverage(marketId?: BytesLike | null, deleveraged?: string | null, counterparty?: string | null): ethers.EventFilter;
    Liquidation(marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
  };
}

export function connectIDiesisMargin(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisMarginContract {
  const contract = new ethers.Contract(address, IDiesisMarginAbi, signerOrProvider);
  return contract as unknown as IDiesisMarginContract;
}
