// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { IDiesisBundleEscrowAbi } from '../../generated/viem/IDiesisBundleEscrow.abi.js';

export interface IDiesisBundleEscrowContract extends ethers.Contract {
  cancelBundleV2(payer: string, planHash: BytesLike, escrowNonce: BigNumberish): Promise<ethers.ContractTransaction>;
  claimable(account: string): Promise<BigNumber>;
  finalizeBundleV2(payer: string, planHash: BytesLike, escrowNonce: BigNumberish, skippedGas: BigNumberish, beneficiary: string): Promise<ethers.ContractTransaction>;
  reclaimExpiredBundleV2(planHash: BytesLike, escrowNonce: BigNumberish): Promise<ethers.ContractTransaction>;
  reservationOf(payer: string, planHash: BytesLike, escrowNonce: BigNumberish): Promise<[string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & { payer: string; builderPayment: BigNumber; refundGasPrice: BigNumber; maxRefund: BigNumber; expiry: BigNumber; settled: boolean }>;
  reserveBundleV2(planHash: BytesLike, maximumBuilderPayment: BigNumberish, refundGasPrice: BigNumberish, maximumRefund: BigNumberish, escrowNonce: BigNumberish, expiry: BigNumberish): Promise<ethers.ContractTransaction>;
  withdraw(): Promise<ethers.ContractTransaction>;
  filters: {
    BundleCancelled(planHash?: BytesLike | null, escrowNonce?: BigNumberish | null, payer?: string | null): ethers.EventFilter;
    BundleFinalized(planHash?: BytesLike | null, escrowNonce?: BigNumberish | null): ethers.EventFilter;
    BundleReserved(planHash?: BytesLike | null, escrowNonce?: BigNumberish | null, payer?: string | null): ethers.EventFilter;
    Withdrawn(account?: string | null): ethers.EventFilter;
  };
}

export function connectIDiesisBundleEscrow(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisBundleEscrowContract {
  const contract = new ethers.Contract(address, IDiesisBundleEscrowAbi, signerOrProvider);
  return contract as unknown as IDiesisBundleEscrowContract;
}
