// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { IDiesisPerpDeployAbi } from '../../generated/viem/IDiesisPerpDeploy.abi.js';

export interface IDiesisPerpDeployContract extends ethers.Contract {
  applyPerpAbandonmentV1(marketId: BytesLike, parentHash: BytesLike, blockNumber: BigNumberish, policyEpoch: BigNumberish, policyHash: BytesLike, windowStart: BigNumberish, windowEnd: BigNumberish, filledVolume: BigNumberish, operatorFees: BigNumberish, lastMetadataUpdate: BigNumberish, inputHash: BytesLike, committeeEpoch: BigNumberish, committeeIdentity: BytesLike, quorumPower: BigNumberish, attestingPower: BigNumberish, voterCount: BigNumberish, evidenceHash: BytesLike): Promise<ethers.ContractTransaction>;
  applySlash(marketId: BytesLike, reason: BigNumberish): Promise<ethers.ContractTransaction>;
  deployPerp(slotId: BytesLike, marketId: BytesLike, sourceList: BytesLike, metadata: BytesLike, signatures: BytesLike): Promise<ethers.ContractTransaction>;
  expireNextUnactivatedPerpV1(): Promise<ethers.ContractTransaction>;
  expireUnactivatedPerpV1(marketId: BytesLike): Promise<ethers.ContractTransaction>;
  finalizeClose(marketId: BytesLike): Promise<ethers.ContractTransaction>;
  finalizePerpPolicyV1(marketId: BytesLike, revision: BigNumberish, proposalId: BytesLike): Promise<ethers.ContractTransaction>;
  getDeploymentState(marketId: BytesLike): Promise<[number, BigNumber, BigNumber, number] & { stateTag: number; deadlineOrLiveBlock: BigNumber; windowCloseBlock: BigNumber; slashReason: number }>;
  getMarketDeploymentState(marketId: BytesLike): Promise<[number, BigNumber, BigNumber, number] & { stateTag: number; deadlineOrLiveBlock: BigNumber; windowCloseBlock: BigNumber; slashReason: number }>;
  getOperatorBalance(operator: string): Promise<BigNumber>;
  getPerpPolicyV1(marketId: BytesLike): Promise<[[BigNumber, number, ([BigNumber, number, number] & { maxNotional: BigNumber; maxLeverage: number; maintenanceMarginBps: number })[]] & { revision: BigNumber; backstopTopupBps: number; tiers: ([BigNumber, number, number] & { maxNotional: BigNumber; maxLeverage: number; maintenanceMarginBps: number })[] }, [BigNumber, number, string[]] & { epoch: BigNumber; threshold: number; signers: string[] }] & { policy: [BigNumber, number, ([BigNumber, number, number] & { maxNotional: BigNumber; maxLeverage: number; maintenanceMarginBps: number })[]] & { revision: BigNumber; backstopTopupBps: number; tiers: ([BigNumber, number, number] & { maxNotional: BigNumber; maxLeverage: number; maintenanceMarginBps: number })[] }; keyset: [BigNumber, number, string[]] & { epoch: BigNumber; threshold: number; signers: string[] } }>;
  initializePerpMarketV1(baseToken: string, quoteToken: string, tickSize: BigNumberish, lotSize: BigNumberish, maxOpenInterest: BigNumberish, initialMark: BigNumberish, maxLeverage: BigNumberish): Promise<ethers.ContractTransaction>;
  initializePerpMarketV2(baseToken: string, quoteToken: string, tickSize: BigNumberish, lotSize: BigNumberish, maxOpenInterest: BigNumberish, initialMark: BigNumberish, policy: { revision: BigNumberish; backstopTopupBps: BigNumberish; tiers: { maxNotional: BigNumberish; maxLeverage: BigNumberish; maintenanceMarginBps: BigNumberish }[] }, keyset: { epoch: BigNumberish; threshold: BigNumberish; signers: string[] }): Promise<ethers.ContractTransaction>;
  initiateDelist(marketId: BytesLike): Promise<ethers.ContractTransaction>;
  preparePerpMarketCloseV1(marketId: BytesLike, maxOrders: BigNumberish, maxPositions: BigNumberish): Promise<ethers.ContractTransaction>;
  promoteToLive(marketId: BytesLike): Promise<ethers.ContractTransaction>;
  proposePerpPolicyV1(marketId: BytesLike, expectedRevision: BigNumberish, expectedKeysetEpoch: BigNumberish, backstopTopupBps: BigNumberish, tiers: { maxNotional: BigNumberish; maxLeverage: BigNumberish; maintenanceMarginBps: BigNumberish }[], nextSigners: string[], nextThreshold: BigNumberish, signatures: { signer: string; r: BytesLike; s: BytesLike; v: BigNumberish }[]): Promise<ethers.ContractTransaction>;
  recordAuctionWin(marketId: BytesLike, operator: string, registrationDigest: BytesLike, evidenceHash: BytesLike): Promise<ethers.ContractTransaction>;
  filters: {
    Activated(marketId?: BytesLike | null): ethers.EventFilter;
    AuctionWinRecorded(marketId?: BytesLike | null, operator?: string | null): ethers.EventFilter;
    Closed(marketId?: BytesLike | null): ethers.EventFilter;
    Delisting(marketId?: BytesLike | null): ethers.EventFilter;
    LiveStarted(marketId?: BytesLike | null): ethers.EventFilter;
    PerpMarketClosePreparedV1(marketId?: BytesLike | null): ethers.EventFilter;
    PerpMarketInitializedV1(marketId?: BytesLike | null): ethers.EventFilter;
    PerpMarketInitializedV2(marketId?: BytesLike | null): ethers.EventFilter;
    Slashed(marketId?: BytesLike | null): ethers.EventFilter;
  };
}

export function connectIDiesisPerpDeploy(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisPerpDeployContract {
  const contract = new ethers.Contract(address, IDiesisPerpDeployAbi, signerOrProvider);
  return contract as unknown as IDiesisPerpDeployContract;
}
