// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { IDiesisPerpsBookAbi } from '../../generated/viem/IDiesisPerpsBook.abi.js';

export interface IDiesisPerpsBookContract extends ethers.Contract {
  adjustIsolatedMargin(marketId: BytesLike, marginDelta: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  advancePricedPerpRuntime(policyHash: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  amendPerpOrder(orderId: BytesLike, price: BigNumberish, amount: BigNumberish, expiry: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  applyPerpFunding(marketId: BytesLike, fundingRateBps: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  cancelPerpOrder(orderId: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  executePerpTrade(makerOrderId: BytesLike, takerOrderId: BytesLike, fillPrice: BigNumberish, fillQty: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  expirePerpOrder(orderId: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  finalizePerpFeeEpoch(marketId: BytesLike, epoch: BigNumberish, snapshotHash: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  getIsolatedMargin(trader: string, marketId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  getPosition(trader: string, marketId: BytesLike, overrides?: CallOverrides): Promise<[string, BigNumber, BigNumber] & { header: string; size: BigNumber; entryPrice: BigNumber }>;
  submitBoundSessionActions(encodedWrapper: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  submitExchangeActions(encodedActions: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  submitPerpOrder(marketId: BytesLike, side: BigNumberish, orderType: BigNumberish, price: BigNumberish, amount: BigNumberish, flags: BigNumberish, marginType: BigNumberish, expiry: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  submitSponsoredPerpActions(signedEnvelope: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  updatePerpMark(marketId: BytesLike, markPrice: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  updatePerpOracle(marketId: BytesLike, indexPrice: BigNumberish, markPrice: BigNumberish, observedAt: BigNumberish, oracleRound: BigNumberish, sourceSetHash: BytesLike, evidenceHash: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  updatePricedOracle(payload: BytesLike, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  filters: {
    ExchangeActionAccepted(clientActionId?: BytesLike | null, actionIndex?: BigNumberish | null, actionTag?: null, marketId?: BytesLike | null): ethers.EventFilter;
    ExchangeActionRejected(clientActionId?: BytesLike | null, actionIndex?: BigNumberish | null, actionTag?: null, marketId?: BytesLike | null): ethers.EventFilter;
    ExchangeL3Mutation(marketId?: BytesLike | null, orderId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    FundingApplied(marketId?: BytesLike | null): ethers.EventFilter;
    IsolatedMarginAdjusted(marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    MarkPriceUpdated(marketId?: BytesLike | null): ethers.EventFilter;
    OrderCancelled(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    OrderFilled(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    OrderPlaced(orderId?: BytesLike | null, marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    PositionClosed(marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
    PositionCollateralAdjusted(marketId?: BytesLike | null, trader?: string | null): ethers.EventFilter;
  };
}

export function connectIDiesisPerpsBook(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisPerpsBookContract {
  const contract = new ethers.Contract(address, IDiesisPerpsBookAbi, signerOrProvider);
  return contract as unknown as IDiesisPerpsBookContract;
}
