// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { IDiesisErc20FactoryAbi } from '../../generated/viem/IDiesisErc20Factory.abi.js';

export interface IDiesisErc20FactoryContract extends ethers.Contract {
  deploy(params: { symbol: BytesLike; name: string; initialSupply: BigNumberish; deployer: string }): Promise<ethers.ContractTransaction>;
  executeTemplateUpdate(): Promise<ethers.ContractTransaction>;
  predictAddress(deployer: string, symbol: BytesLike): Promise<string>;
  proposeTemplateUpdate(newHash: BytesLike): Promise<ethers.ContractTransaction>;
  templateBytecodeHash(): Promise<string>;
  filters: {
    Erc20Deployed(token?: string | null, deployer?: string | null, symbol?: BytesLike | null): ethers.EventFilter;
    TemplateUpdated(): ethers.EventFilter;
  };
}

export function connectIDiesisErc20Factory(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisErc20FactoryContract {
  const contract = new ethers.Contract(address, IDiesisErc20FactoryAbi, signerOrProvider);
  return contract as unknown as IDiesisErc20FactoryContract;
}
