// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { IDiesisBundleEscrowAbi } from '../../generated/viem/IDiesisBundleEscrow.abi.js';

export interface IDiesisBundleEscrowContract extends ethers.Contract {
  cancelBundle(payer: string, planHash: BytesLike, escrowNonce: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  claimable(account: string, overrides?: CallOverrides): Promise<BigNumber>;
  finalizeBundle(payer: string, planHash: BytesLike, escrowNonce: BigNumberish, skippedGas: BigNumberish, beneficiary: string, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  reclaimExpiredBundle(planHash: BytesLike, escrowNonce: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  reservationOf(payer: string, planHash: BytesLike, escrowNonce: BigNumberish, overrides?: CallOverrides): Promise<[string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & { payer: string; builderPayment: BigNumber; refundGasPrice: BigNumber; maxRefund: BigNumber; expiry: BigNumber; settled: boolean }>;
  reserveBundle(planHash: BytesLike, maximumBuilderPayment: BigNumberish, refundGasPrice: BigNumberish, maximumRefund: BigNumberish, escrowNonce: BigNumberish, expiry: BigNumberish, overrides?: PayableOverrides): Promise<ethers.ContractTransaction>;
  withdraw(overrides?: Overrides): Promise<ethers.ContractTransaction>;
  filters: {
    BundleCancelled(planHash?: BytesLike | null, escrowNonce?: BigNumberish | null, payer?: string | null): ethers.EventFilter;
    BundleFinalized(planHash?: BytesLike | null, escrowNonce?: BigNumberish | null): ethers.EventFilter;
    BundleReserved(planHash?: BytesLike | null, escrowNonce?: BigNumberish | null, payer?: string | null): ethers.EventFilter;
    Withdrawn(account?: string | null): ethers.EventFilter;
  };
}

export function connectIDiesisBundleEscrow(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): IDiesisBundleEscrowContract {
  const contract = new ethers.Contract(address, IDiesisBundleEscrowAbi, signerOrProvider);
  return contract as unknown as IDiesisBundleEscrowContract;
}
