// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, BigNumber, BigNumberish, BytesLike } from 'ethers';
import { ILiquidStakedDSAbi } from '../../generated/viem/ILiquidStakedDS.abi.js';

export interface ILiquidStakedDSContract extends ethers.Contract {
  allowance(owner: string, spender: string): Promise<BigNumber>;
  approve(spender: string, amount: BigNumberish): Promise<ethers.ContractTransaction>;
  balanceOf(account: string): Promise<BigNumber>;
  burn(amount: BigNumberish): Promise<ethers.ContractTransaction>;
  burnFrom(from: string, amount: BigNumberish): Promise<ethers.ContractTransaction>;
  decimals(): Promise<number>;
  mint(to: string, amount: BigNumberish): Promise<ethers.ContractTransaction>;
  name(): Promise<string>;
  symbol(): Promise<string>;
  totalSupply(): Promise<BigNumber>;
  transfer(to: string, amount: BigNumberish): Promise<ethers.ContractTransaction>;
  transferFrom(from: string, to: string, amount: BigNumberish): Promise<ethers.ContractTransaction>;
  filters: {
    Approval(owner?: string | null, spender?: string | null): ethers.EventFilter;
    Transfer(from?: string | null, to?: string | null): ethers.EventFilter;
  };
}

export function connectILiquidStakedDS(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): ILiquidStakedDSContract {
  const contract = new ethers.Contract(address, ILiquidStakedDSAbi, signerOrProvider);
  return contract as unknown as ILiquidStakedDSContract;
}
