// Auto-generated by abi-typegen. Do not edit manually.
import { ethers, type BigNumber, type BigNumberish, type BytesLike, type CallOverrides, type Overrides, type PayableOverrides } from 'ethers';
import { ILiquidStakedDSAbi } from '../../generated/viem/ILiquidStakedDS.abi.js';

export interface ILiquidStakedDSContract extends ethers.Contract {
  allowance(owner: string, spender: string, overrides?: CallOverrides): Promise<BigNumber>;
  approve(spender: string, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;
  burn(amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  burnFrom(from: string, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  decimals(overrides?: CallOverrides): Promise<number>;
  mint(to: string, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  name(overrides?: CallOverrides): Promise<string>;
  symbol(overrides?: CallOverrides): Promise<string>;
  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;
  transfer(to: string, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  transferFrom(from: string, to: string, amount: BigNumberish, overrides?: Overrides): Promise<ethers.ContractTransaction>;
  filters: {
    Approval(owner?: string | null, spender?: string | null): ethers.EventFilter;
    Transfer(from?: string | null, to?: string | null): ethers.EventFilter;
  };
}

export function connectILiquidStakedDS(
  address: string,
  signerOrProvider: ethers.Signer | ethers.providers.Provider,
): ILiquidStakedDSContract {
  const contract = new ethers.Contract(address, ILiquidStakedDSAbi, signerOrProvider);
  return contract as unknown as ILiquidStakedDSContract;
}
