// Auto-generated by abi-typegen. Do not edit manually.
import { DiesisPrivacyPoolsAbi } from '../../generated/viem/DiesisPrivacyPools.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useDiesisPrivacyPoolsArtifactClass(address: Address) {
  return useReadContract({
    address,
    abi: DiesisPrivacyPoolsAbi,
    functionName: 'artifactClass',
  });
}

export function useDiesisPrivacyPoolsAssociationVerifier(address: Address) {
  return useReadContract({
    address,
    abi: DiesisPrivacyPoolsAbi,
    functionName: 'associationVerifier',
  });
}

export function useDiesisPrivacyPoolsInitialized(address: Address) {
  return useReadContract({
    address,
    abi: DiesisPrivacyPoolsAbi,
    functionName: 'initialized',
  });
}

export function useDiesisPrivacyPoolsOwner(address: Address) {
  return useReadContract({
    address,
    abi: DiesisPrivacyPoolsAbi,
    functionName: 'owner',
  });
}

export function useDiesisPrivacyPoolsPendingOwner(address: Address) {
  return useReadContract({
    address,
    abi: DiesisPrivacyPoolsAbi,
    functionName: 'pendingOwner',
  });
}

export function useDiesisPrivacyPoolsProviderCount(address: Address) {
  return useReadContract({
    address,
    abi: DiesisPrivacyPoolsAbi,
    functionName: 'providerCount',
  });
}

export function useDiesisPrivacyPoolsProviderList(address: Address, args: { arg0: bigint }) {
  return useReadContract({
    address,
    abi: DiesisPrivacyPoolsAbi,
    functionName: 'providerList',
    args: [args.arg0],
  });
}

export function useDiesisPrivacyPoolsProviders(address: Address, args: { arg0: `0x${string}` }) {
  return useReadContract({
    address,
    abi: DiesisPrivacyPoolsAbi,
    functionName: 'providers',
    args: [args.arg0],
  });
}

export function useDiesisPrivacyPoolsVerifyAssociation(address: Address, args: { proof: `0x${string}`, associationSetRoot: `0x${string}`, nullifier: `0x${string}`, provider: `0x${string}` }) {
  return useReadContract({
    address,
    abi: DiesisPrivacyPoolsAbi,
    functionName: 'verifyAssociation',
    args: [args.proof, args.associationSetRoot, args.nullifier, args.provider],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useDiesisPrivacyPoolsAcceptOwnership(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: () => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: () =>
      writeContract({
        address,
        abi: DiesisPrivacyPoolsAbi,
        functionName: 'acceptOwnership',
      }),
  };
}

export function useDiesisPrivacyPoolsRegisterProvider(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { provider: `0x${string}`, name: string }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { provider: `0x${string}`, name: string }) =>
      writeContract({
        address,
        abi: DiesisPrivacyPoolsAbi,
        functionName: 'registerProvider',
        args: [args.provider, args.name],
      }),
  };
}

export function useDiesisPrivacyPoolsTransferOwnership(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { newOwner: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { newOwner: `0x${string}` }) =>
      writeContract({
        address,
        abi: DiesisPrivacyPoolsAbi,
        functionName: 'transferOwnership',
        args: [args.newOwner],
      }),
  };
}

export function useDiesisPrivacyPoolsUpdateAssociationSet(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { newRoot: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { newRoot: `0x${string}` }) =>
      writeContract({
        address,
        abi: DiesisPrivacyPoolsAbi,
        functionName: 'updateAssociationSet',
        args: [args.newRoot],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useDiesisPrivacyPoolsAssociationSetUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisPrivacyPoolsAbi,
    eventName: 'AssociationSetUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisPrivacyPoolsOwnershipTransferStartedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisPrivacyPoolsAbi,
    eventName: 'OwnershipTransferStarted',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisPrivacyPoolsOwnershipTransferredEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisPrivacyPoolsAbi,
    eventName: 'OwnershipTransferred',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisPrivacyPoolsProviderRegisteredEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisPrivacyPoolsAbi,
    eventName: 'ProviderRegistered',
    onLogs: (logs) => logs.forEach(listener),
  });
}
