// Auto-generated by abi-typegen. Do not edit manually.
import { DiesisConfigAbi } from '../../generated/viem/DiesisConfig.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useDiesisConfigCutRateUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'CUT_RATE_UPPER',
  });
}

export function useDiesisConfigDefaultDelegationFanoutLimit(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_DELEGATION_FANOUT_LIMIT',
  });
}

export function useDiesisConfigDefaultExitDelayCheckpoints(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_EXIT_DELAY_CHECKPOINTS',
  });
}

export function useDiesisConfigDefaultExitDelaySeconds(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_EXIT_DELAY_SECONDS',
  });
}

export function useDiesisConfigDefaultLivenessDowntimeLimit(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_LIVENESS_DOWNTIME_LIMIT',
  });
}

export function useDiesisConfigDefaultLivenessMissedBlockLimit(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_LIVENESS_MISSED_BLOCK_LIMIT',
  });
}

export function useDiesisConfigDefaultNetworkBurnCut(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_NETWORK_BURN_CUT',
  });
}

export function useDiesisConfigDefaultOperatorTakeRate(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_OPERATOR_TAKE_RATE',
  });
}

export function useDiesisConfigDefaultReliabilityFloor(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_RELIABILITY_FLOOR',
  });
}

export function useDiesisConfigDefaultReliabilitySampleCheckpoints(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_RELIABILITY_SAMPLE_CHECKPOINTS',
  });
}

export function useDiesisConfigDefaultRewardStreamPerSecond(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_REWARD_STREAM_PER_SECOND',
  });
}

export function useDiesisConfigDefaultSurplusRewardBurnCut(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_SURPLUS_REWARD_BURN_CUT',
  });
}

export function useDiesisConfigDefaultTreasuryCut(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_TREASURY_CUT',
  });
}

export function useDiesisConfigDefaultValidatorBondFloor(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DEFAULT_VALIDATOR_BOND_FLOOR',
  });
}

export function useDiesisConfigDelegationFanoutLimitLower(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DELEGATION_FANOUT_LIMIT_LOWER',
  });
}

export function useDiesisConfigDelegationFanoutLimitUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'DELEGATION_FANOUT_LIMIT_UPPER',
  });
}

export function useDiesisConfigExitDelayCheckpointsLower(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'EXIT_DELAY_CHECKPOINTS_LOWER',
  });
}

export function useDiesisConfigExitDelayCheckpointsUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'EXIT_DELAY_CHECKPOINTS_UPPER',
  });
}

export function useDiesisConfigExitDelaySecondsLower(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'EXIT_DELAY_SECONDS_LOWER',
  });
}

export function useDiesisConfigExitDelaySecondsUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'EXIT_DELAY_SECONDS_UPPER',
  });
}

export function useDiesisConfigLivenessDowntimeLimitLower(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'LIVENESS_DOWNTIME_LIMIT_LOWER',
  });
}

export function useDiesisConfigLivenessDowntimeLimitUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'LIVENESS_DOWNTIME_LIMIT_UPPER',
  });
}

export function useDiesisConfigLivenessMissedBlockLimitLower(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'LIVENESS_MISSED_BLOCK_LIMIT_LOWER',
  });
}

export function useDiesisConfigLivenessMissedBlockLimitUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'LIVENESS_MISSED_BLOCK_LIMIT_UPPER',
  });
}

export function useDiesisConfigOperatorTakeRateUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'OPERATOR_TAKE_RATE_UPPER',
  });
}

export function useDiesisConfigReliabilityFloorUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'RELIABILITY_FLOOR_UPPER',
  });
}

export function useDiesisConfigReliabilitySampleLower(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'RELIABILITY_SAMPLE_LOWER',
  });
}

export function useDiesisConfigReliabilitySampleUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'RELIABILITY_SAMPLE_UPPER',
  });
}

export function useDiesisConfigRewardStreamPerSecondUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'REWARD_STREAM_PER_SECOND_UPPER',
  });
}

export function useDiesisConfigSurplusRewardBurnCutUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'SURPLUS_REWARD_BURN_CUT_UPPER',
  });
}

export function useDiesisConfigValidatorBondFloorLower(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'VALIDATOR_BOND_FLOOR_LOWER',
  });
}

export function useDiesisConfigValidatorBondFloorUpper(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'VALIDATOR_BOND_FLOOR_UPPER',
  });
}

export function useDiesisConfigDelegationFanoutLimit(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'delegationFanoutLimit',
  });
}

export function useDiesisConfigExitDelayCheckpoints(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'exitDelayCheckpoints',
  });
}

export function useDiesisConfigExitDelaySeconds(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'exitDelaySeconds',
  });
}

export function useDiesisConfigLivenessDowntimeLimit(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'livenessDowntimeLimit',
  });
}

export function useDiesisConfigLivenessMissedBlockLimit(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'livenessMissedBlockLimit',
  });
}

export function useDiesisConfigMintReceiver(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'mintReceiver',
  });
}

export function useDiesisConfigNetworkBurnCut(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'networkBurnCut',
  });
}

export function useDiesisConfigOperatorTakeRate(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'operatorTakeRate',
  });
}

export function useDiesisConfigOwner(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'owner',
  });
}

export function useDiesisConfigReliabilityFloor(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'reliabilityFloor',
  });
}

export function useDiesisConfigReliabilitySampleCheckpoints(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'reliabilitySampleCheckpoints',
  });
}

export function useDiesisConfigRewardStreamPerSecond(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'rewardStreamPerSecond',
  });
}

export function useDiesisConfigSurplusRewardBurnCut(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'surplusRewardBurnCut',
  });
}

export function useDiesisConfigTreasuryCut(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'treasuryCut',
  });
}

export function useDiesisConfigValidatorBondFloor(address: Address) {
  return useReadContract({
    address,
    abi: DiesisConfigAbi,
    functionName: 'validatorBondFloor',
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useDiesisConfigRenounceOwnership(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: () => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: () =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'renounceOwnership',
      }),
  };
}

export function useDiesisConfigSetDelegationFanoutLimit(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setDelegationFanoutLimit',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetExitDelayCheckpoints(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setExitDelayCheckpoints',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetExitDelaySeconds(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setExitDelaySeconds',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetLivenessDowntimeLimit(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setLivenessDowntimeLimit',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetLivenessMissedBlockLimit(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setLivenessMissedBlockLimit',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetMintReceiver(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: `0x${string}` }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setMintReceiver',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetNetworkBurnCut(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setNetworkBurnCut',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetOperatorTakeRate(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setOperatorTakeRate',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetReliabilityFloor(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setReliabilityFloor',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetReliabilitySampleCheckpoints(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: number }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: number }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setReliabilitySampleCheckpoints',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetRewardStreamPerSecond(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setRewardStreamPerSecond',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetSurplusRewardBurnCut(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setSurplusRewardBurnCut',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetTreasuryCut(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setTreasuryCut',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigSetValidatorBondFloor(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { v: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { v: bigint }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'setValidatorBondFloor',
        args: [args.v],
      }),
  };
}

export function useDiesisConfigTransferOwnership(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { newOwner: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { newOwner: `0x${string}` }) =>
      writeContract({
        address,
        abi: DiesisConfigAbi,
        functionName: 'transferOwnership',
        args: [args.newOwner],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useDiesisConfigDelegationFanoutLimitUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'DelegationFanoutLimitUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigExitDelayCheckpointsUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'ExitDelayCheckpointsUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigExitDelaySecondsUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'ExitDelaySecondsUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigLivenessDowntimeLimitUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'LivenessDowntimeLimitUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigLivenessMissedBlockLimitUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'LivenessMissedBlockLimitUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigMintReceiverUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'MintReceiverUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigNetworkBurnCutUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'NetworkBurnCutUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigOperatorTakeRateUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'OperatorTakeRateUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigOwnershipTransferredEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'OwnershipTransferred',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigReliabilityFloorUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'ReliabilityFloorUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigReliabilitySampleCheckpointsUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'ReliabilitySampleCheckpointsUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigRewardStreamPerSecondUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'RewardStreamPerSecondUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigSurplusRewardBurnCutUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'SurplusRewardBurnCutUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigTreasuryCutUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'TreasuryCutUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useDiesisConfigValidatorBondFloorUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: DiesisConfigAbi,
    eventName: 'ValidatorBondFloorUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}
