// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisReverseRegistrarAbi } from '../../generated/viem/IDiesisReverseRegistrar.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisReverseRegistrarControllers(address: Address, args: { controller: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisReverseRegistrarAbi,
    functionName: 'controllers',
    args: [args.controller],
  });
}

export function useIDiesisReverseRegistrarName(address: Address, args: { addr: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisReverseRegistrarAbi,
    functionName: 'name',
    args: [args.addr],
  });
}

export function useIDiesisReverseRegistrarNode(address: Address, args: { addr: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisReverseRegistrarAbi,
    functionName: 'node',
    args: [args.addr],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisReverseRegistrarSetController(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { controller: `0x${string}`, approved: boolean }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { controller: `0x${string}`, approved: boolean }) =>
      writeContract({
        address,
        abi: IDiesisReverseRegistrarAbi,
        functionName: 'setController',
        args: [args.controller, args.approved],
      }),
  };
}

export function useIDiesisReverseRegistrarSetName(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { name_: string }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { name_: string }) =>
      writeContract({
        address,
        abi: IDiesisReverseRegistrarAbi,
        functionName: 'setName',
        args: [args.name_],
      }),
  };
}

export function useIDiesisReverseRegistrarSetNameForAddr(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { addr: `0x${string}`, name_: string }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { addr: `0x${string}`, name_: string }) =>
      writeContract({
        address,
        abi: IDiesisReverseRegistrarAbi,
        functionName: 'setNameForAddr',
        args: [args.addr, args.name_],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisReverseRegistrarControllerChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisReverseRegistrarAbi,
    eventName: 'ControllerChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisReverseRegistrarReverseNameChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisReverseRegistrarAbi,
    eventName: 'ReverseNameChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}
