// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisIssuanceAuctionAbi } from '../../generated/viem/IDiesisIssuanceAuction.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisIssuanceAuctionCurrentPerpListingPrice(address: Address) {
  return useReadContract({
    address,
    abi: IDiesisIssuanceAuctionAbi,
    functionName: 'currentPerpListingPrice',
  });
}

export function useIDiesisIssuanceAuctionGetPerpListingSlot(address: Address) {
  return useReadContract({
    address,
    abi: IDiesisIssuanceAuctionAbi,
    functionName: 'getPerpListingSlot',
  });
}

export function useIDiesisIssuanceAuctionGetPerpRegistrationPricing(address: Address, args: { marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisIssuanceAuctionAbi,
    functionName: 'getPerpRegistrationPricing',
    args: [args.marketId],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisIssuanceAuctionBidPricedPerpListing(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { registration: { marketId: `0x${string}`; baseAsset: `0x${string}`; quoteAsset: `0x${string}`; evidenceHash: `0x${string}`; pricingVersion: number; priceDenominator: bigint } }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { registration: { marketId: `0x${string}`; baseAsset: `0x${string}`; quoteAsset: `0x${string}`; evidenceHash: `0x${string}`; pricingVersion: number; priceDenominator: bigint } }) =>
      writeContract({
        address,
        abi: IDiesisIssuanceAuctionAbi,
        functionName: 'bidPricedPerpListing',
        args: [args.registration],
      }),
  };
}

export function useIDiesisIssuanceAuctionBidUnpricedPerpListing(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { registration: { marketId: `0x${string}`; baseAsset: `0x${string}`; quoteAsset: `0x${string}`; evidenceHash: `0x${string}` } }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { registration: { marketId: `0x${string}`; baseAsset: `0x${string}`; quoteAsset: `0x${string}`; evidenceHash: `0x${string}` } }) =>
      writeContract({
        address,
        abi: IDiesisIssuanceAuctionAbi,
        functionName: 'bidUnpricedPerpListing',
        args: [args.registration],
      }),
  };
}

export function useIDiesisIssuanceAuctionSettlePerpListing(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: () => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: () =>
      writeContract({
        address,
        abi: IDiesisIssuanceAuctionAbi,
        functionName: 'settlePerpListing',
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisIssuanceAuctionBidAcceptedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisIssuanceAuctionAbi,
    eventName: 'BidAccepted',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisIssuanceAuctionSlotSettledEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisIssuanceAuctionAbi,
    eventName: 'SlotSettled',
    onLogs: (logs) => logs.forEach(listener),
  });
}
