// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisMarginAbi } from '../../generated/viem/IDiesisMargin.abi.js';
import { useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisMarginResolvePerpProtectionV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisMarginAbi,
        functionName: 'resolvePerpProtectionV1',
        args: [args.marketId],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisMarginAutoDeleverageEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisMarginAbi,
    eventName: 'AutoDeleverage',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisMarginLiquidationEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisMarginAbi,
    eventName: 'Liquidation',
    onLogs: (logs) => logs.forEach(listener),
  });
}
