// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisNameVerifierAbi } from '../../generated/viem/IDiesisNameVerifier.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisNameVerifierAttestationDigest(address: Address, args: { attestation: { node: `0x${string}`; attestationType: `0x${string}`; issuer: `0x${string}`; subjectHash: `0x${string}`; evidenceHash: `0x${string}`; issuedAt: bigint; validUntil: bigint; extraData: `0x${string}` } }) {
  return useReadContract({
    address,
    abi: IDiesisNameVerifierAbi,
    functionName: 'attestationDigest',
    args: [args.attestation],
  });
}

export function useIDiesisNameVerifierAttestationHash(address: Address, args: { attestation: { node: `0x${string}`; attestationType: `0x${string}`; issuer: `0x${string}`; subjectHash: `0x${string}`; evidenceHash: `0x${string}`; issuedAt: bigint; validUntil: bigint; extraData: `0x${string}` } }) {
  return useReadContract({
    address,
    abi: IDiesisNameVerifierAbi,
    functionName: 'attestationHash',
    args: [args.attestation],
  });
}

export function useIDiesisNameVerifierAttestationsBytes32Bytes32(address: Address, args: { node: `0x${string}`, attestationType: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameVerifierAbi,
    functionName: 'attestations',
    args: [args.node, args.attestationType],
  });
}

export function useIDiesisNameVerifierAttestationsBytes32(address: Address, args: { attestationId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameVerifierAbi,
    functionName: 'attestations',
    args: [args.attestationId],
  });
}

export function useIDiesisNameVerifierIsAttested(address: Address, args: { node: `0x${string}`, attestationType: `0x${string}`, issuer: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameVerifierAbi,
    functionName: 'isAttested',
    args: [args.node, args.attestationType, args.issuer],
  });
}

export function useIDiesisNameVerifierIsValid(address: Address, args: { attestationId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameVerifierAbi,
    functionName: 'isValid',
    args: [args.attestationId],
  });
}

export function useIDiesisNameVerifierIssuers(address: Address, args: { issuer: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameVerifierAbi,
    functionName: 'issuers',
    args: [args.issuer],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisNameVerifierAttest(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, subject: `0x${string}`, kind: `0x${string}`, digest: `0x${string}`, expiresAt: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, subject: `0x${string}`, kind: `0x${string}`, digest: `0x${string}`, expiresAt: bigint }) =>
      writeContract({
        address,
        abi: IDiesisNameVerifierAbi,
        functionName: 'attest',
        args: [args.node, args.subject, args.kind, args.digest, args.expiresAt],
      }),
  };
}

export function useIDiesisNameVerifierRevoke(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { attestationId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { attestationId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNameVerifierAbi,
        functionName: 'revoke',
        args: [args.attestationId],
      }),
  };
}

export function useIDiesisNameVerifierRevokeAttestation(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, attestationHash: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, attestationHash: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNameVerifierAbi,
        functionName: 'revokeAttestation',
        args: [args.node, args.attestationHash],
      }),
  };
}

export function useIDiesisNameVerifierSetIssuer(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { issuer: `0x${string}`, approved: boolean }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { issuer: `0x${string}`, approved: boolean }) =>
      writeContract({
        address,
        abi: IDiesisNameVerifierAbi,
        functionName: 'setIssuer',
        args: [args.issuer, args.approved],
      }),
  };
}

export function useIDiesisNameVerifierSubmitAttestation(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { attestation: { node: `0x${string}`; attestationType: `0x${string}`; issuer: `0x${string}`; subjectHash: `0x${string}`; evidenceHash: `0x${string}`; issuedAt: bigint; validUntil: bigint; extraData: `0x${string}` }, signature: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { attestation: { node: `0x${string}`; attestationType: `0x${string}`; issuer: `0x${string}`; subjectHash: `0x${string}`; evidenceHash: `0x${string}`; issuedAt: bigint; validUntil: bigint; extraData: `0x${string}` }, signature: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNameVerifierAbi,
        functionName: 'submitAttestation',
        args: [args.attestation, args.signature],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisNameVerifierAttestationRevokedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameVerifierAbi,
    eventName: 'AttestationRevoked',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameVerifierAttestationSubmittedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameVerifierAbi,
    eventName: 'AttestationSubmitted',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameVerifierAttestedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameVerifierAbi,
    eventName: 'Attested',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameVerifierIssuerChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameVerifierAbi,
    eventName: 'IssuerChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameVerifierRevokedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameVerifierAbi,
    eventName: 'Revoked',
    onLogs: (logs) => logs.forEach(listener),
  });
}
