// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisNamePolicyAbi } from '../../generated/viem/IDiesisNamePolicy.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisNamePolicyGuardians(address: Address, args: { node: `0x${string}`, guardian: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNamePolicyAbi,
    functionName: 'guardians',
    args: [args.node, args.guardian],
  });
}

export function useIDiesisNamePolicyIsTransferLocked(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNamePolicyAbi,
    functionName: 'isTransferLocked',
    args: [args.node],
  });
}

export function useIDiesisNamePolicyRecoveryDelay(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNamePolicyAbi,
    functionName: 'recoveryDelay',
    args: [args.node],
  });
}

export function useIDiesisNamePolicyRecoveryEnabled(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNamePolicyAbi,
    functionName: 'recoveryEnabled',
    args: [args.node],
  });
}

export function useIDiesisNamePolicyRecoveryFallbackOwner(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNamePolicyAbi,
    functionName: 'recoveryFallbackOwner',
    args: [args.node],
  });
}

export function useIDiesisNamePolicyRecoveryThreshold(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNamePolicyAbi,
    functionName: 'recoveryThreshold',
    args: [args.node],
  });
}

export function useIDiesisNamePolicyTransferLockUntil(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNamePolicyAbi,
    functionName: 'transferLockUntil',
    args: [args.node],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisNamePolicyApproveRecovery(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, newOwner: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, newOwner: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNamePolicyAbi,
        functionName: 'approveRecovery',
        args: [args.node, args.newOwner],
      }),
  };
}

export function useIDiesisNamePolicyCancelRecovery(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, newOwner: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, newOwner: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNamePolicyAbi,
        functionName: 'cancelRecovery',
        args: [args.node, args.newOwner],
      }),
  };
}

export function useIDiesisNamePolicyFinalizeRecovery(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, newOwner: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, newOwner: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNamePolicyAbi,
        functionName: 'finalizeRecovery',
        args: [args.node, args.newOwner],
      }),
  };
}

export function useIDiesisNamePolicyGuardedTransfer(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, newOwner: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, newOwner: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNamePolicyAbi,
        functionName: 'guardedTransfer',
        args: [args.node, args.newOwner],
      }),
  };
}

export function useIDiesisNamePolicySetGuardian(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, guardian: `0x${string}`, approved: boolean }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, guardian: `0x${string}`, approved: boolean }) =>
      writeContract({
        address,
        abi: IDiesisNamePolicyAbi,
        functionName: 'setGuardian',
        args: [args.node, args.guardian, args.approved],
      }),
  };
}

export function useIDiesisNamePolicySetRecoveryConfig(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, threshold: number, delay: bigint, fallbackOwner: `0x${string}`, enabled: boolean }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, threshold: number, delay: bigint, fallbackOwner: `0x${string}`, enabled: boolean }) =>
      writeContract({
        address,
        abi: IDiesisNamePolicyAbi,
        functionName: 'setRecoveryConfig',
        args: [args.node, args.threshold, args.delay, args.fallbackOwner, args.enabled],
      }),
  };
}

export function useIDiesisNamePolicySetTransferLock(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, lockedUntil: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, lockedUntil: bigint }) =>
      writeContract({
        address,
        abi: IDiesisNamePolicyAbi,
        functionName: 'setTransferLock',
        args: [args.node, args.lockedUntil],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisNamePolicyGuardianChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNamePolicyAbi,
    eventName: 'GuardianChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNamePolicyNameRecoveredEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNamePolicyAbi,
    eventName: 'NameRecovered',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNamePolicyRecoveryApprovedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNamePolicyAbi,
    eventName: 'RecoveryApproved',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNamePolicyRecoveryCancelledEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNamePolicyAbi,
    eventName: 'RecoveryCancelled',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNamePolicyRecoveryConfigChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNamePolicyAbi,
    eventName: 'RecoveryConfigChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNamePolicyTransferLockChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNamePolicyAbi,
    eventName: 'TransferLockChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}
