// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisConductorsAbi } from '../../generated/viem/IDiesisConductors.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisConductorsGetConductor(address: Address, args: { conductor: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisConductorsAbi,
    functionName: 'getConductor',
    args: [args.conductor],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisConductorsFinalizeDecrease(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: () => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: () =>
      writeContract({
        address,
        abi: IDiesisConductorsAbi,
        functionName: 'finalizeDecrease',
      }),
  };
}

export function useIDiesisConductorsRegisterOrTopup(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (options?: { value?: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (options?: { value?: bigint }) =>
      writeContract({
        address,
        abi: IDiesisConductorsAbi,
        functionName: 'registerOrTopup',
        value: options?.value,
      }),
  };
}

export function useIDiesisConductorsRequestDecrease(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { amount: bigint }) =>
      writeContract({
        address,
        abi: IDiesisConductorsAbi,
        functionName: 'requestDecrease',
        args: [args.amount],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisConductorsDecreaseFinalizedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisConductorsAbi,
    eventName: 'DecreaseFinalized',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisConductorsDecreaseRequestedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisConductorsAbi,
    eventName: 'DecreaseRequested',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisConductorsRegisteredEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisConductorsAbi,
    eventName: 'Registered',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisConductorsShareEarnedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisConductorsAbi,
    eventName: 'ShareEarned',
    onLogs: (logs) => logs.forEach(listener),
  });
}
