// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisNameRegistryAbi } from '../../generated/viem/IDiesisNameRegistry.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisNameRegistryControllers(address: Address, args: { controller: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'controllers',
    args: [args.controller],
  });
}

export function useIDiesisNameRegistryExpiry(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'expiry',
    args: [args.node],
  });
}

export function useIDiesisNameRegistryIsApprovedForAll(address: Address, args: { owner_: `0x${string}`, operator: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'isApprovedForAll',
    args: [args.owner_, args.operator],
  });
}

export function useIDiesisNameRegistryIsAuthorized(address: Address, args: { node: `0x${string}`, actor: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'isAuthorized',
    args: [args.node, args.actor],
  });
}

export function useIDiesisNameRegistryIsExpired(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'isExpired',
    args: [args.node],
  });
}

export function useIDiesisNameRegistryNamePolicy(address: Address) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'namePolicy',
  });
}

export function useIDiesisNameRegistryOwner(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'owner',
    args: [args.node],
  });
}

export function useIDiesisNameRegistryOwnershipEpoch(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'ownershipEpoch',
    args: [args.node],
  });
}

export function useIDiesisNameRegistryResolver(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'resolver',
    args: [args.node],
  });
}

export function useIDiesisNameRegistryTtl(address: Address, args: { node: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisNameRegistryAbi,
    functionName: 'ttl',
    args: [args.node],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisNameRegistrySetApprovalForAll(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { operator: `0x${string}`, approved: boolean }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { operator: `0x${string}`, approved: boolean }) =>
      writeContract({
        address,
        abi: IDiesisNameRegistryAbi,
        functionName: 'setApprovalForAll',
        args: [args.operator, args.approved],
      }),
  };
}

export function useIDiesisNameRegistrySetController(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { controller: `0x${string}`, approved: boolean }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { controller: `0x${string}`, approved: boolean }) =>
      writeContract({
        address,
        abi: IDiesisNameRegistryAbi,
        functionName: 'setController',
        args: [args.controller, args.approved],
      }),
  };
}

export function useIDiesisNameRegistrySetExpiry(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, expiry_: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, expiry_: bigint }) =>
      writeContract({
        address,
        abi: IDiesisNameRegistryAbi,
        functionName: 'setExpiry',
        args: [args.node, args.expiry_],
      }),
  };
}

export function useIDiesisNameRegistrySetNamePolicy(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { policy: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { policy: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNameRegistryAbi,
        functionName: 'setNamePolicy',
        args: [args.policy],
      }),
  };
}

export function useIDiesisNameRegistrySetOwner(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, owner_: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, owner_: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNameRegistryAbi,
        functionName: 'setOwner',
        args: [args.node, args.owner_],
      }),
  };
}

export function useIDiesisNameRegistrySetResolver(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, resolver_: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, resolver_: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNameRegistryAbi,
        functionName: 'setResolver',
        args: [args.node, args.resolver_],
      }),
  };
}

export function useIDiesisNameRegistrySetSubnodeOwner(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, label: `0x${string}`, owner_: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, label: `0x${string}`, owner_: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisNameRegistryAbi,
        functionName: 'setSubnodeOwner',
        args: [args.node, args.label, args.owner_],
      }),
  };
}

export function useIDiesisNameRegistrySetSubnodeRecord(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, label: `0x${string}`, owner_: `0x${string}`, resolver_: `0x${string}`, ttl_: bigint, expiry_: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, label: `0x${string}`, owner_: `0x${string}`, resolver_: `0x${string}`, ttl_: bigint, expiry_: bigint }) =>
      writeContract({
        address,
        abi: IDiesisNameRegistryAbi,
        functionName: 'setSubnodeRecord',
        args: [args.node, args.label, args.owner_, args.resolver_, args.ttl_, args.expiry_],
      }),
  };
}

export function useIDiesisNameRegistrySetTtl(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { node: `0x${string}`, ttl_: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { node: `0x${string}`, ttl_: bigint }) =>
      writeContract({
        address,
        abi: IDiesisNameRegistryAbi,
        functionName: 'setTTL',
        args: [args.node, args.ttl_],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisNameRegistryApprovalForAllEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameRegistryAbi,
    eventName: 'ApprovalForAll',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameRegistryControllerChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameRegistryAbi,
    eventName: 'ControllerChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameRegistryExpiryChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameRegistryAbi,
    eventName: 'ExpiryChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameRegistryNamePolicyChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameRegistryAbi,
    eventName: 'NamePolicyChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameRegistryOwnerChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameRegistryAbi,
    eventName: 'OwnerChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameRegistryResolverChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameRegistryAbi,
    eventName: 'ResolverChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisNameRegistryTtlChangedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisNameRegistryAbi,
    eventName: 'TTLChanged',
    onLogs: (logs) => logs.forEach(listener),
  });
}
