// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisBuybackBurnAbi } from '../../generated/viem/IDiesisBuybackBurn.abi.js';
import { useReadContract, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisBuybackBurnCumulativeBurnedDs(address: Address) {
  return useReadContract({
    address,
    abi: IDiesisBuybackBurnAbi,
    functionName: 'cumulativeBurnedDs',
  });
}

export function useIDiesisBuybackBurnLastTwapAveragePrice(address: Address, args: { token: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisBuybackBurnAbi,
    functionName: 'lastTwapAveragePrice',
    args: [args.token],
  });
}

export function useIDiesisBuybackBurnNextWindowStartBlock(address: Address, args: { token: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisBuybackBurnAbi,
    functionName: 'nextWindowStartBlock',
    args: [args.token],
  });
}

export function useIDiesisBuybackBurnPendingPurchaseByAsset(address: Address, args: { token: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisBuybackBurnAbi,
    functionName: 'pendingPurchaseByAsset',
    args: [args.token],
  });
}

export function useIDiesisBuybackBurnWindowState(address: Address, args: { token: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisBuybackBurnAbi,
    functionName: 'windowState',
    args: [args.token],
  });
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisBuybackBurnAssetApprovedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisBuybackBurnAbi,
    eventName: 'AssetApproved',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisBuybackBurnBurnChunkEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisBuybackBurnAbi,
    eventName: 'BurnChunk',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisBuybackBurnDsBurnedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisBuybackBurnAbi,
    eventName: 'DsBurned',
    onLogs: (logs) => logs.forEach(listener),
  });
}
