// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisMarketsAbi } from '../../generated/viem/IDiesisMarkets.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisMarketsGetMarket(address: Address, args: { marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisMarketsAbi,
    functionName: 'getMarket',
    args: [args.marketId],
  });
}

export function useIDiesisMarketsGetMarketPricing(address: Address, args: { marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisMarketsAbi,
    functionName: 'getMarketPricing',
    args: [args.marketId],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisMarketsCheckCircuitBreaker(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, currentPrice: bigint, referencePrice: bigint, thresholdBps: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, currentPrice: bigint, referencePrice: bigint, thresholdBps: bigint }) =>
      writeContract({
        address,
        abi: IDiesisMarketsAbi,
        functionName: 'checkCircuitBreaker',
        args: [args.marketId, args.currentPrice, args.referencePrice, args.thresholdBps],
      }),
  };
}

export function useIDiesisMarketsCreatePricedSpotMarket(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { baseToken: `0x${string}`, quoteToken: `0x${string}`, tickSize: bigint, lotSize: bigint, priceDenominator: bigint, bond: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { baseToken: `0x${string}`, quoteToken: `0x${string}`, tickSize: bigint, lotSize: bigint, priceDenominator: bigint, bond: bigint }) =>
      writeContract({
        address,
        abi: IDiesisMarketsAbi,
        functionName: 'createPricedSpotMarket',
        args: [args.baseToken, args.quoteToken, args.tickSize, args.lotSize, args.priceDenominator, args.bond],
      }),
  };
}

export function useIDiesisMarketsCreateSpotMarket(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { baseToken: `0x${string}`, quoteToken: `0x${string}`, tickSize: bigint, lotSize: bigint, bond: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { baseToken: `0x${string}`, quoteToken: `0x${string}`, tickSize: bigint, lotSize: bigint, bond: bigint }) =>
      writeContract({
        address,
        abi: IDiesisMarketsAbi,
        functionName: 'createSpotMarket',
        args: [args.baseToken, args.quoteToken, args.tickSize, args.lotSize, args.bond],
      }),
  };
}

export function useIDiesisMarketsDeployTokenAndSpotBook(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { symbol: `0x${string}`, name: string, initialSupply: bigint, dsBond: bigint, usdcFee: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { symbol: `0x${string}`, name: string, initialSupply: bigint, dsBond: bigint, usdcFee: bigint }) =>
      writeContract({
        address,
        abi: IDiesisMarketsAbi,
        functionName: 'deployTokenAndSpotBook',
        args: [args.symbol, args.name, args.initialSupply, args.dsBond, args.usdcFee],
      }),
  };
}

export function useIDiesisMarketsResumeMarket(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisMarketsAbi,
        functionName: 'resumeMarket',
        args: [args.marketId],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisMarketsCircuitBreakerTriggeredEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisMarketsAbi,
    eventName: 'CircuitBreakerTriggered',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisMarketsMarketCreatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisMarketsAbi,
    eventName: 'MarketCreated',
    onLogs: (logs) => logs.forEach(listener),
  });
}
