// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisOperatorBondAbi } from '../../generated/viem/IDiesisOperatorBond.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisOperatorBondGetBond(address: Address, args: { marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisOperatorBondAbi,
    functionName: 'getBond',
    args: [args.marketId],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisOperatorBondFinalizeRelease(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisOperatorBondAbi,
        functionName: 'finalizeRelease',
        args: [args.marketId],
      }),
  };
}

export function useIDiesisOperatorBondPostBond(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}` }, options?: { value?: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}` }, options?: { value?: bigint }) =>
      writeContract({
        address,
        abi: IDiesisOperatorBondAbi,
        functionName: 'postBond',
        args: [args.marketId],
        value: options?.value,
      }),
  };
}

export function useIDiesisOperatorBondRequestRelease(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisOperatorBondAbi,
        functionName: 'requestRelease',
        args: [args.marketId],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisOperatorBondBondPostedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisOperatorBondAbi,
    eventName: 'BondPosted',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisOperatorBondBondSlashedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisOperatorBondAbi,
    eventName: 'BondSlashed',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisOperatorBondReleaseFinalizedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisOperatorBondAbi,
    eventName: 'ReleaseFinalized',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisOperatorBondReleaseRequestedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisOperatorBondAbi,
    eventName: 'ReleaseRequested',
    onLogs: (logs) => logs.forEach(listener),
  });
}
