// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisPerpDeployAbi } from '../../generated/viem/IDiesisPerpDeploy.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisPerpDeployGetDeploymentState(address: Address, args: { marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisPerpDeployAbi,
    functionName: 'getDeploymentState',
    args: [args.marketId],
  });
}

export function useIDiesisPerpDeployGetMarketDeploymentState(address: Address, args: { marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisPerpDeployAbi,
    functionName: 'getMarketDeploymentState',
    args: [args.marketId],
  });
}

export function useIDiesisPerpDeployGetOperatorBalance(address: Address, args: { operator: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisPerpDeployAbi,
    functionName: 'getOperatorBalance',
    args: [args.operator],
  });
}

export function useIDiesisPerpDeployGetPerpPolicyV1(address: Address, args: { marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisPerpDeployAbi,
    functionName: 'getPerpPolicyV1',
    args: [args.marketId],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisPerpDeployApplyPerpAbandonmentV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, parentHash: `0x${string}`, blockNumber: bigint, policyEpoch: bigint, policyHash: `0x${string}`, windowStart: bigint, windowEnd: bigint, filledVolume: bigint, operatorFees: bigint, lastMetadataUpdate: bigint, inputHash: `0x${string}`, committeeEpoch: bigint, committeeIdentity: `0x${string}`, quorumPower: bigint, attestingPower: bigint, voterCount: number, evidenceHash: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, parentHash: `0x${string}`, blockNumber: bigint, policyEpoch: bigint, policyHash: `0x${string}`, windowStart: bigint, windowEnd: bigint, filledVolume: bigint, operatorFees: bigint, lastMetadataUpdate: bigint, inputHash: `0x${string}`, committeeEpoch: bigint, committeeIdentity: `0x${string}`, quorumPower: bigint, attestingPower: bigint, voterCount: number, evidenceHash: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'applyPerpAbandonmentV1',
        args: [args.marketId, args.parentHash, args.blockNumber, args.policyEpoch, args.policyHash, args.windowStart, args.windowEnd, args.filledVolume, args.operatorFees, args.lastMetadataUpdate, args.inputHash, args.committeeEpoch, args.committeeIdentity, args.quorumPower, args.attestingPower, args.voterCount, args.evidenceHash],
      }),
  };
}

export function useIDiesisPerpDeployApplySlash(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, reason: number }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, reason: number }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'applySlash',
        args: [args.marketId, args.reason],
      }),
  };
}

export function useIDiesisPerpDeployDeployPerp(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { slotId: `0x${string}`, marketId: `0x${string}`, sourceList: `0x${string}`, metadata: `0x${string}`, signatures: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { slotId: `0x${string}`, marketId: `0x${string}`, sourceList: `0x${string}`, metadata: `0x${string}`, signatures: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'deployPerp',
        args: [args.slotId, args.marketId, args.sourceList, args.metadata, args.signatures],
      }),
  };
}

export function useIDiesisPerpDeployExpireNextUnactivatedPerpV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: () => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: () =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'expireNextUnactivatedPerpV1',
      }),
  };
}

export function useIDiesisPerpDeployExpireUnactivatedPerpV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'expireUnactivatedPerpV1',
        args: [args.marketId],
      }),
  };
}

export function useIDiesisPerpDeployFinalizeClose(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'finalizeClose',
        args: [args.marketId],
      }),
  };
}

export function useIDiesisPerpDeployFinalizePerpPolicyV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, revision: bigint, proposalId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, revision: bigint, proposalId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'finalizePerpPolicyV1',
        args: [args.marketId, args.revision, args.proposalId],
      }),
  };
}

export function useIDiesisPerpDeployInitializePerpMarketV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { baseToken: `0x${string}`, quoteToken: `0x${string}`, tickSize: bigint, lotSize: bigint, maxOpenInterest: bigint, initialMark: bigint, maxLeverage: number }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { baseToken: `0x${string}`, quoteToken: `0x${string}`, tickSize: bigint, lotSize: bigint, maxOpenInterest: bigint, initialMark: bigint, maxLeverage: number }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'initializePerpMarketV1',
        args: [args.baseToken, args.quoteToken, args.tickSize, args.lotSize, args.maxOpenInterest, args.initialMark, args.maxLeverage],
      }),
  };
}

export function useIDiesisPerpDeployInitializePerpMarketV2(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { baseToken: `0x${string}`, quoteToken: `0x${string}`, tickSize: bigint, lotSize: bigint, maxOpenInterest: bigint, initialMark: bigint, policy: { revision: bigint; backstopTopupBps: number; tiers: readonly { maxNotional: bigint; maxLeverage: number; maintenanceMarginBps: number }[] }, keyset: { epoch: bigint; threshold: number; signers: readonly `0x${string}`[] } }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { baseToken: `0x${string}`, quoteToken: `0x${string}`, tickSize: bigint, lotSize: bigint, maxOpenInterest: bigint, initialMark: bigint, policy: { revision: bigint; backstopTopupBps: number; tiers: readonly { maxNotional: bigint; maxLeverage: number; maintenanceMarginBps: number }[] }, keyset: { epoch: bigint; threshold: number; signers: readonly `0x${string}`[] } }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'initializePerpMarketV2',
        args: [args.baseToken, args.quoteToken, args.tickSize, args.lotSize, args.maxOpenInterest, args.initialMark, args.policy, args.keyset],
      }),
  };
}

export function useIDiesisPerpDeployInitiateDelist(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'initiateDelist',
        args: [args.marketId],
      }),
  };
}

export function useIDiesisPerpDeployPreparePerpMarketCloseV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, maxOrders: number, maxPositions: number }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, maxOrders: number, maxPositions: number }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'preparePerpMarketCloseV1',
        args: [args.marketId, args.maxOrders, args.maxPositions],
      }),
  };
}

export function useIDiesisPerpDeployPromoteToLive(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'promoteToLive',
        args: [args.marketId],
      }),
  };
}

export function useIDiesisPerpDeployProposePerpPolicyV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, expectedRevision: bigint, expectedKeysetEpoch: bigint, backstopTopupBps: number, tiers: readonly { maxNotional: bigint; maxLeverage: number; maintenanceMarginBps: number }[], nextSigners: readonly `0x${string}`[], nextThreshold: number, signatures: readonly { signer: `0x${string}`; r: `0x${string}`; s: `0x${string}`; v: number }[] }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, expectedRevision: bigint, expectedKeysetEpoch: bigint, backstopTopupBps: number, tiers: readonly { maxNotional: bigint; maxLeverage: number; maintenanceMarginBps: number }[], nextSigners: readonly `0x${string}`[], nextThreshold: number, signatures: readonly { signer: `0x${string}`; r: `0x${string}`; s: `0x${string}`; v: number }[] }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'proposePerpPolicyV1',
        args: [args.marketId, args.expectedRevision, args.expectedKeysetEpoch, args.backstopTopupBps, args.tiers, args.nextSigners, args.nextThreshold, args.signatures],
      }),
  };
}

export function useIDiesisPerpDeployRecordAuctionWin(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, operator: `0x${string}`, registrationDigest: `0x${string}`, evidenceHash: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, operator: `0x${string}`, registrationDigest: `0x${string}`, evidenceHash: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpDeployAbi,
        functionName: 'recordAuctionWin',
        args: [args.marketId, args.operator, args.registrationDigest, args.evidenceHash],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisPerpDeployActivatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpDeployAbi,
    eventName: 'Activated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpDeployAuctionWinRecordedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpDeployAbi,
    eventName: 'AuctionWinRecorded',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpDeployClosedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpDeployAbi,
    eventName: 'Closed',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpDeployDelistingEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpDeployAbi,
    eventName: 'Delisting',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpDeployLiveStartedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpDeployAbi,
    eventName: 'LiveStarted',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpDeployPerpMarketClosePreparedV1Event(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpDeployAbi,
    eventName: 'PerpMarketClosePreparedV1',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpDeployPerpMarketInitializedV1Event(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpDeployAbi,
    eventName: 'PerpMarketInitializedV1',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpDeployPerpMarketInitializedV2Event(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpDeployAbi,
    eventName: 'PerpMarketInitializedV2',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpDeploySlashedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpDeployAbi,
    eventName: 'Slashed',
    onLogs: (logs) => logs.forEach(listener),
  });
}
