// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisPerpsBookAbi } from '../../generated/viem/IDiesisPerpsBook.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisPerpsBookGetIsolatedMargin(address: Address, args: { trader: `0x${string}`, marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisPerpsBookAbi,
    functionName: 'getIsolatedMargin',
    args: [args.trader, args.marketId],
  });
}

export function useIDiesisPerpsBookGetPosition(address: Address, args: { trader: `0x${string}`, marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisPerpsBookAbi,
    functionName: 'getPosition',
    args: [args.trader, args.marketId],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisPerpsBookAdjustIsolatedMargin(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, marginDelta: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, marginDelta: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'adjustIsolatedMargin',
        args: [args.marketId, args.marginDelta],
      }),
  };
}

export function useIDiesisPerpsBookAmendPerpOrderV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { orderId: `0x${string}`, price: bigint, amount: bigint, expiry: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { orderId: `0x${string}`, price: bigint, amount: bigint, expiry: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'amendPerpOrderV1',
        args: [args.orderId, args.price, args.amount, args.expiry],
      }),
  };
}

export function useIDiesisPerpsBookApplyPerpFundingV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, fundingRateBps: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, fundingRateBps: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'applyPerpFundingV1',
        args: [args.marketId, args.fundingRateBps],
      }),
  };
}

export function useIDiesisPerpsBookCancelPerpOrderV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { orderId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { orderId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'cancelPerpOrderV1',
        args: [args.orderId],
      }),
  };
}

export function useIDiesisPerpsBookExecutePerpTradeV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { makerOrderId: `0x${string}`, takerOrderId: `0x${string}`, fillPrice: bigint, fillQty: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { makerOrderId: `0x${string}`, takerOrderId: `0x${string}`, fillPrice: bigint, fillQty: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'executePerpTradeV1',
        args: [args.makerOrderId, args.takerOrderId, args.fillPrice, args.fillQty],
      }),
  };
}

export function useIDiesisPerpsBookExpirePerpOrderV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { orderId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { orderId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'expirePerpOrderV1',
        args: [args.orderId],
      }),
  };
}

export function useIDiesisPerpsBookFinalizePerpFeeEpochV2(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, epoch: bigint, snapshotHash: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, epoch: bigint, snapshotHash: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'finalizePerpFeeEpochV2',
        args: [args.marketId, args.epoch, args.snapshotHash],
      }),
  };
}

export function useIDiesisPerpsBookSubmitExchangeActionsV2(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { encodedActions: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { encodedActions: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'submitExchangeActionsV2',
        args: [args.encodedActions],
      }),
  };
}

export function useIDiesisPerpsBookSubmitPerpOrderV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, side: number, orderType: number, price: bigint, amount: bigint, flags: number, marginType: number, expiry: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, side: number, orderType: number, price: bigint, amount: bigint, flags: number, marginType: number, expiry: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'submitPerpOrderV1',
        args: [args.marketId, args.side, args.orderType, args.price, args.amount, args.flags, args.marginType, args.expiry],
      }),
  };
}

export function useIDiesisPerpsBookSubmitSignedPerpActionsV2(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { signedEnvelope: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { signedEnvelope: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'submitSignedPerpActionsV2',
        args: [args.signedEnvelope],
      }),
  };
}

export function useIDiesisPerpsBookUpdatePerpMarkV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, markPrice: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, markPrice: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'updatePerpMarkV1',
        args: [args.marketId, args.markPrice],
      }),
  };
}

export function useIDiesisPerpsBookUpdatePerpOracleV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, indexPrice: bigint, markPrice: bigint, observedAt: bigint, oracleRound: bigint, sourceSetHash: `0x${string}`, evidenceHash: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, indexPrice: bigint, markPrice: bigint, observedAt: bigint, oracleRound: bigint, sourceSetHash: `0x${string}`, evidenceHash: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'updatePerpOracleV1',
        args: [args.marketId, args.indexPrice, args.markPrice, args.observedAt, args.oracleRound, args.sourceSetHash, args.evidenceHash],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisPerpsBookExchangeActionAcceptedV2Event(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'ExchangeActionAcceptedV2',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookExchangeActionRejectedV2Event(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'ExchangeActionRejectedV2',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookExchangeL3MutationV2Event(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'ExchangeL3MutationV2',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookFundingAppliedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'FundingApplied',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookIsolatedMarginAdjustedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'IsolatedMarginAdjusted',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookMarkPriceUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'MarkPriceUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookOrderCancelledEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'OrderCancelled',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookOrderFilledEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'OrderFilled',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookOrderPlacedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'OrderPlaced',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookPositionClosedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'PositionClosed',
    onLogs: (logs) => logs.forEach(listener),
  });
}
