// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisSettlementAbi } from '../../generated/viem/IDiesisSettlement.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisSettlementAvailableBalance(address: Address, args: { user: `0x${string}`, token: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisSettlementAbi,
    functionName: 'availableBalance',
    args: [args.user, args.token],
  });
}

export function useIDiesisSettlementGetTradingKeyAuth(address: Address, args: { owner: `0x${string}`, tradingKey: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisSettlementAbi,
    functionName: 'getTradingKeyAuth',
    args: [args.owner, args.tradingKey],
  });
}

export function useIDiesisSettlementIsNonceUsed(address: Address, args: { user: `0x${string}`, nonce: bigint }) {
  return useReadContract({
    address,
    abi: IDiesisSettlementAbi,
    functionName: 'isNonceUsed',
    args: [args.user, args.nonce],
  });
}

export function useIDiesisSettlementTotalBalance(address: Address, args: { user: `0x${string}`, token: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisSettlementAbi,
    functionName: 'totalBalance',
    args: [args.user, args.token],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisSettlementAuthorizeSessionKeyV2(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { sessionKey: `0x${string}`, actionScope: bigint, validUntil: bigint, maxNotionalOrSpend: bigint, allowedMarketsMask: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { sessionKey: `0x${string}`, actionScope: bigint, validUntil: bigint, maxNotionalOrSpend: bigint, allowedMarketsMask: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'authorizeSessionKeyV2',
        args: [args.sessionKey, args.actionScope, args.validUntil, args.maxNotionalOrSpend, args.allowedMarketsMask],
      }),
  };
}

export function useIDiesisSettlementCancelNonceWord(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { wordPos: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { wordPos: bigint }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'cancelNonceWord',
        args: [args.wordPos],
      }),
  };
}

export function useIDiesisSettlementCancelOrderNonce(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { nonce: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { nonce: bigint }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'cancelOrderNonce',
        args: [args.nonce],
      }),
  };
}

export function useIDiesisSettlementCreditRouterDeposit(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { user: `0x${string}`, token: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { user: `0x${string}`, token: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'creditRouterDeposit',
        args: [args.user, args.token, args.amount],
      }),
  };
}

export function useIDiesisSettlementDebitRouterWithdrawal(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { user: `0x${string}`, token: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { user: `0x${string}`, token: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'debitRouterWithdrawal',
        args: [args.user, args.token, args.amount],
      }),
  };
}

export function useIDiesisSettlementDeposit(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { token: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { token: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'deposit',
        args: [args.token, args.amount],
      }),
  };
}

export function useIDiesisSettlementFundPerpBackstopV1(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, amount: bigint, nonce: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, amount: bigint, nonce: bigint }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'fundPerpBackstopV1',
        args: [args.marketId, args.amount, args.nonce],
      }),
  };
}

export function useIDiesisSettlementRegisterTradingKey(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { tradingKey: `0x${string}`, validUntil: bigint, maxOrderNotional: bigint, allowedMarketsMask: `0x${string}`, canWithdraw: boolean }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { tradingKey: `0x${string}`, validUntil: bigint, maxOrderNotional: bigint, allowedMarketsMask: `0x${string}`, canWithdraw: boolean }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'registerTradingKey',
        args: [args.tradingKey, args.validUntil, args.maxOrderNotional, args.allowedMarketsMask, args.canWithdraw],
      }),
  };
}

export function useIDiesisSettlementRevokeSessionKeyV2(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { sessionKey: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { sessionKey: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'revokeSessionKeyV2',
        args: [args.sessionKey],
      }),
  };
}

export function useIDiesisSettlementRevokeTradingKey(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { tradingKey: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { tradingKey: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'revokeTradingKey',
        args: [args.tradingKey],
      }),
  };
}

export function useIDiesisSettlementWithdraw(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { token: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { token: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: IDiesisSettlementAbi,
        functionName: 'withdraw',
        args: [args.token, args.amount],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisSettlementDepositEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisSettlementAbi,
    eventName: 'Deposit',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisSettlementNonceCancelledEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisSettlementAbi,
    eventName: 'NonceCancelled',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisSettlementPerpBackstopFundedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisSettlementAbi,
    eventName: 'PerpBackstopFunded',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisSettlementTradingKeyRegisteredEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisSettlementAbi,
    eventName: 'TradingKeyRegistered',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisSettlementTradingKeyRevokedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisSettlementAbi,
    eventName: 'TradingKeyRevoked',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisSettlementWithdrawalEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisSettlementAbi,
    eventName: 'Withdrawal',
    onLogs: (logs) => logs.forEach(listener),
  });
}
