// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisPerpsBookAbi } from '../../generated/viem/IDiesisPerpsBook.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIDiesisPerpsBookGetIsolatedMargin(address: Address, args: { trader: `0x${string}`, marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisPerpsBookAbi,
    functionName: 'getIsolatedMargin',
    args: [args.trader, args.marketId],
  });
}

export function useIDiesisPerpsBookGetPosition(address: Address, args: { trader: `0x${string}`, marketId: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IDiesisPerpsBookAbi,
    functionName: 'getPosition',
    args: [args.trader, args.marketId],
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIDiesisPerpsBookAdjustIsolatedMargin(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, marginDelta: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, marginDelta: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'adjustIsolatedMargin',
        args: [args.marketId, args.marginDelta],
      }),
  };
}

export function useIDiesisPerpsBookAdvancePricedPerpRuntime(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { policyHash: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { policyHash: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'advancePricedPerpRuntime',
        args: [args.policyHash],
      }),
  };
}

export function useIDiesisPerpsBookAmendPerpOrder(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { orderId: `0x${string}`, price: bigint, amount: bigint, expiry: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { orderId: `0x${string}`, price: bigint, amount: bigint, expiry: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'amendPerpOrder',
        args: [args.orderId, args.price, args.amount, args.expiry],
      }),
  };
}

export function useIDiesisPerpsBookApplyPerpFunding(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, fundingRateBps: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, fundingRateBps: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'applyPerpFunding',
        args: [args.marketId, args.fundingRateBps],
      }),
  };
}

export function useIDiesisPerpsBookCancelPerpOrder(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { orderId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { orderId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'cancelPerpOrder',
        args: [args.orderId],
      }),
  };
}

export function useIDiesisPerpsBookExecutePerpTrade(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { makerOrderId: `0x${string}`, takerOrderId: `0x${string}`, fillPrice: bigint, fillQty: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { makerOrderId: `0x${string}`, takerOrderId: `0x${string}`, fillPrice: bigint, fillQty: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'executePerpTrade',
        args: [args.makerOrderId, args.takerOrderId, args.fillPrice, args.fillQty],
      }),
  };
}

export function useIDiesisPerpsBookExpirePerpOrder(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { orderId: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { orderId: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'expirePerpOrder',
        args: [args.orderId],
      }),
  };
}

export function useIDiesisPerpsBookFinalizePerpFeeEpoch(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, epoch: bigint, snapshotHash: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, epoch: bigint, snapshotHash: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'finalizePerpFeeEpoch',
        args: [args.marketId, args.epoch, args.snapshotHash],
      }),
  };
}

export function useIDiesisPerpsBookSubmitBoundSessionActions(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { encodedWrapper: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { encodedWrapper: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'submitBoundSessionActions',
        args: [args.encodedWrapper],
      }),
  };
}

export function useIDiesisPerpsBookSubmitExchangeActions(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { encodedActions: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { encodedActions: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'submitExchangeActions',
        args: [args.encodedActions],
      }),
  };
}

export function useIDiesisPerpsBookSubmitPerpOrder(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, side: number, orderType: number, price: bigint, amount: bigint, flags: number, marginType: number, expiry: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, side: number, orderType: number, price: bigint, amount: bigint, flags: number, marginType: number, expiry: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'submitPerpOrder',
        args: [args.marketId, args.side, args.orderType, args.price, args.amount, args.flags, args.marginType, args.expiry],
      }),
  };
}

export function useIDiesisPerpsBookSubmitSponsoredPerpActions(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { signedEnvelope: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { signedEnvelope: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'submitSponsoredPerpActions',
        args: [args.signedEnvelope],
      }),
  };
}

export function useIDiesisPerpsBookUpdatePerpMark(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, markPrice: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, markPrice: bigint }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'updatePerpMark',
        args: [args.marketId, args.markPrice],
      }),
  };
}

export function useIDiesisPerpsBookUpdatePerpOracle(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { marketId: `0x${string}`, indexPrice: bigint, markPrice: bigint, observedAt: bigint, oracleRound: bigint, sourceSetHash: `0x${string}`, evidenceHash: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { marketId: `0x${string}`, indexPrice: bigint, markPrice: bigint, observedAt: bigint, oracleRound: bigint, sourceSetHash: `0x${string}`, evidenceHash: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'updatePerpOracle',
        args: [args.marketId, args.indexPrice, args.markPrice, args.observedAt, args.oracleRound, args.sourceSetHash, args.evidenceHash],
      }),
  };
}

export function useIDiesisPerpsBookUpdatePricedOracle(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { payload: `0x${string}` }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { payload: `0x${string}` }) =>
      writeContract({
        address,
        abi: IDiesisPerpsBookAbi,
        functionName: 'updatePricedOracle',
        args: [args.payload],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIDiesisPerpsBookExchangeActionAcceptedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'ExchangeActionAccepted',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookExchangeActionRejectedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'ExchangeActionRejected',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookExchangeL3MutationEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'ExchangeL3Mutation',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookFundingAppliedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'FundingApplied',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookIsolatedMarginAdjustedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'IsolatedMarginAdjusted',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookMarkPriceUpdatedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'MarkPriceUpdated',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookOrderCancelledEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'OrderCancelled',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookOrderFilledEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'OrderFilled',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookOrderPlacedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'OrderPlaced',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookPositionClosedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'PositionClosed',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIDiesisPerpsBookPositionCollateralAdjustedEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IDiesisPerpsBookAbi,
    eventName: 'PositionCollateralAdjusted',
    onLogs: (logs) => logs.forEach(listener),
  });
}
