// Auto-generated by abi-typegen. Do not edit manually.
import { ILiquidStakedDSAbi } from '../../generated/viem/ILiquidStakedDS.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useILiquidStakedDSAllowance(address: Address, args: { owner: `0x${string}`, spender: `0x${string}` }) {
  return useReadContract({
    address,
    abi: ILiquidStakedDSAbi,
    functionName: 'allowance',
    args: [args.owner, args.spender],
  });
}

export function useILiquidStakedDSBalanceOf(address: Address, args: { account: `0x${string}` }) {
  return useReadContract({
    address,
    abi: ILiquidStakedDSAbi,
    functionName: 'balanceOf',
    args: [args.account],
  });
}

export function useILiquidStakedDSDecimals(address: Address) {
  return useReadContract({
    address,
    abi: ILiquidStakedDSAbi,
    functionName: 'decimals',
  });
}

export function useILiquidStakedDSName(address: Address) {
  return useReadContract({
    address,
    abi: ILiquidStakedDSAbi,
    functionName: 'name',
  });
}

export function useILiquidStakedDSSymbol(address: Address) {
  return useReadContract({
    address,
    abi: ILiquidStakedDSAbi,
    functionName: 'symbol',
  });
}

export function useILiquidStakedDSTotalSupply(address: Address) {
  return useReadContract({
    address,
    abi: ILiquidStakedDSAbi,
    functionName: 'totalSupply',
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useILiquidStakedDSApprove(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { spender: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { spender: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: ILiquidStakedDSAbi,
        functionName: 'approve',
        args: [args.spender, args.amount],
      }),
  };
}

export function useILiquidStakedDSBurn(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { amount: bigint }) =>
      writeContract({
        address,
        abi: ILiquidStakedDSAbi,
        functionName: 'burn',
        args: [args.amount],
      }),
  };
}

export function useILiquidStakedDSBurnFrom(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { from: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { from: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: ILiquidStakedDSAbi,
        functionName: 'burnFrom',
        args: [args.from, args.amount],
      }),
  };
}

export function useILiquidStakedDSMint(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { to: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { to: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: ILiquidStakedDSAbi,
        functionName: 'mint',
        args: [args.to, args.amount],
      }),
  };
}

export function useILiquidStakedDSTransfer(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { to: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { to: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: ILiquidStakedDSAbi,
        functionName: 'transfer',
        args: [args.to, args.amount],
      }),
  };
}

export function useILiquidStakedDSTransferFrom(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { from: `0x${string}`, to: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { from: `0x${string}`, to: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: ILiquidStakedDSAbi,
        functionName: 'transferFrom',
        args: [args.from, args.to, args.amount],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useILiquidStakedDSApprovalEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: ILiquidStakedDSAbi,
    eventName: 'Approval',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useILiquidStakedDSTransferEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: ILiquidStakedDSAbi,
    eventName: 'Transfer',
    onLogs: (logs) => logs.forEach(listener),
  });
}
