// Auto-generated by abi-typegen. Do not edit manually.
import { IWrappedDSAbi } from '../../generated/viem/IWrappedDS.abi.js';
import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';
import type { Address } from 'viem';

// ── Read hooks ─────────────────────────────────────────────────────────

export function useIWrappedDSAllowance(address: Address, args: { owner: `0x${string}`, spender: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IWrappedDSAbi,
    functionName: 'allowance',
    args: [args.owner, args.spender],
  });
}

export function useIWrappedDSBalanceOf(address: Address, args: { account: `0x${string}` }) {
  return useReadContract({
    address,
    abi: IWrappedDSAbi,
    functionName: 'balanceOf',
    args: [args.account],
  });
}

export function useIWrappedDSDecimals(address: Address) {
  return useReadContract({
    address,
    abi: IWrappedDSAbi,
    functionName: 'decimals',
  });
}

export function useIWrappedDSName(address: Address) {
  return useReadContract({
    address,
    abi: IWrappedDSAbi,
    functionName: 'name',
  });
}

export function useIWrappedDSSymbol(address: Address) {
  return useReadContract({
    address,
    abi: IWrappedDSAbi,
    functionName: 'symbol',
  });
}

export function useIWrappedDSTotalSupply(address: Address) {
  return useReadContract({
    address,
    abi: IWrappedDSAbi,
    functionName: 'totalSupply',
  });
}

// ── Write hooks ────────────────────────────────────────────────────────

export function useIWrappedDSApprove(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { spender: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { spender: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: IWrappedDSAbi,
        functionName: 'approve',
        args: [args.spender, args.amount],
      }),
  };
}

export function useIWrappedDSDeposit(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (options?: { value?: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (options?: { value?: bigint }) =>
      writeContract({
        address,
        abi: IWrappedDSAbi,
        functionName: 'deposit',
        value: options?.value,
      }),
  };
}

export function useIWrappedDSTransfer(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { to: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { to: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: IWrappedDSAbi,
        functionName: 'transfer',
        args: [args.to, args.amount],
      }),
  };
}

export function useIWrappedDSTransferFrom(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { from: `0x${string}`, to: `0x${string}`, amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { from: `0x${string}`, to: `0x${string}`, amount: bigint }) =>
      writeContract({
        address,
        abi: IWrappedDSAbi,
        functionName: 'transferFrom',
        args: [args.from, args.to, args.amount],
      }),
  };
}

export function useIWrappedDSWithdraw(
  address: Address,
): Omit<UseWriteContractReturnType, 'writeContract'> & {
  write: (args: { amount: bigint }) => void;
} {
  const { writeContract, ...rest } = useWriteContract();
  return {
    ...rest,
    write: (args: { amount: bigint }) =>
      writeContract({
        address,
        abi: IWrappedDSAbi,
        functionName: 'withdraw',
        args: [args.amount],
      }),
  };
}

// ── Event hooks ────────────────────────────────────────────────────────

export function useIWrappedDSApprovalEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IWrappedDSAbi,
    eventName: 'Approval',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIWrappedDSDepositEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IWrappedDSAbi,
    eventName: 'Deposit',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIWrappedDSTransferEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IWrappedDSAbi,
    eventName: 'Transfer',
    onLogs: (logs) => logs.forEach(listener),
  });
}

export function useIWrappedDSWithdrawalEvent(address: Address, listener: (log: any) => void) {
  return useWatchContractEvent({
    address,
    abi: IWrappedDSAbi,
    eventName: 'Withdrawal',
    onLogs: (logs) => logs.forEach(listener),
  });
}
