// Auto-generated by abi-typegen. Do not edit manually.
import { DiesisPrivacyPoolsAbi } from '../../generated/viem/DiesisPrivacyPools.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getDiesisPrivacyPoolsContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof DiesisPrivacyPoolsAbi, TClient> {
  return getContract({ address, abi: DiesisPrivacyPoolsAbi, client });
}

export type DiesisPrivacyPoolsRegisterProviderParams = {
  provider: `0x${string}`;
  name: string;
};

export type DiesisPrivacyPoolsTransferOwnershipParams = {
  newOwner: `0x${string}`;
};

export type DiesisPrivacyPoolsUpdateAssociationSetParams = {
  newRoot: `0x${string}`;
};

