// Auto-generated by abi-typegen. Do not edit manually.
import { DiesisPublicResolverAbi } from '../../generated/viem/DiesisPublicResolver.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getDiesisPublicResolverContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof DiesisPublicResolverAbi, TClient> {
  return getContract({ address, abi: DiesisPublicResolverAbi, client });
}

export type DiesisPublicResolverSetAddrBytes32Uint256BytesParams = {
  node: `0x${string}`;
  coinType: bigint;
  value: `0x${string}`;
};

export type DiesisPublicResolverSetAddrBytes32AddressParams = {
  node: `0x${string}`;
  value: `0x${string}`;
};

export type DiesisPublicResolverSetAgentRecordParams = {
  node: `0x${string}`;
  agentId: `0x${string}`;
  record: { agentId: `0x${string}`; endpoint: string; publicKey: `0x${string}`; capabilitiesHash: `0x${string}`; policyHash: `0x${string}`; validFrom: bigint; validUntil: bigint; enabled: boolean };
};

export type DiesisPublicResolverSetContenthashParams = {
  node: `0x${string}`;
  value: `0x${string}`;
};

export type DiesisPublicResolverSetContractRecordParams = {
  node: `0x${string}`;
  role: `0x${string}`;
  target: `0x${string}`;
};

export type DiesisPublicResolverSetPaymentRouteParams = {
  node: `0x${string}`;
  routeId: `0x${string}`;
  route: { chainId: bigint; token: `0x${string}`; recipient: `0x${string}`; priority: number; feeBpsLimit: number; memoPolicy: `0x${string}`; enabled: boolean };
};

export type DiesisPublicResolverSetRecordsParams = {
  node: `0x${string}`;
  calls: readonly `0x${string}`[];
};

export type DiesisPublicResolverSetRouteRecordParams = {
  node: `0x${string}`;
  record: { routeId: `0x${string}`; routeKind: number; target: `0x${string}`; contractTarget: `0x${string}`; policyHash: `0x${string}`; wildcard: boolean; enabled: boolean };
};

export type DiesisPublicResolverSetTextParams = {
  node: `0x${string}`;
  key: string;
  value: string;
};

export type DiesisPublicResolverSetTrustedWriterParams = {
  writer: `0x${string}`;
  approved: boolean;
};

export type DiesisPublicResolverSetWildcardPaymentRoutingAllowedParams = {
  node: `0x${string}`;
  approved: boolean;
};

/**
 * @dev Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
 */
export type DiesisPublicResolverTransferOwnershipParams = {
  newOwner: `0x${string}`;
};

