// Auto-generated by abi-typegen. Do not edit manually.
import { DiesisConfigAbi } from '../../generated/viem/DiesisConfig.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getDiesisConfigContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof DiesisConfigAbi, TClient> {
  return getContract({ address, abi: DiesisConfigAbi, client });
}

export type DiesisConfigSetDelegationFanoutLimitParams = {
  v: bigint;
};

export type DiesisConfigSetExitDelayCheckpointsParams = {
  v: bigint;
};

export type DiesisConfigSetExitDelaySecondsParams = {
  v: bigint;
};

export type DiesisConfigSetLivenessDowntimeLimitParams = {
  v: bigint;
};

export type DiesisConfigSetLivenessMissedBlockLimitParams = {
  v: bigint;
};

export type DiesisConfigSetMintReceiverParams = {
  v: `0x${string}`;
};

export type DiesisConfigSetNetworkBurnCutParams = {
  v: bigint;
};

export type DiesisConfigSetOperatorTakeRateParams = {
  v: bigint;
};

export type DiesisConfigSetReliabilityFloorParams = {
  v: bigint;
};

export type DiesisConfigSetReliabilitySampleCheckpointsParams = {
  v: number;
};

export type DiesisConfigSetRewardStreamPerSecondParams = {
  v: bigint;
};

export type DiesisConfigSetSurplusRewardBurnCutParams = {
  v: bigint;
};

export type DiesisConfigSetTreasuryCutParams = {
  v: bigint;
};

export type DiesisConfigSetValidatorBondFloorParams = {
  v: bigint;
};

/**
 * @dev Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
 */
export type DiesisConfigTransferOwnershipParams = {
  newOwner: `0x${string}`;
};

