// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisMarginAbi } from '../../generated/viem/IDiesisMargin.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getIDiesisMarginContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof IDiesisMarginAbi, TClient> {
  return getContract({ address, abi: IDiesisMarginAbi, client });
}

/**
 * System-owned canonical frontier resolution. External callers are rejected.
 */
export type IDiesisMarginResolvePerpProtectionParams = {
  marketId: `0x${string}`;
};

