// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisSpotBookAbi } from '../../generated/viem/IDiesisSpotBook.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getIDiesisSpotBookContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof IDiesisSpotBookAbi, TClient> {
  return getContract({ address, abi: IDiesisSpotBookAbi, client });
}

/**
 * Amend an active order owned by the caller.
 * @dev Cancel-and-replace preserving the original `orderId`. Preserving the      id keeps user/market indexes and signed-intent nonce mappings stable.      Requires the original market to still be active and new price/amount      to be nonzero.
 * @param orderId Existing order id.
 * @param newPrice New limit price in ticks.
 * @param newAmount New base quantity in lots.
 * @param newFlags Replacement order flags.
 * @returns newOrderId Equal to `orderId`; retained for ABI compatibility with cancel-and-replace clients.
 */
export type IDiesisSpotBookAmendOrderParams = {
  orderId: `0x${string}`;
  newPrice: bigint;
  newAmount: bigint;
  newFlags: number;
};

/**
 * Cancel an active order owned by the caller.
 * @dev Releases the order's locked collateral and clears the order storage.      Historical user and market order lists may still contain the order id;      clients should filter by order existence. Cancelling a dormant signed      stop removes its bounded stop-index membership and releases its lock.
 * @param orderId Canonical order identifier.
 */
export type IDiesisSpotBookCancelOrderParams = {
  orderId: `0x${string}`;
};

/**
 * Execute a one-sided legacy spot fill.
 * @dev System-only in production. Kept for compatibility and recovery tests.
 */
export type IDiesisSpotBookExecuteSpotFillParams = {
  orderId: `0x${string}`;
  fillPrice: bigint;
  fillQty: bigint;
};

/**
 * Atomically settle a matched maker/taker spot trade.
 * @dev System-only. Emits one `OrderFilled` event per side and clears completed orders.
 */
export type IDiesisSpotBookExecuteSpotTradeParams = {
  makerOrderId: `0x${string}`;
  takerOrderId: `0x${string}`;
  fillPrice: bigint;
  fillQty: bigint;
};

/**
 * Finalize an ended opening auction and return the market to active trading.
 * @dev System-only. Runs the batch auction, settles crossing orders, restores      residual live orders into the continuous BBO cache, emits      `BatchAuctionCleared`, and stores final auction totals.
 */
export type IDiesisSpotBookFinalizeOpeningAuctionParams = {
  marketId: `0x${string}`;
};

/**
 * Start an opening auction for an active empty market.
 * @dev System-only. The market must be active and have no live open orders.      Historical cleared order ids do not block auction start, but the call      charges gas for scanning those historical ids.
 */
export type IDiesisSpotBookStartOpeningAuctionParams = {
  marketId: `0x${string}`;
  startBlock: bigint;
  endBlock: bigint;
  referencePrice: bigint;
};

/**
 * Submit one strictly bounded canonical V2 action batch.
 * @dev The ordinary EVM caller authenticates the batch. The encoded bytes      contain no action-level signature or replay nonce. `resultHash`      commits to the original bytes and every ordered action outcome.
 */
export type IDiesisSpotBookSubmitExchangeActionsV2Params = {
  encodedActions: `0x${string}`;
};

/**
 * Place a limit order in an active spot market.
 * @dev Requires an active market, `priceTicks > 0`, `amountLots > 0`, a prior      settlement deposit flag, and enough available collateral. Buy orders      lock quote collateral equal to `priceTicks * amountLots`; sell orders      lock base collateral equal to `amountLots`.
 * @param marketId Canonical market identifier.
 * @param side Order side: 0 = Buy, 1 = Sell.
 * @param priceTicks Limit price in market ticks.
 * @param amountLots Base quantity in market lots.
 * @param flags Bit flags from `DiesisOrderFlags`.
 * @returns orderId Canonical order identifier.
 */
export type IDiesisSpotBookSubmitLimitOrderParams = {
  marketId: `0x${string}`;
  side: number;
  priceTicks: bigint;
  amountLots: bigint;
  flags: number;
};

/**
 * Submit a market order intent against the active continuous book.
 * @dev Requires an active market and `amountLots > 0`. The returned      `filledAmount` is currently zero; economic fills are emitted as      canonical `OrderFilled` events when matching settles.
 * @param marketId Canonical market identifier.
 * @param side Order side: 0 = Buy, 1 = Sell.
 * @param amountLots Base quantity in market lots.
 * @returns filledAmount Reserved fill amount field.
 * @returns orderId Canonical order identifier.
 */
export type IDiesisSpotBookSubmitMarketOrderParams = {
  marketId: `0x${string}`;
  side: number;
  amountLots: bigint;
};

/**
 * Submit a signed request to cancel all active orders in one market.
 * @dev The payload is a JSON-encoded signed cancel-all spot intent. The      signature binds trader, market, expiry, and replay nonce. The call      scans the trader's historical user-order list for `marketId`, charges      per scanned order, cancels currently active matching orders, and rolls      back nonce consumption if cancellation fails.
 * @param signedCancelAllJson ABI `bytes` containing UTF-8 JSON for the signed cancel-all payload.
 * @returns cancelled Number of active orders cancelled.
 */
export type IDiesisSpotBookSubmitSignedCancelAllSpotIntentParams = {
  signedCancelAllJson: `0x${string}`;
};

/**
 * Submit a signed order or cancel intent.
 * @dev The payload is a JSON-encoded `SignedIntent`. Order intents may be      submitted by any relayer; the precompile verifies the signature and      uses the signed trader as the effective caller. Trading-key signed      order and cancel intents are constrained by the key's market mask and      notional limit. This ABI intentionally declares no return value because      order and cancel variants have different raw return data. Clients that      need the returned order id should either call direct order methods or      use a low-level call and decode the variant-specific bytes.
 * @param signedIntentJson ABI `bytes` containing UTF-8 JSON for the signed intent.
 */
export type IDiesisSpotBookSubmitSignedSpotIntentParams = {
  signedIntentJson: `0x${string}`;
};

/**
 * Activate dormant stops triggered by the market's last settled trade.
 * @dev Permissionless bounded continuation. A buy stop triggers when the      canonical last-trade price rises to or above its trigger price; a sell      stop triggers when it falls to or below. `maxOrders` is clamped to the      protocol activation limit and to the call's gas headroom; the call      never triggers from an oracle, RPC quote, or user-supplied      observation. Each activated stop inserts into the live book and matches      at its limit/protection price (a stop-market executes as an IOC      protected limit) and emits a `StopOrderTriggered` event. A paused      market or a market with no settled trade activates nothing.
 * @param marketId Canonical market identifier.
 * @param maxOrders Requested maximum activations this call.
 * @returns activated Number of stops activated.
 * @returns hasMore True when triggerable stops remain past this call's budget.
 */
export type IDiesisSpotBookTriggerSpotStopsParams = {
  marketId: `0x${string}`;
  maxOrders: number;
};

