// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisReverseRegistrarAbi } from '../../generated/viem/IDiesisReverseRegistrar.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getIDiesisReverseRegistrarContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof IDiesisReverseRegistrarAbi, TClient> {
  return getContract({ address, abi: IDiesisReverseRegistrarAbi, client });
}

export type IDiesisReverseRegistrarSetControllerParams = {
  controller: `0x${string}`;
  approved: boolean;
};

export type IDiesisReverseRegistrarSetNameParams = {
  name_: string;
};

export type IDiesisReverseRegistrarSetNameForAddrParams = {
  addr: `0x${string}`;
  name_: string;
};

