// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisPerpsBookAbi } from '../../generated/viem/IDiesisPerpsBook.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getIDiesisPerpsBookContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof IDiesisPerpsBookAbi, TClient> {
  return getContract({ address, abi: IDiesisPerpsBookAbi, client });
}

/**
 * Add or remove isolated margin on the caller's position.
 * @dev A positive `marginDelta` locks quote collateral from the caller's      available settlement balance into the position's isolated margin; a      negative one releases it. Reductions are consensus-guarded and revert      when they would leave the position below maintenance margin. Emits      {IsolatedMarginAdjusted}.
 * @param marketId The market whose position is adjusted.
 * @param marginDelta Quote-denominated signed adjustment.
 */
export type IDiesisPerpsBookAdjustIsolatedMarginParams = {
  marketId: `0x${string}`;
  marginDelta: bigint;
};

/**
 * Request the system-owned canonical priced runtime tick.
 * @dev Inactive until qualified runtime activation. Every caller currently reverts.      Future execution requires authenticated selected authority and a matching policy hash.
 * @param policyHash Commitment of the authenticated execution policy.
 */
export type IDiesisPerpsBookAdvancePricedPerpRuntimeParams = {
  policyHash: `0x${string}`;
};

/**
 * Atomically cancel and replace an order with new price, amount,         expiry, canonical margin reservation, and priority identity.
 */
export type IDiesisPerpsBookAmendPerpOrderParams = {
  orderId: `0x${string}`;
  price: bigint;
  amount: bigint;
  expiry: bigint;
};

/**
 * Advance canonical funding through solvency-frontier segments.
 * @dev System-only and bounded to the protocol funding-rate limit.
 */
export type IDiesisPerpsBookApplyPerpFundingParams = {
  marketId: `0x${string}`;
  fundingRateBps: bigint;
};

/**
 * Cancel an owned V1 order and return all unused canonical margin.
 */
export type IDiesisPerpsBookCancelPerpOrderParams = {
  orderId: `0x${string}`;
};

/**
 * Commit one system-owned opposite-side fill through canonical clearing.
 * @dev Reads and validates both stored V1 orders, derives deterministic      maker/taker fees and persistent frontier proofs, then commits the      PreparedClearingTransactionV1 and both order consumptions under one      outer EVM checkpoint. The lower order ID is the canonical maker.
 */
export type IDiesisPerpsBookExecutePerpTradeParams = {
  makerOrderId: `0x${string}`;
  takerOrderId: `0x${string}`;
  fillPrice: bigint;
  fillQty: bigint;
};

/**
 * Permissionlessly expire a GTD order after its canonical deadline.
 */
export type IDiesisPerpsBookExpirePerpOrderParams = {
  orderId: `0x${string}`;
};

/**
 * Finalize the exact stored snapshot of one closed fee epoch.
 * @dev Native queue/accounting behavior is introduced by X4b M3. This      declaration prevents public ABI drift before that implementation.
 */
export type IDiesisPerpsBookFinalizePerpFeeEpochParams = {
  marketId: `0x${string}`;
  epoch: bigint;
  snapshotHash: `0x${string}`;
};

/**
 * Proposed ordinary-caller bound-session V3 action wrapper.
 * @dev Inactive until a separately accepted resource policy and dispatch revision.      DXS3 contains the expected principal and current positive generation,      followed by unchanged DXA2 bytes. The result commits the full wrapper.      Sponsorship and relayer adapters are unsupported. Counts retain V2 types.
 * @param encodedWrapper Canonical complete DXS3 header and unchanged inner batch.
 * @returns resultHash Full-wrapper commitment using the inherited result framing.
 * @returns acceptedCount Accepted action count in inherited uint16 width.
 * @returns rejectedCount Rejected action count in inherited uint16 width.
 */
export type IDiesisPerpsBookSubmitBoundSessionActionsParams = {
  encodedWrapper: `0x${string}`;
};

/**
 * Encode the shared bounded V2 action call for future Lane B use.
 * @dev The ABI is frozen for tooling parity, but perpetual V2 execution      remains protocol-gated until the Lane B activation revision.      `resultHash` commits to the original bytes and every ordered action outcome.
 */
export type IDiesisPerpsBookSubmitExchangeActionsParams = {
  encodedActions: `0x${string}`;
};

/**
 * Submit one versioned perpetual order funded from canonical settlement custody.
 * @dev The call atomically moves initial margin plus the deterministic fee      reserve from GlobalUserAvailable to the market's UserMargin ledger.      `price` is a nonzero integer tick and price-protected market orders      use it as their worst acceptable execution price. `expiry == 0`      selects GTC; otherwise expiry is a Unix timestamp in seconds.      V1 requires `flags == 0`; reduce-only and advanced time-in-force      semantics are reserved for the bounded V2 action surface.
 */
export type IDiesisPerpsBookSubmitPerpOrderParams = {
  marketId: `0x${string}`;
  side: number;
  orderType: number;
  price: bigint;
  amount: bigint;
  flags: number;
  marginType: number;
  expiry: bigint;
};

/**
 * Execute a sponsored bounded V2 action batch on behalf of a signer.
 * @dev The relayer is the outer transaction sender and pays fees; the      recovered EIP-712 signer of `signedEnvelope` is the trading      principal. The precompile verifies the signature, consumes the      signer's canonical per-trader nonce-bitmap bit, and executes the      exact same canonical action bytes, admission policy, replay      protection, clearing journal, and logs as the direct      `submitExchangeActions` path. Later tasks implement verification      and execution; this freezes the release selector and wire shape.
 * @param signedEnvelope ABI `bytes` containing the canonical signed        perpetual-actions envelope.
 * @returns batchId Canonical identifier committing to the executed batch.
 */
export type IDiesisPerpsBookSubmitSponsoredPerpActionsParams = {
  signedEnvelope: `0x${string}`;
};

/**
 * Advance the canonical scaled mark through solvency-frontier segments.
 * @dev System-only. If a root is reached, the market enters Protection and      persists the original target until liquidation resolves the root.
 */
export type IDiesisPerpsBookUpdatePerpMarkParams = {
  marketId: `0x${string}`;
  markPrice: bigint;
};

/**
 * Persist one validator-attested oracle round for a market.
 * @dev System-only. Accepts strictly increasing rounds and observed-at      timestamps, an active `sourceSetHash`, and a canonical `evidenceHash`      commitment. The call atomically writes the canonical index/mark,      round, observed-at, source-set/evidence commitments, and derived      circuit-breaker/recovery state; there is no operator path that      bypasses freshness or evidence. Later tasks implement the transition;      this freezes the release selector and argument layout.
 * @param marketId Canonical market identifier.
 * @param indexPrice Attested index price.
 * @param markPrice Attested canonical mark price.
 * @param observedAt Canonical observed-at timestamp in seconds.
 * @param oracleRound Monotonic oracle round.
 * @param sourceSetHash Commitment to the active source set.
 * @param evidenceHash Commitment to the ordered aggregation evidence.
 */
export type IDiesisPerpsBookUpdatePerpOracleParams = {
  marketId: `0x${string}`;
  indexPrice: bigint;
  markPrice: bigint;
  observedAt: bigint;
  oracleRound: bigint;
  sourceSetHash: `0x${string}`;
  evidenceHash: `0x${string}`;
};

/**
 * Persist one descriptor-authorized priced oracle observation.
 * @dev System-only, caller address zero. payload is exactly one canonical      DOR2 observation: a 128-byte V2 context/round header followed by a      144-byte observation. The native runtime verifies chain, genesis,      exact parent number/hash, immutable descriptor/source commitments,      tick alignment and canonical observation freshness before writes.      Canonical oracle prices use p; the clearing mirror uses p*PRICE_SCALE.      This distinct selector returns no data and leaves V1 encoding intact.
 */
export type IDiesisPerpsBookUpdatePricedOracleParams = {
  payload: `0x${string}`;
};

