// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisErc20FactoryAbi } from '../../generated/viem/IDiesisErc20Factory.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getIDiesisErc20FactoryContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof IDiesisErc20FactoryAbi, TClient> {
  return getContract({ address, abi: IDiesisErc20FactoryAbi, client });
}

/**
 * Deploy a new ERC-20 at the deterministic address.
 * @dev Reverts with `DuplicateDeployment` if the `(deployer, symbol)` pair      has already been used, with `InvalidSymbolLength` or `InvalidSupply`      on parameter validation, and with `FactoryCallFailed` for any other      precompile-side failure.
 * @param params Deployment parameters.
 * @returns tokenAddress The deterministically derived token address.
 */
export type IDiesisErc20FactoryDeployParams = {
  params: { symbol: `0x${string}`; name: string; initialSupply: bigint; deployer: `0x${string}` };
};

/**
 * Propose a new template bytecode hash. Subject to a 7-day timelock.
 * @dev Multiple proposals overwrite the previous pending hash and reset the timelock.
 */
export type IDiesisErc20FactoryProposeTemplateUpdateParams = {
  newHash: `0x${string}`;
};

