// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisNamePolicyAbi } from '../../generated/viem/IDiesisNamePolicy.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getIDiesisNamePolicyContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof IDiesisNamePolicyAbi, TClient> {
  return getContract({ address, abi: IDiesisNamePolicyAbi, client });
}

export type IDiesisNamePolicyApproveRecoveryParams = {
  node: `0x${string}`;
  newOwner: `0x${string}`;
};

export type IDiesisNamePolicyCancelRecoveryParams = {
  node: `0x${string}`;
  newOwner: `0x${string}`;
};

export type IDiesisNamePolicyFinalizeRecoveryParams = {
  node: `0x${string}`;
  newOwner: `0x${string}`;
};

export type IDiesisNamePolicyGuardedTransferParams = {
  node: `0x${string}`;
  newOwner: `0x${string}`;
};

export type IDiesisNamePolicySetGuardianParams = {
  node: `0x${string}`;
  guardian: `0x${string}`;
  approved: boolean;
};

export type IDiesisNamePolicySetRecoveryConfigParams = {
  node: `0x${string}`;
  threshold: number;
  delay: bigint;
  fallbackOwner: `0x${string}`;
  enabled: boolean;
};

export type IDiesisNamePolicySetTransferLockParams = {
  node: `0x${string}`;
  lockedUntil: bigint;
};

