// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisIssuanceAuctionAbi } from '../../generated/viem/IDiesisIssuanceAuction.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getIDiesisIssuanceAuctionContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof IDiesisIssuanceAuctionAbi, TClient> {
  return getContract({ address, abi: IDiesisIssuanceAuctionAbi, client });
}

/**
 * Place a canonical-USDC bid bound to immutable priced units.
 * @dev The native runtime debits msg.sender and retains the accepted      identity preimage. Successful admission and identical retries      return no data, as with bidUnpricedPerpListing.
 */
export type IDiesisIssuanceAuctionBidPricedPerpListingParams = {
  registration: { marketId: `0x${string}`; baseAsset: `0x${string}`; quoteAsset: `0x${string}`; evidenceHash: `0x${string}`; pricingVersion: number; priceDenominator: bigint };
};

/**
 * Place a canonical-USDC bid bound to one perpetual registration.
 * @dev The native runtime debits USDC; this selector is intentionally not      payable and accepts no caller-supplied winner.
 */
export type IDiesisIssuanceAuctionBidUnpricedPerpListingParams = {
  registration: { marketId: `0x${string}`; baseAsset: `0x${string}`; quoteAsset: `0x${string}`; evidenceHash: `0x${string}` };
};

