// Auto-generated by abi-typegen. Do not edit manually.
import { IDiesisMarketsAbi } from '../../generated/viem/IDiesisMarkets.abi.js';
import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';

export function getIDiesisMarketsContract<TClient extends Client>(
  address: Address,
  client: TClient,
): GetContractReturnType<typeof IDiesisMarketsAbi, TClient> {
  return getContract({ address, abi: IDiesisMarketsAbi, client });
}

/**
 * @dev System-only. Market must exist and `referencePrice` must be nonzero.
 */
export type IDiesisMarketsCheckCircuitBreakerParams = {
  marketId: `0x${string}`;
  currentPrice: bigint;
  referencePrice: bigint;
  thresholdBps: bigint;
};

/**
 * @dev `bond`, when nonzero, is deducted from the creator's WDS settlement balance. Reverts after the append-only 256-market ordinal namespace is full.
 */
export type IDiesisMarketsCreateSpotMarketParams = {
  baseToken: `0x${string}`;
  quoteToken: `0x${string}`;
  tickSize: bigint;
  lotSize: bigint;
  bond: bigint;
};

/**
 * @dev Deploys a token through the factory and creates its USDC spot market atomically.
 */
export type IDiesisMarketsDeployTokenAndSpotBookParams = {
  symbol: `0x${string}`;
  name: string;
  initialSupply: bigint;
  dsBond: bigint;
  usdcFee: bigint;
};

export type IDiesisMarketsResumeMarketParams = {
  marketId: `0x${string}`;
};

